### ISSUE TITLE
No autocomplete for native JavaScript props and methods

### ISSUE THREAD

**Issue by waderyan** [Microsoft/TypeScript#11012]
_From @fronteed on September 17, 2016 10:16_

- VSCode Version: 1.5.1
- OS Version: OS X El Capitan

Autocomplete for native methods and properties in JavaScript doesn't work inside IIFE (Immediately-Invoked Function Expression).

Steps to Reproduce:

1) Type `document.get` at the top of JS file - you will get 'getElementById` autocomplete suggestion.

![2016-09-17-0dyeh](https://cloud.githubusercontent.com/assets/1612675/18607761/e32f6238-7cde-11e6-9fff-e22aab4e8398.png)

2) Type `document.get` inside IIFE construction - you'll get no autocomplete suggestion for `getElementById`.

```javascript
(function (window, document) {
  document.get| // no autocomplete
})(window, document)
```

![2016-09-17-gtm7q](https://cloud.githubusercontent.com/assets/1612675/18607762/ed55e5a2-7cde-11e6-96bb-d15638ff2d42.png)

This looks like an issue, I hope this will be fixed in the next release.

_Copied from original issue: Microsoft/vscode#12186_

**Comment by waderyan** [comment]
_From @rozzzly on September 17, 2016 15:3_

Offtopic.. but what theme is that lol looks nice.

**Comment by waderyan** [comment]
@fronteed thanks for opening this issue. Moving to TypeScript language service (powers JavaScript auto complete).

**Comment by mhegazy** [comment]
Should be working correctly in latest drop of TypeSript (TS 2.0.2 or later). VSCode ships with an older version of TypeScript. Please see [Using Newer TypeScript Versions](https://code.visualstudio.com/docs/languages/typescript#_using-newer-typescript-versions) documentation for more details on updating your VSCode to use a different version of TypeScript.

**Comment by naxsooley** [comment]
Current issue still exists in VS Code v1.5.3, please check it again.

**Comment by mhegazy** [comment]
> Current issue still exists in VS Code v1.5.3, please check it again.

what version of TS have you been using with VSCode 1.5.3?

**Comment by naxsooley** [comment]
@mhegazy I'm using a built-in one.

**Comment by mhegazy** [comment]
Well. as i noted in https://github.com/Microsoft/TypeScript/issues/11012#issuecomment-248387807

> Should be working correctly in latest drop of TypeSript (TS 2.0.2 or later). VSCode ships with an older version of TypeScript. Please see [Using Newer TypeScript Versions](https://code.visualstudio.com/docs/languages/typescript#_using-newer-typescript-versions) documentation for more details on updating your VSCode to use a different version of TypeScript.
