### ISSUE TITLE
TS2488	Type must have a '[Symbol.iterator]()' method that returns an iterator.	TypeScript Virtual Projects

### ISSUE THREAD

**Issue by stefdelec** [Microsoft/TypeScript#12707]
**ERROR :**
TS2488	Type must have a '[Symbol.iterator]()' method that returns an iterator.	TypeScript Virtual Project
**TypeScript Version:**  2.1 
I am using typescript in a Visual Studio 2015

```
for (var item of this.listOfTemplate) { //error here

        }
```
tsconfig
```
{
  "compileOnSave ": true,
  "compilerOptions": {
    "target": "es6",
    "module": "commonjs",
    "removeComments": true,
    "lib": [ "es5", "dom" ]
  },

  "files": [
    "app.ts"
  ]
}

```

**Comment by mhegazy** [comment]
you are specifying `target: es6` but do not included the needed `es6` built in definitions in the `lib: es6`. 

so either change the target to be `es5`. or add `es6` to your `lib` flag.

**Comment by ricklove** [comment]
I ran into this also and it took forever to find: Hoping this comment will help others find this note.

I was trying to use for ... of with an array while targeting es6 (es2015).

I solved by doing what @mhegazy said, but I just added "es2015.iterable" instead of all of es6.

keywords: typescript array symbol iterator error

**Comment by mikejune** [comment]
I'm trying to use the spread operator in this manner:
```
[PAGE_LAYOUTS_FETCH]: (state, { payload, error }) => {
    return Object.assign({}, state, {
        isFetching: true,
        error,
        results: [...state.results, ...payload]
    });
},
```
error is on the `...payload` part of the code. issue still remains with `"es2015.iterable"` in `tsconfig.json`

**Comment by IAmCoder** [comment]
Make sure the type isn't nullable (have a question mark at the end of the variable name)... that caused this error for me.

**Comment by jshado1** [comment]
This also happens with an interface that fakes a tuple:

```ts
interface foo {
    0: string;
    1: number;
    2?: boolean; // can't have an optional member in a real tuple
}
```

**Comment by ratskin** [comment]
add `!` to the end of the var that is being spread. E.g. `[{}, ...payload!]`

**Comment by slavafomin** [comment]
Hello!

I'm seeing this issue as well.

I have the following interface:

```typescript
export interface TasksList {
  0: ('parallel' | 'sequential');
  [key: number]: string;
}
```

And I'm trying to spread it this way:

```typescript
const [mode, ...taskNames] = tasksList;

// TS2488: Type 'TasksList' must have a '[Symbol.iterator]()'
// method that returns an iterator.
```

All I want is to define a more specific type of the first element of the array.

**Comment by slavafomin** [comment]
I've found a working solution for cases mentioned by me, @jshado1 and @mikejune.

The type should be defined this way:

```typescript
export interface TasksListSpecifics {
    0: ('parallel' | 'sequential');
}

export type TasksList = (string[] & TasksListSpecifics);
```

The trick is to add your more specific properties on top of array of strings type (`string[]`).

I've tested it and it works great, type checking is working correctly everywhere I probably expect it to work.

Here's the [TS Playground][tsp] to test this out.

  [tsp]: http://www.typescriptlang.org/play/?target=2&ssl=1&ssc=1&pln=19&pc=1#code/KYDwDg9gTgLgBASwHY2FAZgQwMbDgFUwGcBrIgGQSJgGUxhsF0Fsi4BvAKDh7gAYAXHAAUAcjCYomADbTg00XAA+cUUWABHAK7AUCGaICUAbk4BfTp1CRYcGAE96BYmUrU4AXhHUoyAOYA2gC6cABkzqQUVLT0jMysJpbYEEjuMC5R1EKEkW7wXgHcvOKSMnIKADSq6BAQolWiAEaSopxBppzJqfABALYQACbAVQB0Y+mkAHKYvcBEIV4TrtEdRADuCDDYABYi-UOGHEU82MR4apo6egYCx7w8jVDAmCSmFp0pRBByI9IQfsIlpkYFV9sM7C5prMiIkgA

**Comment by MrCEO63** [comment]
> add `!` to the end of the var that is being spread. E.g. `[{}, ...payload!]`

```
interface IMethods {
  post: string;
  get: string;
  patch: string;
  put: string;
  delete: string;
}
```
`type PartialRecord<K extends keyof any, T> = Partial<Record<K, T>>;`

```
interface IEndpoint {
  route: string;
  methods: Array<keyof IMethods>;
  middlewares: PartialRecord<keyof IMethods, any[]>;
}
```
`...endpoint.middlewares[method]` -- !works
`...endpoint.middlewares[method]!` --works

Can you please explain what this does, because it helped in my case.

**Comment by chicken-suop** [comment]
@MrCEO63 Did you check https://stackoverflow.com/questions/42273853/in-typescript-what-is-the-exclamation-mark-bang-operator-when-dereferenci?

**Comment by daikiirai** [comment]
> add `!` to the end of the var that is being spread. E.g. `[{}, ...payload!]`

LSDJHFKSJDFKSJD was so easy, i love u
