### ISSUE TITLE
Issue when using yarn link and @types types

### ISSUE THREAD

**Issue by raybooysen** [Microsoft/TypeScript#12860]
**TypeScript Version:**  2.0.3

I have two projects, ProjectA and ProjectB.  Both projects have @types/react installed.  If ProjectA is linked to ProjectB via `yarn link`, ProjectB will start to complain when building:

```
node_modules/@types/react/index.d.ts(7,21): error TS2300: Duplicate identifier 'React'.
node_modules/@types/react/index.d.ts(2449,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'a' must be of type 'HTMLProps<HTMLAnchorElement>', but here has type 'HTMLProps<HTMLAnchorElement>'.
```

Since there is @types/react in both projects, this seems to cause issues.

**Comment by DanielRosenwasser** [comment]
@raybooysen do you run into the same issues if you used `npm link`?

**Comment by longlho** [comment]
This is fixed in TS 2.1 I believe

**Comment by mhegazy** [comment]
@raybooysen can you give it a try with `typescript@2.1.4` or `typescript@next`? if issue still persists please share a sample project we can use or some detailed steps, including versions of the @types packages to be able to reproduce this locally.

**Comment by qballer** [comment]
First link then install.

**Comment by pocesar** [comment]
the problem is the link, tsc seems to be resolving the symlink instead of using it as-is (see #9566 and  #6496)

**Comment by patrikx3** [comment]
same error, dont know what to do
i linked my project with yarn whetever i exclude or delete the linked node_modules, always get an error based on 
```bash
ERROR in [at-loader] ./node_modules/@types/hammerjs/index.d.ts:9:5 
    TS2300: Duplicate identifier 'export='.

ERROR in [at-loader] ./node_modules/@types/hammerjs/index.d.ts:71:6 
    TS2300: Duplicate identifier 'RecognizerTuple'.

```
