### ISSUE TITLE
BaseUrl is not working in jsconfig.json

### ISSUE THREAD

**Issue by olafahn** [Microsoft/TypeScript#12995]
> copied from https://github.com/Microsoft/vscode/issues/9135#issuecomment-266945304, https://github.com/Microsoft/TypeScript/issues/9667#issuecomment-266985852

**TypeScript Version:**  2.1.0 / nightly (2.2.0-dev.201xxxxx)
(vscode version 1.8.0)

Hello, @dbaeumer !
this feature seems not working for me.

i checked my vscode version, (1.7.2) which uses typescript server 2.0.10
and i also tried to use typescript@next for my vscode,
but vscode hint me with underline as Property baseUrl is not allowed.

so i changed jsconfig.json => tsconfig.json,
then add allowJs true at compilerOptions, but still not working.
is there anything else that i'm missing?

(p.s. I really enjoy coding with vscode. Thank you! * 10000)

**Expected behavior:**

intelli sense working properly

**Actual behavior:**

but it is not.

**Comment by aluanhaddad** [comment]
I tried this in 1.9.0-insider with typescript@next and I definitely see the warning for (`jsconfig.json` files only). 
@olafahn 
The good news is that it actually respects the setting in spite of the warning, so you should be able to safely ignore it.

**Comment by DanielRosenwasser** [comment]
@olafahn Given that VS Code is at 1.8 and TypeScript is at 2.1, please try the latest VSCode and let us know if it's still a problem.

**Comment by mhegazy** [comment]
https://github.com/SchemaStore/schemastore/pull/258 removes the warning from schema validation

**Comment by evileagle** [comment]
I also have this issue, my vscode version is 1.8.1 and typescript version is 2.1.4
my folder looks like below:
![image](https://cloud.githubusercontent.com/assets/5699456/21338266/9c2a5daa-c6af-11e6-88b4-91e4a94df527.png),

and my content of jsconfig.json is: 
```
{
    "files": [
        "src/"
    ],
    "compilerOptions": {
        "module": "commonjs",
        "target": "es6",
        "baseUrl": "src",
        "mapRoot": "src",
        "rootDir": "src",
        "sourceRoot": "src"
    }
}
```
I added `root: path.join(path.dirname(__dirname), "src"),` to my webpack config, so I can write `var connect = require("utils/connect.js");` in 

> src\components\workloaddetails\index.js

but the intelli sense can't resolve it.

![image](https://cloud.githubusercontent.com/assets/5699456/21338409/175f12a8-c6b1-11e6-9007-cf5898c5bfd1.png)


but if I write relative path, it works,
![image](https://cloud.githubusercontent.com/assets/5699456/21338382/e0787ad6-c6b0-11e6-8e8a-6b930126ebf2.png)

I really don't want write relative path in my code, how to resolve it?

**Comment by mhegazy** [comment]
can you share your project?

**Comment by nishp1** [comment]
I am seeing with resolving paths and intelli-sense with baseUrl option in jsconfig.json. I have pushed sample project at https://github.com/nishp1/vscode-baseurl.

Expected:
<img width="681" alt="screen shot 2016-12-22 at 11 12 08 am" src="https://cloud.githubusercontent.com/assets/553376/21432054/dae5390a-c837-11e6-8c42-68423e90cb31.png">

Actual:
<img width="685" alt="screen shot 2016-12-22 at 11 12 17 am" src="https://cloud.githubusercontent.com/assets/553376/21432063/e646f5ea-c837-11e6-96f6-c617b6e7531b.png">

**Comment by nishp1** [comment]
Ah, looks like jsconfig needs to be at root of the project and not under ".vscode". I have fixed the sample project and is now working as expected. cc: @olafahn

**Comment by olafahn** [comment]
@nishp1 I'll check after my vacation! THX!

**Comment by olafahn** [comment]
Now i see the baseUrl as proper key value for compilerOptions, (warning disappeared)

but intelliSense still not working...

**Comment by mhegazy** [comment]
@olafahn can you share a project i can look at?

**Comment by nickcox** [comment]
I have the same issue. Intellisense works with relative paths but not relative to baseUrl.

```
Version 1.9.0-insider
Commit 12af9ea6effefeaeecde2107c960ae5222703864
Date 2017-01-09T07:10:36.676Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0
```

[vscode-sample.zip](https://github.com/Microsoft/TypeScript/files/695055/vscode-sample.zip)

**Comment by mhegazy** [comment]
in your jsconfig.json, `files` does not support glob patterns. it does not support directories either. use `include` instead. or just do not specify any thing., and the jsonfig would apply to the whole folder.

**Comment by nickcox** [comment]
Yay, that works, thanks!

**Comment by mhegazy** [comment]
@olafahn, can you confirm that your issue is also caused by an invalid jsconfig file? This seems to be the case for the other reports.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
