### ISSUE TITLE
Spead types may only be created from object types

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/TypeScript#14409]
Version 2.2.1

``` ts
let p = {} as any as object;
const z = { ...p } // works fine
const fn = <T extends object>(t: T) => {
	return { ...t } // Error: Spread types may only be created from object types.
}
```

Should this be erroring?

**Comment by mhegazy** [comment]
Tracked by https://github.com/Microsoft/TypeScript/issues/10727, fixed by https://github.com/Microsoft/TypeScript/pull/13288

**Comment by zheeeng** [comment]
@mhegazy I still get this error on TS online playground and VS Code with TS 2.4.2

**Comment by kitsonk** [comment]
@zheeeng #13288 is not yet merged and #10727 is still open.  Commenting on issues closed as duplicate helps no one.
