### ISSUE TITLE
In Visual Studio 2017, TS2304 errors occur when viewing a JavaScript file

### ISSUE THREAD

**Issue by jimbarrett33** [Microsoft/TypeScript#15055]
**TypeScript Version:**  2.1

**Code**
https://github.com/jimbarrett33/VS2017_Typescript_Test
Although not a full Angular project, it uses the core Angular packages to demonstrate the problem. 

tsconfig.json
```
{
   "compilerOptions": {
      "target": "es5",
      "module": "commonjs",
      "moduleResolution": "node",
      "lib": [ "es2015", "dom" ],
      "emitDecoratorMetadata": true,
      "experimentalDecorators": true,
      "noImplicitAny": true,
      "suppressImplicitAnyIndexErrors": true,
      "sourceMap": true
   },
   "include": [
      "src/**/*"
   ]
}
```

**Summary**
In Visual Studio 2017, TS2304 errors occur when viewing a JavaScript file that is not in the "include" path and with "new JavaScript language service" enabled. Generally I'm trying to get a handle on Visual Studio TS2304 errors appearing and disappearing (which occur frequently for me) and this is the first consistently reproducible project I have been able to create.

Details:
- tsconfig.json uses  "include": [ "src/**/*" ]
- someConfigFile.js is in the VS project but not in the TS project – it is not under src
- when I open someConfigFile.js, the errors appear after about 30 seconds (sometimes longer), and the TypeScript/JavaScript Virtual Project displays as in the below pic
- although not in the test project code, I did try it with "allowJs": true in tsconfig.json and still got errors
- when I disable "new JavaScript language service", the errors go away after closing and re-opening the someConfigFile.js. (but what if I wanted both TS and JS language service?)

**Questions**
Does the JavaScript language service does use tsconfig.json?  If not how do I tell it what files to exclude? In my case I want to exclude them all since all my real source is in TypeScript.

Depending on above answer, why do I have to disable "new JavaScript language service" when the JS file is not in my tsconfig.json include section?

Why do the errors only start happening when I open the JS and after about a 30 second delay?

Why do the errors clear when I close the JS file?

Is there a way to invoke the TS/JS language services on demand instead of whatever time period Visual Studio is using?

Shouldn't "enable the new JavaScript language service" be a project-level option and not a VS-level option?

**Expected behavior:**
No TS2304 errors and/or TS2304 errors to be removed even if file is still open

**Actual behavior:**
TS2304 errors when file is opened and remain until file is closed

![ts2304_errors](https://cloud.githubusercontent.com/assets/8396655/24770634/9fe92e9e-1ad8-11e7-8115-9c2f52ccae18.png)

![ts_projects](https://cloud.githubusercontent.com/assets/8396655/24770660/bc98662c-1ad8-11e7-92bf-efebf841e0af.png)

**Comment by bowdenk7** [comment]
I apologize for the slow response @jimbarrett33. I believe that this issue has been fixed. Can you try downloading the latest [VS 2017 Preview build](https://www.visualstudio.com/vs/preview/)? I can't reproduce this in `15.2 26421.1-Preview`.

**Comment by jimbarrett33** [comment]
@bowdenk7  Thanks that is great news!  And it's OK regarding response time, I'm just glad the TS2304 errors are getting attention from the team. Quick questions before I try since I haven't used preview builds before.

Will the preview work side-by-side with an existing VS 2017 installation or will it overwrite what I have?  If so, is it stable enough to keep using on my dev machine(s)?

Thanks.

**Comment by jimbarrett33** [comment]
@bowdenk7 this problem does seem to be fixed. I verified it in version 15.2 26419.1-Preview which was the latest available version on the VS 2017 Preview site.  Thanks for that.

I do however still have problems with TypeScript files that are "Miscellaneous" files according to the TypeScript Virtual Project. I think you should be able to have TypeScript files in the solution/project that are not included in the build (or that might be later) and be able to edit them. Currently these lead to hundreds of TS2304 errors when they are opened, making it hard do determine real errors. As with the JavaScript files in this issue, the errors all go away when the TS file is closed. If I have time I may create repo to reproduce this but this and open a new issue.

**Comment by billti** [comment]
I assume those loose files are referencing types that they aren't able to resolve though (as they are in Miscellaneous and not part of any project)? What behavior do you suggest - that we don't show type errors in TypeScript files that aren't part of a project? The issue is we always create some type of project content for them, as they may well just /// reference the files they need, and be compiled directly on the command-line (e.g. `tsc file1.ts`).

**Comment by jimbarrett33** [comment]
@billti thanks for getting back. I understand your point. In my case I'm using modules in an Angular 2 app and the app entry point is just a couple files and then the rest gets resolved via node module resolution. 

`
   "files": [
      "src/app/app.module.ts",
      "src/main.ts"
`

Also important is that I have disabled Visual Studio TypeScript build and instead using npm externally so I guess that means I'm only talking about the Language Service here. I imagine this will be a popular configuration given the move to JS modules and bundlers like Webpack. (I have talked to other Angular 2 devs and they left Visual Studio to use VS Code because of the errors. I very much do not want to do that).

A common thing in Angular 2 app is to have a few separate files for an AoT build (main-aot.ts, lib-aot.ts, etc.) and a separate tsconfig-aot.json for them. When I open the AoT files in the project they are **Miscallenous** and most of the errors have to do with not being able to resolve modules in `node_modules @angular/<...>`. In addition, this also happens when starting starting a new TS file or including an existing TS file in the project (I'm converting an AngularJS project to Angular) and it hasn't been imported into `app.module.ts`.

So to answer your question, maybe there could be a `tsconfig.misc.json` (or similar) that the TypeScript Language service uses for  Miscellaneous files. This could be configured by the developer to either include and/or exclude files in order to avoid the errors. For example, `"include": ["src/**/*"]` and `"moduleResolution": "node"` so it could resolve all the types in the project and under node_modules.

I'm not sure about this but it would seem that the language service must use some default (in-memory) tsconfig.json for Miscellaneus files or else how would it know that these are errors in the first place? If that's the case then I'm just asking that this file (optionally) comes from disk instead of memory. I may be way off on this.

Thanks.

**Comment by billti** [comment]
Thanks for the additional details. Part of the problem here I believe is that we don't default to a `moduleResolution: node` settings for miscellaneous files. If we did, it would still resolve the Angular files correctly.

@mhegazy , we still default to `classic` for legacy reasons I believe. Is that really still useful? Is it too big a breaking change to default to `node`?

**Comment by mhegazy** [comment]
Problly not. But it is stilll a breaking change. We can lump that with es5 default target in TS 2.4.

**Comment by jimbarrett33** [comment]
@billti, @mhegazy thanks for the responses.  Yes, `moduleResolution: node` will help but there are other things that cause the errors such as not having `"experimentalDecorators": true` for Angular components, pipes etc. and not finding types under `node_modules\@types`, unless `moduleResolution: node` does that. And if the Miscellaneous files reference other files in the solution, for instance model classes, it finds errors in those files also, most of the "cannot find name/module" variety. 

I see at least two use cases in addition to the use case in my previous comment regarding AoT files. A developer working on an existing project adds a new (or existing) TS file and just wants to start coding, importing modules as necessary from other project files and using types under node_modules\@types, and without getting errors in VS. Later they add it to the app, however it is bootstrapped, say in app.module.ts for Angular. A workaround to the errors here is to always add new files to the app immediately which may not be too much to ask.

Second use case is a common library (coded by the developer) that has a various services, components, pipes, utilities, etc. and are part of the project. However, only a subset of these are added to the app and module resolution / build will automatically exclude the modules not added to the app from the output. In VS however the modules not added to the app currently result in errors. A workaround for this is to add all service, components, etc. to an Angular Module and include it in the app and hope that the TypeScript build and/or tree shaking will get rid of the dead code.

I thought I read something recently about VS Code supporting project level errors. I'd be interested to see how it will be handled there since it seems to work with loose (miscellaneous) files.

**Comment by govis** [comment]
Similar issue here (with internal .ts files): numerous TS2304, TS2503, TS2339, TS2694 complaining about not finding namespaces, members, types, etc are showing upon build in VS2017 even though it builds successfully.

TypeScript Intellisense is not working. The project was originally developed in VS2015 and everything is fine there. Adding <code>///&lt;reference path="..ts" /></code> seems to help, but shouldn't it find .ts files within the project automatically just like VS2015 does?

VS 15.2 (26430.13) with Typescript 2.3.

**Comment by mhegazy** [comment]
Should be fixed in [15.3](https://www.visualstudio.com/en-us/news/releasenotes/vs2017-relnotes). please reopen if you are still running into issues.

**Comment by mzhukovs** [comment]
I'm still having this issue although not 100% sure if it's the same. In my case, if I have a typescript file opened as well as an html file that's in the same directory, then TS spews false errors in VS2017 - any ideas?
[I also filed this here but there hasn't been any movement](https://developercommunity.visualstudio.com/content/problem/206355/typescript-file-treated-as-miscellaneous-if-other.html?childToView=222381#comment-222381 )
