### ISSUE TITLE
VS2017.2 Preview: Inconsistent error on array spread with Uint8Array

### ISSUE THREAD

**Issue by SaschaNaz** [Microsoft/TypeScript#15366]
**TypeScript Version:**  2.2.2 (Visual Studio 2017)

**Code**

```ts
[...Uint8Array.of(1, 2, 3)]
```

**Expected behavior:**

Should work without error

**Actual behavior:**

IntelliSense complains that Uint8Array is not array but build anyway proceeds without error, both with `--target es2017`. `dom.iterable` type is included.

**Comment by SaschaNaz** [comment]
Probably VS2017 specific error, this does not repro on VSCode with TS master branch.

**Comment by mhegazy** [comment]
This should be fixed in latest.

**Comment by SaschaNaz** [comment]
I got TS2.3 on VS2017 15.2 Preview and this still happen. Build still succeeds but IntelliSense doesn't like it.

**Comment by SaschaNaz** [comment]
By some reason I lost the right to reopen my issues, what happened?
