### ISSUE TITLE
ts.createEmitHostFromProgram doesn't bind compilerHost methods to the compilerHost instance

### ISSUE THREAD

**Issue by Arnavion** [Microsoft/TypeScript#1545]
Starting from 5a2fb94, the EmitHost returned from ts.createEmitHostFromProgram() returns functions on the compilerHost like so:

```javascript
        return {
            getCanonicalFileName: compilerHost.getCanonicalFileName,
            getCurrentDirectory: compilerHost.getCurrentDirectory,
            getNewLine: compilerHost.getNewLine,
            writeFile: compilerHost.writeFile,
        };
```

Because of this, the implementations of those functions do not have access to the compilerHost object via `this`.

This doesn't matter for the default WScript and node.js compiler hosts because they use closures to capture their references, but it's a problem for custom compiler hosts that are implemented as classes, and worked before this change.

**Comment by danquirk** [comment]
You're describing a fairly general problem with APIs of this shape are you not? The compiler certainly does this in more places than just this one.

**Comment by Arnavion** [comment]
>You're describing a fairly general problem with APIs of this shape are you not?

Yes, which is why I advocated for the safe path of always passing in a valid this-context and letting the implementation ignore it if it wants to. Unless TS gains a syntax like `interface FooInterface { bar(this: undefined, arg1: string, arg2: number); }` it is not possible for an implementation to know whether their FooImpl.method code can use `this` or not. If such a syntax existed and the compiler disallowed the use of `this` inside FooImpl.method then it'd be fine.

So yes, I consider it a problem that the compiler allows two ways of implementing an interface without type errors, yet one of them fails at runtime because of a reason that the type system does not express.

>The compiler certainly does this in more places than just this one. 

CompilerHost is the one I implement in my compiler wrapper, so I know it broke with the mentioned change. In the PR for this, @DanielRosenwasser suggested to give the Program object the same treatment because users might want to pass in custom Programs not created via ts.createProgram. Atleast for compiling via ts.createProgram() this fix is sufficient. If there are more places that support user implementations of the interfaces but don't pass in a valid this-context to their methods then they need to be fixed too.

**Comment by danquirk** [comment]
Perhaps this is something that should be considered along with the other functionality mentioned in issues like #229 and #285

**Comment by Arnavion** [comment]
Yes, those issues are what I was referring to.

**Comment by basarat** [comment]
I haven't looked at the code, but would this fix it: 

```ts
return {
            getCanonicalFileName: compilerHost.getCanonicalFileName.bind(compilerHost),
            getCurrentDirectory: compilerHost.getCurrentDirectory.bind(compilerHost),
            getNewLine: compilerHost.getNewLine.bind(compilerHost),
            writeFile: compilerHost.writeFile.bind(compilerHost),
        };
```

**Comment by Arnavion** [comment]
@basarat Pretty much, although I prefer it to be explicit rather than use bind, seeing as bind kills typechecking - see #1546

**Comment by Arnavion** [comment]
@mhegazy I think you misunderstood something. This isn't fixed.

**Comment by danquirk** [comment]
Looks like the referenced PR fixed some but not all of these:

```ts
function getEmitHost(writeFileCallback?: WriteFileCallback): EmitHost {
            return {
                getCanonicalFileName: fileName => host.getCanonicalFileName(fileName),
                getCommonSourceDirectory: program.getCommonSourceDirectory,
                getCompilerOptions: program.getCompilerOptions,
                getCurrentDirectory: () => host.getCurrentDirectory(),
                getNewLine: () => host.getNewLine(),
                getSourceFile: program.getSourceFile,
                getSourceFiles: program.getSourceFiles,
                writeFile: writeFileCallback || (
                    (fileName, data, writeByteOrderMark, onError) => host.writeFile(fileName, data, writeByteOrderMark, onError)),
            };
        }
```

**Comment by mhegazy** [comment]
@danquirk which ones are still missing? i see all the `host` references handled correctelly

**Comment by mhegazy** [comment]
I believe this is fixed now after @Arnavion 's last change. @Arnavion can you confirm?

**Comment by Arnavion** [comment]
I'll confirm when I get home tonight.

The reason I didn't fix the `program` ones is in [this comment in the PR.](https://github.com/Microsoft/TypeScript/pull/1546#issuecomment-85612229)
