### ISSUE TITLE
Incorrect tab indentation in some JQuery code

### ISSUE THREAD

**Issue by pkkj** [Microsoft/TypeScript#1580]
If you format the code in Visual Studio, you may see this result:
```
$.ajax({
    type: "POST",
}).done(function (data) {
        var i;
    }).fail(function (jqXHR, textStatus) {
        var j;
    }); 
```
The indentation in "done" and "fail" is too long: there is an extra tab in those lines.

However, if you edit the content inside, "done()", you will see:
```
$.ajax({
    type: "POST",
}).done(function (data) {
    var i;
    i = 1;
    }).fail(function (jqXHR, textStatus) {
        var j;
    }); 
```
It seems to be correct. However, if you press "CTRL K + CTRL F" to format the source code, you will see the extra tab in indentation again.

I am wondering is this by-design, or a small bug in the intellisense?

**Comment by vladima** [comment]
this issue should already be fixed in our latest bits:
```typescript
$.ajax({
    type: "POST",
}).done(function (data) {
    var i;
}).fail(function (jqXHR, textStatus) {
    var j;
}); 
```

**Comment by elkdanger** [comment]
By "latest bits", do you mean in the 1.4 release? I'm still experiencing this issue with 1.4, was just wondering if I would expect to see the fix there.

**Comment by vladima** [comment]
Interesting. This is what I'm seeing in 1.4
![formatting](https://cloud.githubusercontent.com/assets/8052307/5825395/d60c3d32-a09f-11e4-9142-7c078cacd1af.gif)

Can you provide more information about your formatting settings: tab size, if tabs are replaces with spaces etc...?

**Comment by elkdanger** [comment]
On further inspection, the case where I put the chained call on the same line as the thing I'm chaining to, it seems to work. As in `}).done(function() {`

When the call appears on the next line, the formatting doesn't quite work, as in:

```
    })
    .done(function() {
```

In these examples, the correctly formatted version of the code has been done by hand. Pressing Ctrl+K, Ctrl+D breaks it, but it seems to be the stuff inside the function call.

![VS 1](http://i.imgur.com/pzwZD7R.gif)

Example 2:

![VS 2](http://i.imgur.com/6pyjigJ.gif)

I also have code like this:

```
return new http.AjaxClient().post({
    url: serviceUrl
})
    .then((resultHtml: string) => {

    this.toolContainer
        .empty()
        .html(resultHtml);

    this.categoriesLoaded.trigger(this);
});
```
Notice the `.then(` isn't aligned underneath the `}` on the left, which is where I originally typed it before formatting. If I put the call to `.then` on the same line, the formatting does indeed work now.

As for tab options, they are set to "smart indenting", tab size of 4, indent size 4 and it's set to insert spaces.
