### ISSUE TITLE
Indentation formatting nested destructering is incorrect

### ISSUE THREAD

**Issue by jvanoostveen** [Microsoft/TypeScript#16869]
**TypeScript Version:**  2.4.1

**Code**

Provided the following code:
```ts
let a = {
  b: 1,
  c: 2,
  d: {
    e: 'a',
    f: 'b',
    h: 'c'
  }
};

export let test = (
  multi: typeof a,
  line: boolean,
  params: boolean
): boolean => {
  let {
    d: {
      e,
      f,
      h
    }
  } = a;

  return true;
};
```

After formatting, the function will be:
```ts
export let test = (
  multi: typeof a,
  line: boolean,
  params: boolean
): boolean => {
  let {
    d: {
      e,
    f,
    h
    }
  } = a;

  return true;
};
```

The `f` and `h` in the destruct are unidented one position.
When I add a destruct before the `d` (for example `c`), then the formatting is correct.
```
  let {
    c, // <- one before the nested destruct.
    d: {
      e,
      f,
      h
    }
  } = a;
```

Example: https://goo.gl/9JqSRu right click -> Format Code

(original issue was posted here: https://github.com/vvakame/typescript-formatter/issues/105)

**Comment by aluanhaddad** [comment]
This works correctly in nightly

**Comment by jvanoostveen** [comment]
Issue still present in version `2.4.2`. :(

**Comment by mhegazy** [comment]
Should be working correctly in latest drop of TypeScript (TS 2.5.1 or later). VSCode ships with an older version of TypeScript. Please see [Using Newer TypeScript Versions](https://code.visualstudio.com/docs/languages/typescript#_using-newer-typescript-versions) documentation for more details on updating your VSCode to use a different version of TypeScript.

**Comment by jvanoostveen** [comment]
@mhegazy We're running Typescript 2.5.3 now, but the problem still exists...

**Comment by mhegazy** [comment]
here is what i see locally:
![animation](https://user-images.githubusercontent.com/8000722/31640262-3ad38412-b292-11e7-9c9d-899c9e8f5ac2.gif)
