### ISSUE TITLE
Project does not contain document for @types with TS 2.4

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#17131]
From https://github.com/Microsoft/vscode/issues/30463

**TypeScript Version:**  2.4.1

**Code**

1. Download this project and opened it in vscode: https://github.com/Microsoft/vscode/files/1142617/example.zip
1. Open `file1.js` and trigger completions.
1. Then open `broken.js` and try trigger completions

**Bug**
```
Trace  - 10:18:13 AM] Response received: completions (24). Request took 2 ms. Success: false . Message: Error processing request. Project '/dev/null/inferredProject1*' does not contain document '/users/matb/library/caches/typescript/2.4/node_modules/parse5/node_modules/@types/node/index.d.ts'
Error: Project '/dev/null/inferredProject1*' does not contain document '/users/matb/library/caches/typescript/2.4/node_modules/parse5/node_modules/@types/node/index.d.ts'
    at Object.ThrowProjectDoesNotContainDocument (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:75718:23)
    at InferredProject.Project.getScriptInfoForNormalizedPath (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:77238:42)
    at InferredProject.Project.getScriptInfo (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:77243:29)
    at ModuleBuilder.AbstractBuilder.getOrCreateFileInfo (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:76551:51)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:76679:84
    at Object.map (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:1483:29)
    at ModuleBuilder.getReferencedFileInfos (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:76679:31)
    at ModuleBuilder.updateFileReferences (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:76708:42)
    at ModuleBuilder.ensureProjectDependencyGraphUpToDate (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:76693:30)
    at ModuleBuilder.onProjectUpdateGraph (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:76684:22)
```

**Comment by mjbvz** [comment]
This issue has also been reported here: https://github.com/Microsoft/vscode/issues/30425#issuecomment-314572507

As a workaround, try downgrading your TS version to 2.3.4.  [Here are the instructions on that](https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions)

Closing as upstream

**Comment by andy-ms** [comment]
Can reproduce this with just a JS file containing: `require("jsdom")`.
The problem is likely due to the fact that `@types/jsdom` has `parse5` as a dependency, which is not an `@types` package. Somewhere we must have assumed that everything in the typings cache is an `@types` package.

**Comment by mjbvz** [comment]
Thanks for looking into this @andy-ms! 

@rbuckton We're seeing a number of users reporting this in a variety of different cases. Can we please prioritize this for TS 2.4.2

**Comment by andy-ms** [comment]
Talked to @sheetalkamat and it looks like this was fixed by #16539.
Now that #17210 is in there should be nothing blocking me from reproducing this in master, but I can't.

**Comment by rbuckton** [comment]
This does look to have been fixed by #16539. I've merged this into release-2.4.

**Comment by kscott5** [comment]
Yes I review must of the other related threads but this is still an issue for me.

The latest build of VS Code with TypeScript 2.4.1, Express and MongoDB only has partial Intellisense enabled for the modules imported via the .ts file. TypeScript adds Express and MongoDB index.d.ts files to its @types folder there's very little documentation available. If you can image, this reduces my productivity dramatically. Any suggestions on resolving this. My repo is [Rescue Shelter](https://github.com/kscott5/RescueShelter)

Also, is there anyway to include the actual JSDoc located in the node_module folder specifically?

**Comment by andy-ms** [comment]
@kscott5 Can you try this out with the latest version of TypeScript? See the [docs](https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions) for how to set that up.

**Comment by kscott5** [comment]
I will review the document. I did find this post on [Angular University](http://blog.angular-university.io/typescript-2-type-system-how-do-type-definitions-work-in-npm-when-to-use-types-and-why-what-are-compiler-opt-in-types/) blog. It brief explain @type declaration and why the suggest using the noImplicityAny: true flag updated in tsconfig.json, and although it didn't resolve the issue complete it helped.
