### ISSUE TITLE
TSC.EXE and Node TSC order folders differently

### ISSUE THREAD

**Issue by panost** [Microsoft/TypeScript#17225]
It appears that tsc.exe and nodejs tsc differ in the folder ordering.
tsc.exe is ordering folders descending (Z-A), While the nodejs tsc orders folders ascending(A-Z)

**TypeScript Version:**  2.4.1
On the attached project 

[TscOrder.zip](https://github.com/Microsoft/TypeScript/files/1150489/TscOrder.zip)

using the tsc.exe
"C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.4\tsc.exe" --project tsconfig.json  --listFiles
I get as response

    ./c/a.ts
    ./c/b.ts
    ./c/c.ts
    ./b/a.ts
    ./b/b.ts
    ./b/c.ts
    ./a/a.ts
    ./a/b.ts
    ./a/c.ts

while using tsc nodejs version 
tsc --project tsconfig.json  --listFiles
I get this, as response

    ./a/a.ts
    ./a/b.ts
    ./a/c.ts
    ./b/a.ts
    ./b/b.ts
    ./b/c.ts
    ./c/a.ts
    ./c/b.ts
    ./c/c.ts

Both are the same version 2.4.1

**Expected behavior:**
ordering folders ascending (A-Z)

**Actual behavior:**
ordering folders is descending (Z-A)

**Comment by aluanhaddad** [comment]
I see the same behavior. The difference likely stems from that, IIRC, the NodeJS version uses a third party package to perform the globbing.

If your code depends on this behavior you should fix that.

**Comment by panost** [comment]
The NodeJS version works just fine. The TSC.EXE version has the problem. IIRC TSC.EXE is based on Chakra.

I could fix this if
1) I could build a fixed TSC.EXE, but I didn't found anywhere instructions on how I can do that
or
2) I could configure VS 2017 to use the NodeJS version, but again I could find anything how I can do that. Perhaps is not possible.

**Comment by panost** [comment]
Just checked with TSC.EXE version 2.5 RC and the problem remains :(
What makes the files to order normally (ascending), but the directories in descending order is a big mystery.

The last working version of TSC.EXE is 2.1

**Comment by aluanhaddad** [comment]
I still say that any application which depends on this ordering is very questionably designed.

**Comment by panost** [comment]
@aluanhaddad That is probably right. But having from the same source two different outputs, using the same version of the compiler, is more questionable.

I wonder what kind of design will be recommended when I want a file to be placed last, without having a long list of references, that you will need to update each time when a file is added, renamed or split

**Comment by paulvanbrenk** [comment]
Is there an actual difference in behavior when compiling, or just when displaying the list of files?

**Comment by panost** [comment]
Produces different output since it processes files in different order.
(if you have the --out switch, which merges the output to one file)

That has the immediate effect of different errors ie "Class ..something.. used before it's declaration"
and has many side effects, ie initialization functions running in different order, which may not throw a run-time error, but produce different behaviour

**Comment by mhegazy** [comment]
> Is there an actual difference in behavior when compiling, or just when displaying the list of files?

the order of input files is what decides the output order with using `--out` and for checking use before declaration.

**Comment by paulvanbrenk** [comment]
Thanks, for confirming. I think I have a fix, but I'll check with @minestarks to verify my C++ is fine.

**Comment by paulvanbrenk** [comment]
I merged the PR into our internal repo, so this should show in the nightlies soon.

**Comment by panost** [comment]
Just checked with TSC.EXE version 2.6 RC and the problem remains :(

**Comment by paulvanbrenk** [comment]
@panost  source control is hard... my change didn't make it into the release branch. :(
