### ISSUE TITLE
TypeError: Cannot read property 'getMissingFilePaths' of undefined at ConfiguredProject.Project.updateGraphWorker

### ISSUE THREAD

**Issue by aozgaa** [Microsoft/TypeScript#19000]
**TypeScript Version**:
2.5.3-insiders.20170919
**VSCode Version**
1.17.0-insider
**command requested**
getApplicableRefactors
**hit count**
69200
**stack**
```
at ConfiguredProject.Project.updateGraphWorker in tsserver.js (line: 79310, column: 56)
at ConfiguredProject.Project.updateGraph in tsserver.js (line: 79254, column: 39)
at ConfiguredProject.Project.getLanguageService in tsserver.js (line: 78994, column: 26)
at IOSession.Session.getApplicableRefactors in tsserver.js (line: 82616, column: 32)
at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) in tsserver.js (line: 81586, column: 61)
at IOSession.Session.executeWithRequestId in tsserver.js (line: 82790, column: 28)
at IOSession.Session.executeCommand in tsserver.js (line: 82799, column: 33)
at IOSession.Session.onMessage in tsserver.js (line: 82819, column: 35)
at Interface.<anonymous> in tsserver.js (line: 83945, column: 27)
at emitOne in events.js (line: 96, column: 13)
at Interface.emit in events.js (line: 191, column: 7)
at Interface._onLine in readline.js (line: 241, column: 10)
at Interface._normalWrite in readline.js (line: 384, column: 12)
at Socket.ondata in readline.js (line: 101, column: 10)
at emitOne in events.js (line: 96, column: 13)
at Socket.emit in events.js (line: 191, column: 7)
at readableAddChunk in _stream_readable.js (line: 178, column: 18)
at Socket.Readable.push in _stream_readable.js (line: 136, column: 10)
at Pipe.onread in net.js (line: 560, column: 20)
```

**Comment by sheetalkamat** [comment]
@aozgaa  This doesnt seem like something from recent master branch since now updateGraphWorker doesnt directly get the program's missing file paths, instead helper function updateMissingFilePathsWatch gets the missing file paths from program.  Please let me know if this is still being hit with latest master branch ?

**Comment by mhegazy** [comment]
> @aozgaa This doesnt seem like something from recent master branch since now updateGraphWorker doesnt directly get the program's missing file paths, instead helper function updateMissingFilePathsWatch gets the missing file paths from program. Please let me know if this is still being hit with latest master branch ?

these are crash reports we are getting. so if we believe the code has changed enough for this to be invalid, just close it.

**Comment by sheetalkamat** [comment]
Yes i think this is fixed since the code has changed with watchImprovements PR.

**Comment by aozgaa** [comment]
This is still showing up in 2.6.1-insiders20171019 and 2.7.0 (version marker for internal builds). For the insiders build, here is the stack we get:
```
TypeError: Cannot read property 'getMissingFilePaths' of undefined
    at Object.updateMissingFilePathsWatch (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:81770:39)
    at ConfiguredProject.Project.updateGraphWorker (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:83000:24)
    at ConfiguredProject.Project.updateGraph (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:82936:39)
    at ConfiguredProject.updateGraph (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:83227:53)
    at ConfiguredProject.Project.getLanguageService (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:82672:26)
    at IOSession.Session.getApplicableRefactors (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:86450:32)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:85415:61)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:86645:88
    at IOSession.Session.executeWithRequestId (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:86636:28)
    at IOSession.Session.executeCommand (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:86645:33)
    at IOSession.Session.onMessage (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:86665:35)
    at Interface.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:87857:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

**Comment by mhegazy** [comment]
@aozgaa do you see any new hits on 2.6.1?

**Comment by errorx666** [comment]
I'm getting this error in 1.23.0-insider and it seems to be completely breaking most language server features for me.

**Comment by errorx666** [comment]
I tried patching `updateMissingFilePathsWatch` to just return without doing anything.
The error changed to
```
TypeError: Cannot read property 'getTypeChecker' of undefined
    at ConfiguredProject.Project.updateGraph (c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:88313:58)
    at ConfiguredProject.updateGraph (c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:88659:61)
    at IOSession.Session.getProjectInfoWorker (c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:91294:25)
    at IOSession.Session.getProjectInfo (c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:91290:29)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:90837:61)
    at c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:92148:88
    at IOSession.Session.executeWithRequestId (c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:92139:28)
    at IOSession.Session.executeCommand (c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:92148:33)
    at IOSession.Session.onMessage (c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:92168:35)
    at Interface.<anonymous> (c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:93369:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

So, it seems the problem is not actually with `getMissingFilePaths`, but rather with a `null`-valued program parameter.

I'm not sure how/why this is the case.

**Comment by errorx666** [comment]
@sheetalkamat @mhegazy Can this issue be reopened?

**Comment by mhegazy** [comment]
@errorx666 please file a new ticket, give us some context on what version of TS are you using, and share the full tsserver log.

**Comment by errorx666** [comment]
@mhegazy 
I traced the problem to my jsconfig having multiple asterisks in the `paths` section.

This was causing the assert at https://github.com/Microsoft/TypeScript/blob/0ef0b7adea643a4a28cf9ada1476ff5650a1a9f2/src/compiler/core.ts#L3068 to fail.

The comment at https://github.com/Microsoft/TypeScript/blob/0ef0b7adea643a4a28cf9ada1476ff5650a1a9f2/src/compiler/core.ts#L3012 appears to be incorrect.

**Comment by mhegazy** [comment]
can you share a sample input that caused this issue?

**Comment by errorx666** [comment]
@mhegazy 
jsconfig.json:
```js
{
	"compilerOptions": {
		"allowSyntheticDefaultImports": true,
		"baseUrl": ".",
		"experimentalDecorators": true,
		"jsx": "preserve",
		"lib": [ "dom", "dom.iterable", "esnext" ],
		"module": "commonjs",
		"moduleResolution": "node",
		"outDir": "dist",
		"paths": {
			"data/**/*": [ "./src/data/**/*" ],
			"src/**/*": [ "./src/**/*" ],
			"test/**/*": [ "./src/test/**/*" ]
		},
		"rootDir": "src",
		"target": "esnext"
	},
	"exclude": [
		"node_modules"
	]
}
```

**Comment by duki994** [comment]
@mhegazy @errorx666 

I have the same problem with @angular/language-service.
Once tsconfig.json has paths with multiple asteriks chars language server features crash.

I have this problem with TypeScript 2.8.4 and up (2.9.2 has this problem too). It's making many language services unusable in large projects outside of using editors such as VSCode and Atoms which use a bit different intialization for their lang service extensions.
We cannot use this feature in Visual Studio 2017 IDE to provide language service because it crashes.

**Comment by mhegazy** [comment]
Can you share a repro project we can use to investigate?

**Comment by duki994** [comment]
@mhegazy 
I can't share project NDA signed.

But the thing is that @angular/language-service works with TypeScript 2.7.2, but not with 2.8+. 
So I'm now not entirely sure if this is TypeScript issue or Angular team's issue with forgoting to update language service TypeScript peer dependency.

@errorx666 
Try TypeScript 2.7.2 for multiple asteriks patterns. Seems to work with everything I throw at it.
