### ISSUE TITLE
"Debugging Language Service in VS Code" documentation is weird

### ISSUE THREAD

**Issue by davidsk** [Microsoft/TypeScript#19254]
The "Debugging Language Service in VS Code" wiki is vague and sometimes confusing.

>Update your user settings to use your development version of typescript, located in the .../TypeScript/built/local directory. The corresponding setting/path is
>```
>{
>   "typescript.tsdk": "/path/to/repo/TypeScript/built/local"
>}
>```
User settings are stored per folder and it's not clear which folder should be used.  Both typescript and vscode have been downloaded.  There have been no instructions to open either version of code yet.

>Debugging tsserver (server-side)
>...
>2. Update launch.json with an option to attach to the node instance, with sourcemaps from your built/local folder.

Again, which launch.json is being spoken about?
>3. Launch an instance of development vs code, and open a ts file.
>4. Launch an instance of stable vs code.
>5. Attach the stable vs code instance to the development instance.

Wouldn't it be easier to open an instance of code, change the launch.json and then open a .ts file or attach to the other instance?

It would be helpful to list the steps in order and with more detail, perhaps with an example path so that it's clear which instance of code is being opened, which folder said instance is opening (if any) and which files are being edited.

Given that there aren't too many steps, it should be quite reasonable to list all steps for each debugging excercise.

**Comment by DanielRosenwasser** [comment]
I fixed the page up a bit [here](https://github.com/Microsoft/TypeScript-wiki/pull/151) but I'm definitely missing some context on actually debugging. @mhegazy or others will need to help me out here.

**Comment by davidsk** [comment]
Thanks @DanielRosenwasser.  I'm still not sure I understand though.  What's most confusing, for me anyway, is the order of the instructions. The process that I think is being suggested is the following:

1. Download STABLE VSCode
2. Clone Typescript repo
3. Clone DEV VSCode repo
4. Build VSCode
5. Update user settings
6. Open console
7. Set TSS_DEBUG variable OR update the typescript source to expose the port
8. Start DEV VSCode (from same console if setting the TSS_DEBUG variable)
9. Open a folder from within DEV VSCODE
10. Open a Typescript file from within DEV VSCode
11. Start STABLE VSCode
12. Open a folder in the STABLE VSCode (any folder? vscode repo? typescript repo?)
13. Create or update the launch.json file (any folder? vscode repo? typescript repo?)
14. Attach the STABLE VSCode to the DEV VSCode

With regards to the settings pointing to the typescript repo, I think it'd be better to update workspace settings rather than user settings.  Otherwise all projects are going to use the typescript server from source, no?  Personally, I would want to opt in on to 'development' services on a project by project basis, in which case I would strike step 5 and insert a step between  9 and 10 to update the "typescript.tsdk" setting.

Does that look about right? If not, what am I getting wrong?

**Comment by tonyhallett** [comment]
@davidsk did you succeed in debugging your language service ? I agree that the documentation is not clear enough.  Is it really necessary to 'Manually edit extensions/typescript/src/typescriptServiceClient.ts in your development-side VS Code, setting the port to an open one.'  @DanielRosenwasser, @RyanCavanaugh can you provide the exact setup and steps required to debug into the server code, specifically enablePlugin as this is the entrance point to my language service wrapper.  Thanks

**Comment by davidsk** [comment]
@tonyhallet I'm afraid I didn't, no. I was still hoping for a little more clarity on the process.  I am still interested in getting this working however so would appreciate any help anyone can provide.

**Comment by tonyhallett** [comment]
@davidsk Ok, I now have it set up. Can debug the server, depending on where you want your debugging to start you may have to add a debugger statement to the local typescript that have cloned.  If you are only interested in your module then a debugger statement in there will be sufficient.  I will elaborate further in the next couple of days

**Comment by davidsk** [comment]
@tonyhallett Glad to hear you're making progress.

Having decided to look at this again I'm still stuck.  If I'm reading the instructions correctly, I'm supposed to debug typescript using a (dev) instance of vscode and then debug _that_ with (stable) vscode.  Where I get confused is how to debug the (dev) vscode.  On one hand I'm supposed to [start it from a shell (to set the debug port)](https://github.com/Microsoft/TypeScript/wiki/Debugging-Language-Service-in-VS-Code#debugging-tsserver-server-side) and at the same time, [launch vscode from the launch dropdown in the Debug viewlet](https://github.com/Microsoft/vscode/wiki/How-to-Contribute#using-vscode).

**Comment by tonyhallett** [comment]
@davidsk this is what worked for me.

a) Add the TSS_DEBUG variable 

I have windows so used the Control Panel/System and Security/System - Advanced System Settings / Environment Variables. I added to user variables. I chose  port **9222**
( There is the variable TSS_LOG - of course not as useful when things are not working )

b) Clone vscode and build it

c) _Optionally_ if you want to debug the language server code
Clone typescript
Open instance of the built cloned vscode.  **I have been clicking ion the vscode/scripts/code.bat  ( windows )**
Add below to user settings to the typescript/built/local directory - for me
"typescript.tsdk":"C:\\Users\\me\\Source\\Repos\\Typescript\\built\\local
( it is tsserver.js in this directory that you will add breakpoints too ( there are source maps too )

We always debug in the regular/stable vscode, so what is opened in it depends on what we want to debug, as does the launch configuration in launch,json that we will use.
1) Debugging the typescript client ( the extension ) - we have open the cloned vscode folder.  We will use the "Attach To Extension Host" configuration that should already be present.

2) Debugging the typescript server - we have open the cloned typescript folder - we need to add the launch configuration below
{
            "name": "Attach to TS Server",
            "type": "node",
            "request": "launch",
            "protocol": "inspector",
            "port": _**9222,**_
            "sourceMaps": true,
            "outFiles": ["./built/local"],
            "stopOnEntry": true,
            "runtimeArgs": [
                "--inspect-brk=**5999**" //an open port
            ]
        }
3) Debugging your own typescript language service wrapper - have that folder open.  The launch configuration is the same as above aside from outFiles which depends upon your project build.  ( mine is "./lib"

How do you get the debugger to stop where you want it ?
1) Just add a breakpoint in any typescript file in the extension
e.g extensions/typescript/src/extension.ts activate method
2) Add breakpoint in built/local/tsserver.js
e.g Session.prototype.getCodeFixes

_Note that you miss the first call. **If you want to debug tssserver from the start build typescript with a debugger statement where you want to break.  e.g ioSession.listen()_**
3) Add breakpoint in typescript file
e.g in your wrapper methods

_Note that like above the first call will not be hit.  More importantly if you need to debug code that runs when the module is required then add a debugger statement.  You may want to do so in init or create._

We debug against the developer version ( the one that you have cloned and built). What we open in it:

1) Any project which has a typescript file ( opening typescript file loads the extension and starts the server on the port set in the environment variable you have set )
2) Any project that has a typescript file - with the user settings configured as described
3) A specific project with typescript file - with the user settings configured as described and with the tsconfig having the compilerOptions plugin key set appropriately to the language service wrapper that you want to debug.

Steps for debugging:
(Ensure your developer vscode does not start with typescript file open )

1) Debugging typescript client
a) Open regular vscode on the vscode folder
b) Open developer vscode e.g using code.bat on any project with a typescript file
c) Attach to extension host from regular vscode
d) Open typescript file in the developer vscode

2) Debugging the language server code
a) Open regular vscode on the typescript folder
b) Open developer vscode on any project with a typescript file
c) Attach to TS Server from regular vscode
d) Open typescript file in the developer vscode

3) Debugging own language service wrapper
a) Open regular vscode on your language service wrapper folder
b) Open developer vscode on any project that requires this language service wrapper through the tsconfig plugins key
c) Attach to TS Server from regular vscode
d) Open typescript file in the developer vscode.

I hope this helps !

**Comment by davidsk** [comment]
Ok, I got it working but to do so I had to:

1. Open regular vscode on the typescript folder
2. Open developer vscode on any project with a typescript file
3. Open typescript file in the developer vscode
4. Attach to TS Server from regular vscode

For that to work, I had to change the debug config to "attach" rather than "launch".  I also made the port value the same as the port specified in the runtimeArgs but I don't know whether that was necessary.

All that said, the instructions are still 'weird' and the issue is still open.  I may raise a pull request with, IMHO, clearer steps, at least for language server debugging.

**Comment by WalterWoshid** [comment]
That is still too complicated. Not getting it to work

**Comment by WalterWoshid** [comment]
I resolved the debugging issue by following this guide https://github.com/hediet/easy-attach and then just restarting the TS server
