### ISSUE TITLE
Duplicate auto import suggestions returned for @angular/material

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#19922]
From https://github.com/Microsoft/vscode/issues/37930

**TypeScript Version:**  2.6.1

**Reop**
In a new folder:

1.  run `$ npm init -y` and `npm install @angular/material`
2. Create a empty `jsconfig.json`
3. In a new js file, try triggering suggestions

**Bug:**
Notice that there are multiple, duplicate entries for items such as `MatAccordion`:

<img width="543" alt="screen shot 2017-11-10 at 11 51 42 am" src="https://user-images.githubusercontent.com/12821956/32675949-8e35d356-c60d-11e7-8b12-26df07cbda05.png">

I confirmed that these duplicate entries are being returned by the TS server

**Comment by mjbvz** [comment]
I suspect this may have something to do with how `@angular/material` re-exports symbols

**Comment by mhegazy** [comment]
seems like a duplicate of https://github.com/Microsoft/TypeScript/issues/19694 and https://github.com/Microsoft/TypeScript/issues/19889

**Comment by mhegazy** [comment]
Fixed by https://github.com/Microsoft/TypeScript/pull/20049

**Comment by mjbvz** [comment]
Confirmed this seems to be fixed in TS@next:

<img width="628" alt="screen shot 2017-12-08 at 3 36 47 pm" src="https://user-images.githubusercontent.com/12821956/33789497-a82df8d4-dc2d-11e7-905b-9b0670b2fb34.png">

**Comment by jtsom** [comment]
Problem still exists, and worse, in 2.7dev:

![ts270dev](https://user-images.githubusercontent.com/13488/33895744-2ec3471a-df2f-11e7-9e5a-cc93728dc696.PNG)

**Comment by mhegazy** [comment]
@jtsom mind logging a new issue and giving us more context.
