### ISSUE TITLE
{ [key in keyof typeof Enum]: any } is not index signature

### ISSUE THREAD

**Issue by CzBuCHi** [Microsoft/TypeScript#20011]
**TypeScript Version:**  2.4.1

**Code**
```ts
enum Name {
  Fred, Vilma
}
type Names = keyof typeof Name; // type Names = "Fred" | "Vilma";
type Data = ...;

const data: { [name in Names]: Data } = {
  Fred: { ... },
  Vilma: { ... },
}

function getData(name: Names) {
  return data[strName]; // error here
}

```

**Expected behavior:**
No error
**Actual behavior:**
Compilation error message:
`Element implicitly has an 'any' type because type '{ readonly Fred: Data; readonly Vilma: Data; ...' has no index signature.`

can be fixed by casting data to `any` or to `{ [name: string]: Data }` before using indexer

**Comment by mhegazy** [comment]
Should be fixed in TS 2.6 ([playground link](http://www.typescriptlang.org/play/index.html#src=enum%20Name%20%7B%0D%0A%20%20%20%20Fred%2C%20Vilma%0D%0A%7D%0D%0A%0D%0Atype%20Names%20%3D%20keyof%20typeof%20Name%3B%20%2F%2F%20type%20Names%20%3D%20%22Fred%22%20%7C%20%22Vilma%22%3B%0D%0Atype%20Data%20%3D%20%7B%7D%3B%0D%0A%0D%0Aconst%20data%3A%20%7B%5Bname%20in%20Names%5D%3A%20Data%20%7D%20%3D%20%7B%0D%0A%20%20%20%20Fred%3A%20%7B%7D%2C%0D%0A%20%20%20%20Vilma%3A%20%7B%7D%2C%0D%0A%7D%0D%0A%0D%0Afunction%20getData(name%3A%20Names)%20%7B%0D%0A%20%20%20%20return%20data%5Bname%5D%3B%20%2F%2F%20no%20error%20in%20TS%202.6%0D%0A%7D%0D%0A%0D%0A)).

**Comment by CzBuCHi** [comment]
wow that was fast ... nes time i will try update ts first 👍

**Comment by CzBuCHi** [comment]
updated to 2.6.1 and error still persist. This is my real code:

```ts
enum State {
  Fail, Inconclusive, Running, Success,
}
type StateKeys = keyof typeof State;
type States = {
  [state in StateKeys]: string[]
};
const test: States = getStatesSomehow();
const state = State.Fail;

// Element implicitly has an 'any' type because type 'States' has no index signature.
test[state].push('something');
~~~~~~~~~~~
```

**Comment by mhegazy** [comment]
> ``ts
> const state = State.Fail;
>```

`state` is a number, but `test` has keys that are strings.. did you mean to use string enums?

**Comment by CzBuCHi** [comment]
yea .... silly me :) ... btw: could be that error message tweaked little - basically print your response?

**Comment by mhegazy** [comment]
> btw: could be that error message tweaked little - basically print your response?

if you want to take a stab at making the error better and send us a PR, would be happy to review it.

**Comment by chriszrc** [comment]
How would one use this type of key, but then use the enum value instead? As in :

```javascript
enum Name {
  Fred = "fred",
  Vilma = "vilma"
}

...

test["fred"].push('something');

```

**Comment by CzBuCHi** [comment]
@chriszrc  i would use it this way:

```ts
test[Name.Fred].push('something');
```
