### ISSUE TITLE
Object literal with variable property is overly generic

### ISSUE THREAD

**Issue by xealot** [Microsoft/TypeScript#21030]
**Code**

```ts
interface BV {
    A: string,
    B: number,
}

type BVTemplate<K extends keyof BV> = {
    [P in K]?: BV[P];
}

abstract class BaseBlock<T extends keyof BV> {
    abstract readonly typeName: T;
    value: BVTemplate<T>;

    update(v: BV[T]) {
        const updated: BVTemplate<T> = {
            [this.typeName]: v,
        }
        // const updated: BVTemplate<T> = {};
        // updated[this.typeName] = v;

        this.value = updated;
    }
}
```

**Expected behavior:**

`typeName` is `T`, but the type is incompatible with BVTemplate because the object literal declaration stores it as `string`. `string` is not compatible to `T`.

**Actual behavior:**

I would hope this example could work. The commented string works perfectly, and in JS land those two things should be equivalent.

**Comment by sylvanaar** [comment]
The computed property doesn't take the union type - so it is widened to string.

Simplified Example

```
const a = {} as "FOO" | "BAR";

const o = {
    [a]: true
};

// type of o is {  [x: string]: boolean; }
```

**Comment by mhegazy** [comment]
Should be addressed by https://github.com/Microsoft/TypeScript/pull/21070

**Comment by sandersn** [comment]
After some discussion with @mhegazy, we decided that this issue is a job for the proposed Unionize type. It is not fixed by #21070 in any case.

**Comment by mhegazy** [comment]
here is the sample using the unionize type:
````ts
abstract class BaseBlock<T extends keyof BV> {
abstract readonly typeName: T;
value!: BVTemplate<T>;

update(v: BV[T]) {
   type union = {[P in T]: {[Q in P]: typeof v } }[T];

   const updated: BVTemplate<T> = <union>{
      [this.typeName]: v,
   };
   this.value = updated;
}
} 
```ts

**Comment by mhegazy** [comment]
more discussion in https://github.com/Microsoft/TypeScript/issues/18155
