### ISSUE TITLE
Intellisense on global prototype overrides

### ISSUE THREAD

**Issue by olmobrutall** [Microsoft/TypeScript#22737]
Hi TS Team, 

Both in VS Code and Visual Studio 2017, since the latest version of Typescript (2.7.2) we're not getting IntelliSense for methods that override prototypes of standard classes (Array, string, Promise).

Here is an example of the d.ts file that we use to override this classes:  https://github.com/signumsoftware/framework/blob/master/Signum.React/Scripts/Globals.d.ts

The methods are not shown anymore in the auto-completion list after '.' or Ctrl+Space:

![image](https://user-images.githubusercontent.com/720953/37684168-7620d714-2c8f-11e8-93eb-ec35296a145f.png)

But the code compiles just OK and, once blindly written, parameter information works: 
![image](https://user-images.githubusercontent.com/720953/37684195-8e8eaf1a-2c8f-11e8-9456-21cfc1716be1.png)

Adding an explicit `/// <reference path="..."/>` doesn't seem to have any effect. 

Thanks in advance and keep the good work 👍

**Comment by andy-ms** [comment]
Could you test with `typescript@next`?

**Comment by olmobrutall** [comment]
Hi @andy-ms, I don't know how to install typescript@next language service in VS 2017, but I've tried with 2.8 RC and the same problem happen for promise: 

![image](https://user-images.githubusercontent.com/720953/37707867-e9d573e8-2d04-11e8-989f-04fee79ce907.png)

It's strange, but for Array works. 
![image](https://user-images.githubusercontent.com/720953/37707896-ff835386-2d04-11e8-88e8-165b560756a5.png)

Also works for String:
![image](https://user-images.githubusercontent.com/720953/37707936-276e0b84-2d05-11e8-91e4-96c17234ac74.png)

**Comment by mhegazy** [comment]
looks fixed in latest 
![image](https://user-images.githubusercontent.com/8000722/38276933-8a189588-374b-11e8-8a45-b410c78dc4a1.png)

**Comment by olmobrutall** [comment]
Hi again, 

I think this problem is back in Typescript 2.9. At least in VS2017 (Version 15.7.3)

* Extensions on `string` work ok. 
* Extensions on  `Promise` do not appear in auto-completion. 
* Extensions on `Array` work only on literals (`[]`) but not on general expressions. 

Regards.

**Comment by andy-ms** [comment]
@olmobrutall Could you provide an example that shows how you're extending the prototypes?
