### ISSUE TITLE
Duplicate definitions returned for go to definition 

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#24861]
https://github.com/Microsoft/vscode/issues/51489

**TypeScript Version:**  3.0.0-dev.20180608

**Search Terms:** 
- Go to definition

**Code**

```ts
export const _ = 1;

const f = x => console.log(x)
f()
```

Run `go to definition` on `f`

**Expected behavior:**
One definition entry returned

**Actual behavior:**
Two definition entries returned:

```
[Trace  - 8:58:30 AM] Response received: definition (207). Request took 1 ms. Success: true 
Result: [
    {
        "file": "/Users/matb/projects/san/App.js",
        "start": {
            "line": 3,
            "offset": 7
        },
        "end": {
            "line": 3,
            "offset": 8
        }
    },
    {
        "file": "/Users/matb/projects/san/App.js",
        "start": {
            "line": 3,
            "offset": 11
        },
        "end": {
            "line": 3,
            "offset": 30
        }
    }
]
```

**Playground Link:**  

**Related Issues:**

**Comment by benevbright** [comment]
any workaround for vs code?

**Comment by andy-ms** [comment]
@benevbright The issue should be fixed now, so you should only need to install `typescript@next` and [set up](https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions) vscode to use it.

**Comment by dontsave** [comment]
I am still seeing this issue in vscode with ts ver 3.0.1 on react styled-components:

export const SC = styled.div``;

<SC/> <--- go to definition in vscode here still returns 2 definitions: the above constructor and the @types/react Component constructor

**Comment by andy-ms** [comment]
@dontsave Could you provide the full source? What is `styled` imported from? The npm "styled" package doesn't provide its own types and isn't on DefinitelyTyped.

**Comment by dontsave** [comment]
@andy-ms sure! styled is from styled-components which is one of the most popular css in js libraries. 

```
import * as React from 'react';
import styled from "styled-components";

const RedDiv = styled.div`
	color:red;
`;

const myDiv = <RedDiv/> //<--go to definition here returns 2 results

```

**Comment by andy-ms** [comment]
@dontsave Sorry for forgetting about this, fix is at #26715

**Comment by lishine** [comment]
Have this issue right now version 1.30.1
![image](https://user-images.githubusercontent.com/6741645/50602833-877aa080-0ede-11e9-9810-4d64015aa683.png)

**Comment by Drumstix42** [comment]
I know this is the TypeScript repo... But when using vanilla JS with JSDOC `@enum`, I'm seeing in VSCode that an object's intellisense will have "2 definitions" that both point to the same line. Considering VS is using internal Type logic to power intellisense, does anyone know if this is a bug on VSCode or TypeScript's end?

![image](https://user-images.githubusercontent.com/2993354/119968211-31a96600-bf7b-11eb-848a-72095bea88df.png)
![image](https://user-images.githubusercontent.com/2993354/119968249-3b32ce00-bf7b-11eb-8626-f03c8d59be8b.png)
