### ISSUE TITLE
String type autocomplete doesn't work with paren

### ISSUE THREAD

**Issue by Kingwl** [microsoft/TypeScript#26141]
**TypeScript Version:**  3.1.0-dev.201xxxxx

**Search Terms:**
completion, paren
**Code**

```ts
type A = 'AAAAA' | 'BBBBBB';
type B<T extends A> = {};
type C = B<('/**/')>
```

**Expected behavior:**
`'AAAAA'` or `'BBBBBB'`

**Actual behavior:**
no completions

**Related Issues:** 
#25839 

completion cannot walkup useless node (paren type)

**Comment by DanielRosenwasser** [comment]
Hmm - well if it's not, you were looking for more complex issues. 😄

**Comment by ILikePizza555** [comment]
Hey there, I was browsing the issue list and noticed that this one had been fixed by PR #26140 
I figured that the people here might want to know so that this issue can be closed.

**Comment by jtbandes** [comment]
Bump! @weswigham should this one be closed too?

**Comment by weswigham** [comment]
Doesn't seem fixed to me. I still get generic "text in file" completions instead of string literal in the 3.9 beta playground.

**Comment by DanielRosenwasser** [comment]
Thanks @a-tarasyuk
