### ISSUE TITLE
[Project References] references-full returning definition in mapped .d.ts file

### ISSUE THREAD

**Issue by amcasey** [Microsoft/TypeScript#26175]
Setup: Function F declared in Project1, consumed in Project2.
Repro: Request `references-full` for the occurrence in Project 2.
Response (with unrelated properties pruned):
```json
{
  "seq": 0,
  "type": "response",
  "command": "references-full",
  "request_seq": 51,
  "success": true,
  "body": [
    {
      "definition": {
        "fileName": "C:/Users/amcasey/source/repos/NodeJsProjRef/NodeJsProjRef/bin/proj2.d.ts",
        "name": "function NS18.stuff(): void",
        "textSpan": {
          "start": 39,
          "length": 5
        }
      },
      "references": [
        {
          "fileName": "C:/Users/amcasey/source/repos/NodeJsProjRef/NodeJsProjRef/proj2/file2.ts",
          "textSpan": {
            "start": 45,
            "length": 5
          }
        }
      ]
    },
    {
      "definition": {
        "fileName": "C:/Users/amcasey/source/repos/NodeJsProjRef/NodeJsProjRef/proj1/file1.ts",
        "name": "function NS18.stuff(): void",
        "textSpan": {
          "start": 35,
          "length": 5
        }
      },
      "references": [
        {
          "fileName": "C:/Users/amcasey/source/repos/NodeJsProjRef/NodeJsProjRef/proj1/file1.ts",
          "textSpan": {
            "start": 35,
            "length": 5
          }
        }
      ]
    }
  ]
}
```

**Comment by sheetalkamat** [comment]
I think this is fixed by #26173

**Comment by amcasey** [comment]
Still seeing it in fce3d9f34d93d0472149d98be4859f50d4def6fc.
