### ISSUE TITLE
tsserver uses 100% CPU after installing deps with `yarn add`, and disabling the suggestions dropdown in VS Code

### ISSUE THREAD

**Issue by garyking** [Microsoft/TypeScript#26651]
**TypeScript Version:**  3.1.0-dev.20180823

**Search Terms:** 'cpu npm', 'cpu yarn'

In an NPM project in VS Code, when I install a large package like `yarn add parcel`, then the suggestions dropdown does not appear, which lasts from a few seconds to a few minutes, because the `Code Helper` process goes to 100% CPU. In Process Explorer, `electron_node electronForkStart.js tsserver.js` is using 100% CPU, as seen in the screenshot at the bottom of this post. This therefore seems to point to TypeScript as the culprit. It is [this pull request](https://github.com/Microsoft/TypeScript/pull/23039) that introduced this bug.

This bug has existed in VS Code since June 6, 2018. I built VS Code from source, testing several commits, and different versions of TypeScript, and have come to the following conclusions.

# Relevant versions

- VS Code
    - The bug does NOT exist in `1.23.1` (May 10, 2018). 
    - It first appears in `1.24.0` (June 6, 2018).
    - It exists in the Insiders build released on August 23, 2018 (today).
- TypeScript
    - The bug does NOT appear in `2.8.3`, and `2.9.0-dev.20180331` (March 31, 2018).
    - The bug first appears in `2.9.0-dev.20180401` (April 1, 2018).
    - The bug still exists in `3.1.0-dev.20180823`, released on August 23, 2018 (today).

# Relevant commits

- The commit that introduced this bug to VS Code was [bf99321408066051070a8ac5027be009aca99b41](https://github.com/Microsoft/vscode/commit/bf99321408066051070a8ac5027be009aca99b41).
    - First introduced to VS Code in version `1.24.0`.
    - The relevant change was the upgrade of TypeScript, from `2.8.3` to `2.9.0-insiders.20180503`.
- The commit that introduced this bug to TypeScript was [b3829523b2b2928b15237206e171a5465dc2211b](https://github.com/Microsoft/TypeScript/commit/b3829523b2b2928b15237206e171a5465dc2211b), which references [this pull request](https://github.com/Microsoft/TypeScript/pull/23039).

# Steps to reproduce

- Use the latest stable version of VS Code. 
- In a test directory, run `yarn init -y && touch app.js && code .`. 
- Run `yarn add parcel`. 
    - After it's installed, Code Helper will be at 100% CPU for a few seconds to a few minutes. 
    - During this time, the suggestions dropdown does not appear. You can test this by editing the `app.js` file and typing a few letters; the suggestions dropdown will not appear, for completing snippets, etc.
    - If the problem does not occur, then continue installing (large) NPM packages, like `webpack`, `typescript`, `nodegit`, until it happens. 
        - It is also reproducible if you have an existing project with lots of deps, and then you install another dep.
- TypeScript is perhaps crawling the new files, and therefore slowing down on the particularly large packages?

Please advise me on what I can do to help, if you need more info.

**Process Explorer screenshot from VS Code:**

![vs code - process explorer screenshot](https://user-images.githubusercontent.com/343940/44562219-911d1c00-a726-11e8-8594-37e4eb05459e.png)

**Comment by sheetalkamat** [comment]
This seems to not repro with typescript@next. Can you please give it a try. If it still repros, please share tsserver log by 
1. With "typescript.tsserver.log": "verbose" enabled
2. Restart vscode or vscode insiders
3. Reproduce the problem
4. Run ```code --upload-logs``` on the command line (or ```code-insiders --upload-logs``` if using vscode insiders) and follow instructions
5. Share the log file ID

If possible also share your project which might be a special case that's causing this. I created just blank app.js and added few variable initializations.

**Comment by garyking** [comment]
It seems to be fixed in Insiders. 

Any idea as to what change fixed this? I assume it must've been a change to either VSC or TS (probably the latter) that was made since I made my post.

**Comment by sheetalkamat** [comment]
I am not sure if the issue was reproed earlier since I investigated this yesterday and seems to be not repro on master, I didn't look into earlier drops.

Closing this issue since it seems to work. Please reopen if you run into it again. Thanks.

**Comment by sheetalkamat** [comment]
Closing this since haven't heard back about this yet. Can reopen when we have more data.

**Comment by npesa92** [comment]
I am having severe CPU spiking issues from tsserver.js in VSCode right now. I have uploaded my logs, here is the ID: 2956520534. As I am developing any code change will take around 10-15 seconds to reflect on the UI and during this time Code Helper is spiking 100+% CPU in the activity monitor, and electron_node tsserver.js is showing 100% CPU usage in the Process Explorer. I have viewed various issues created and do not seem to show a resolution. 

Node: v10.13.0
TS: 3.1.6 (Have tried with 3.0.3 also and same issues)
VSCode: 1.29.0

Please let me know if you need anymore information from me. This is making it impossible to develop as all of Typescript is getting choked by something here. Thank you in advance.

**Comment by sheetalkamat** [comment]
@npesa92 Looking at the logs it seems like it is fixed with #28209 which isn't part of 3.1.6 
Can you please try with typescript@next to see if you are seeing this issue?

**Comment by npesa92** [comment]
@sheetalkamat Still having the same issue after upgrading to typescript@next. Should I do this globally on my machine? I have only tested as of now locally using the package.json of the specific package and telling the workspace to use the local version instead of the global version.

**Comment by felixfbecker** [comment]
`typescript@next` seems to have fixed this for me

**Comment by felixfbecker** [comment]
Here's a log file (loglevel verbose) in case it helps

[tsserver.log](https://github.com/Microsoft/TypeScript/files/2581419/tsserver.log)

Could this be reopened, or should I open a new issue?

**Comment by sheetalkamat** [comment]
Yes please create a separate issue and provide full logs. The logs you have shared doesn't contain information when you actually run yarn (since there are no watchers being triggered)

**Comment by npesa92** [comment]
Did this new issue ever get created?

**Comment by felixfbecker** [comment]
Not yet, I tried collecting a log with information mixed in about when exactly yarn was run but it’s non-trivial and doesn’t reproduce every time

**Comment by sheetalkamat** [comment]
@npesa92 you can create separate issue to track problem you are facing. Please give full information on how to repro the issue, source code if possible and tsserver log when you see the issue 
using [typescript nightly drop](https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Nightly%20Builds.md#visual-studio-code).

You can upload logs using 
1. With "typescript.tsserver.log": "verbose" enabled
2. Restart vscode or vscode insiders
3. Reproduce the problem
4. Run ```code --upload-logs``` on the command line (or ```code-insiders --upload-logs``` if using vscode insiders) and follow instructions
5. Share the log file ID

**Comment by npesa92** [comment]
@sheetalkamat Will do, thank you for the information. Will get the issue created as soon as I can.
