### ISSUE TITLE
Find all references doesn't work for composite projects

### ISSUE THREAD

**Issue by asvetliakov** [microsoft/TypeScript#27266]
**TypeScript Version:**  3.1.0-dev.20180921

**Search Terms:**
Project references
Composite projects
Find all references for composite projects

**Repro**
1. Clone repository
https://github.com/asvetliakov/typescript-composite-findreferences
2. yarn && yarn run build
3. Open ```packages/pkg1/src/a.ts``` and ```packages/pkg2/src/c.ts``` (to load both projects into the ts server)
3. Try to find all references for ```export const a``` in file ```packages/pkg1/src/a.ts``` 

**Expected behavior:**
Displays references to ```a``` in ```packages/pkg2/src/c.ts``` file from ```pkg2``` project

**Actual behavior:**
Nothing

**Playground Link:** 

**Related Issues:**

**Comment by dinofx** [comment]
This is very frustrating, and it affects much more than just "Find all references".  Refactor rename fails to update those references that wouldn't have been found.

The behavior is actually non-deterministic.  If you open `c.ts` and then close it, then the reference will probably be found.
I tried turning on `"typescript.tsserver.experimental.enableProjectDiagnostics": true`, to see if that would force the tsdk to discover all files before searching/refactoring, but that features doesn't seem to work in 4.0.3.  For example, renaming the export in `a.ts` does not find the compile error in `c.ts`.

**Comment by sheetalkamat** [comment]
This is fixed
![findAllRef](https://user-images.githubusercontent.com/8052792/97035080-a9fa0580-151a-11eb-885c-9918cbf9fa33.gif)

**Comment by dinofx** [comment]
@sheetalkamat That's awesome!  So will the fix be in 4.1?
(I could still reproduce with TS 4.0.3)

**Comment by dinofx** [comment]
FYI, I just installed the 4.1-beta, restarted VSCode, and I can still reproduce.  To reproduce the problem, you have to avoid ever opening `c.ts`.
<img width="818" alt="image" src="https://user-images.githubusercontent.com/7581987/97049002-f3614980-1548-11eb-86b2-6bdb324f5b57.png">

**Comment by dinofx** [comment]
I confirmed that this is working if the main tsconfig file for the whole "workspace" is named `tsconfig.json`.  Changing the name seems to break things.  Also, you don't even need to build things for this to work.

It would be nice to document how typescript discovers the workspace config that pkg-1 is part of, which I'm guessing is why pkg-2 is then found.  It seems like it is walking up the folder hierarchy and looking for potential other files called `tsconfig.json`.

Alternatively, would it make sense for VSCode to prime the TS server by finding all of the leaf tsconfig.json files in its workspace?

**Comment by sheetalkamat** [comment]
This is intended. tsserver only detects for file named tsconfig.json as in ancestor directory.
