### ISSUE TITLE
Intellisense - Import suggestions show up but are not inserted/loaded?

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#27636]
_From @Alexand3r on October 9, 2018 13:3_

As the title, when I try to "auto import" a component in a React Project , intellisense shows the suggestion, but on selecting it, it is not inserted

- VSCode Version: 1.28.0
- OS Version: Kubuntu 18.04

Steps to Reproduce:

1.Type in render function any React Component from any package ( my case from @material-ui/core the component TableHead, however it is not limited to this )
2. Press ctrl+space for Intellisense suggestion
3. Select Suggestion TableHead (tried with both mouse and keyboard arrows, same result)
4. Nothing happens, the small window for details doesn't show, however the suggestion is there.

Small note: This has been happening since ~ 1.20, however the imports would be imported at one point after some loading time, was blaming the huge number of node modules and the heavy usage of the machine. However with 1.28, it's dead.

Does this issue occur when all extensions are disabled?: Yes
Edit: This also happens in Visual Studio Code Insiders 1.29 version

I've set the typescript.tsserver.trace to verbose and got this :
_the ****** are to hide the project_

```

[Trace  - 2:46:03 PM] Sending request: completionEntryDetails (26). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "/home/andrei/Desktop/Work/*********/src/views/Collections/CollectionCards/CollectionDevices.js",
    "line": 18,
    "offset": 18,
    "entryNames": [
        {
            "name": "TableCell",
            "source": "/home/andrei/Desktop/Work/*********/node_modules/@material-ui/core/TableCell/TableCell"
        }
    ]
}
[Trace  - 2:46:03 PM] Response received: completionEntryDetails (26). Request took 91 ms. Success: false . Message: Error processing request. Debug Failure. Unknown entity name kind.
Error: Debug Failure. Unknown entity name kind.
    at resolveEntityName (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:32169:32)
    at getTargetOfExportAssignment (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:31995:29)
    at getTargetOfAliasDeclaration (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:32017:28)
    at Object.getImmediateAliasedSymbol (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:30419:45)
    at getDefaultExportInfoWorker (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:108189:39)
    at getDefaultLikeExportInfo (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:108171:24)
    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:107968:35
    at forEachExternalModule (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:108311:21)
    at getAllReExportingModules (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:107963:13)
    at Object.getImportCompletionAction (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:107949:31)
    at getCompletionEntryCodeActionsAndSourceDisplay (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:94041:33)
    at Object.getCompletionEntryDetails (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:93991:30)
    at Object.getCompletionEntryDetails (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:114803:35)
    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:122609:57
    at Object.mapDefined (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:578:30)
    at IOSession.Session.getCompletionEntryDetails (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:122607:33)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:121654:61)
    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:123061:88
    at IOSession.Session.executeWithRequestId (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:123052:28)
    at IOSession.Session.executeCommand (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:123061:33)
    at IOSession.Session.onMessage (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:123081:35)
    at Interface.<anonymous> (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:124344:27)
    at emitOne (events.js:116:13)
    at Interface.emit (events.js:211:7)
    at Interface._onLine (readline.js:282:10)
    at Interface._normalWrite (readline.js:424:12)
    at Socket.ondata (readline.js:141:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
[Error  - 2:46:03 PM] 'completionEntryDetails' request failed with error.
Error processing request. Debug Failure. Unknown entity name kind.
Error: Debug Failure. Unknown entity name kind.
    at resolveEntityName (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:32169:32)
    at getTargetOfExportAssignment (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:31995:29)
    at getTargetOfAliasDeclaration (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:32017:28)
    at Object.getImmediateAliasedSymbol (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:30419:45)
    at getDefaultExportInfoWorker (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:108189:39)
    at getDefaultLikeExportInfo (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:108171:24)
    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:107968:35
    at forEachExternalModule (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:108311:21)
    at getAllReExportingModules (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:107963:13)
    at Object.getImportCompletionAction (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:107949:31)
    at getCompletionEntryCodeActionsAndSourceDisplay (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:94041:33)
    at Object.getCompletionEntryDetails (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:93991:30)
    at Object.getCompletionEntryDetails (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:114803:35)
    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:122609:57
    at Object.mapDefined (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:578:30)
    at IOSession.Session.getCompletionEntryDetails (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:122607:33)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:121654:61)
    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:123061:88
    at IOSession.Session.executeWithRequestId (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:123052:28)
    at IOSession.Session.executeCommand (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:123061:33)
    at IOSession.Session.onMessage (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:123081:35)
    at Interface.<anonymous> (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:124344:27)
    at emitOne (events.js:116:13)
    at Interface.emit (events.js:211:7)
    at Interface._onLine (readline.js:282:10)
    at Interface._normalWrite (readline.js:424:12)
    at Socket.ondata (readline.js:141:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
```

Edit Insiders log:
```
[Info  - 4:03:40 PM] Using tsserver from: /usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib
[Info  - 4:03:40 PM] Forking TSServer
[Info  - 4:03:40 PM] Started TSServer
[Error  - 4:04:15 PM] 'completionEntryDetails' request failed with error.
Error processing request. Debug Failure. Unknown entity name kind.
Error: Debug Failure. Unknown entity name kind.
    at resolveEntityName (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:32169:32)
    at getTargetOfExportAssignment (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:31995:29)
    at getTargetOfAliasDeclaration (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:32017:28)
    at Object.getImmediateAliasedSymbol (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:30419:45)
    at getDefaultExportInfoWorker (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:108189:39)
    at getDefaultLikeExportInfo (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:108171:24)
    at /usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:107968:35
    at forEachExternalModule (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:108311:21)
    at getAllReExportingModules (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:107963:13)
    at Object.getImportCompletionAction (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:107949:31)
    at getCompletionEntryCodeActionsAndSourceDisplay (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:94041:33)
    at Object.getCompletionEntryDetails (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:93991:30)
    at Object.getCompletionEntryDetails (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:114803:35)
    at /usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:122609:57
    at Object.mapDefined (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:578:30)
    at IOSession.Session.getCompletionEntryDetails (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:122607:33)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:121654:61)
    at /usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:123061:88
    at IOSession.Session.executeWithRequestId (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:123052:28)
    at IOSession.Session.executeCommand (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:123061:33)
    at IOSession.Session.onMessage (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:123081:35)
    at Interface.<anonymous> (/usr/share/code-insiders/resources/app/extensions/node_modules/typescript/lib/tsserver.js:124344:27)
    at emitOne (events.js:116:13)
    at Interface.emit (events.js:211:7)
    at Interface._onLine (readline.js:282:10)
    at Interface._normalWrite (readline.js:424:12)
    at Socket.ondata (readline.js:141:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)

```
![screenshot_20181009_160758](https://user-images.githubusercontent.com/988056/46674891-90a8e980-cbdd-11e8-9713-3f8d23130744.png)

_Copied from original issue: Microsoft/vscode#60314_

**Comment by mjbvz** [comment]
@Alexand3r I can't reproduce this debug failure. Can you please share the `jsconfig` from your project if it has one. Also, please share a small code sample as text that demonstrates this problem

**Comment by darwinserrano** [comment]
Hi.
This happens when try to import any component with this shape. See the signature of the class and the export default

```jsx
import React, { Component } from 'react'

class MyComponent extends Component {
  render() {
    return (
      <div></div>
    )
  }
}
export default MyComponent
```

So, the result on Ctrl+space is `<import('../MyComponent').MyComponent>`

**Comment by Alexand3r** [comment]
What @darwinserrano showed, however, as seen in the picture, mine throws an error and does nothing with no jsconfig and with a jsconfig where the "target" and "modules" are changed as long as the target is not commonjs, i get the 
```
<import('../MyComponent').MyComponent>
```
Issue

**Comment by TimonVS** [comment]
I think I'm having the same issue, suggestions show up, but they don't automatically import the file anymore. It works perfectly fine in 1.27, but it's broken in 1.28 and the insiders build.

In Insiders build and 1.28 it only shows the suggestion, but it doesn't automatically import the file:

![image 1](https://user-images.githubusercontent.com/876666/46728844-05366380-cc84-11e8-929f-ca6801236869.png)

In 1.27 it suggests to automatically import the file:

![image](https://user-images.githubusercontent.com/876666/46728878-20a16e80-cc84-11e8-9609-ec41d0f5d8f4.png)

This isn't isolated to just React components btw, constant values, functions etc. don't show the import suggestion anymore either.

**Comment by TimonVS** [comment]
Here's a part of my `tsserver.log`:

```
Info 898  [12:3:19.242] response:
    {"seq":0,"type":"response","command":"completionEntryDetails","request_seq":27,"success":false,"message":"Error processing request. Debug Failure. Unknown entity name kind.\nError: Debug Failure. Unknown entity name kind.\n    at resolveEntityName (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:32172:32)\n    at getTargetOfExportAssignment (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:31998:29)\n    at getTargetOfAliasDeclaration (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:32020:28)\n    at Object.getImmediateAliasedSymbol (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:30421:45)\n    at getDefaultExportInfoWorker (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:108207:39)\n    at getDefaultLikeExportInfo (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:108189:24)\n    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:107986:35\n    at forEachExternalModule (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:108329:21)\n    at getAllReExportingModules (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:107981:13)\n    at Object.getImportCompletionAction (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:107967:31)\n    at getCompletionEntryCodeActionsAndSourceDisplay (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:94059:33)\n    at Object.getCompletionEntryDetails (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:94009:30)\n    at Object.getCompletionEntryDetails (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:114821:35)\n    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:122627:57\n    at Object.mapDefined (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:578:30)\n    at IOSession.Session.getCompletionEntryDetails (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:122625:33)\n    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:121672:61)\n    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:123079:88\n    at IOSession.Session.executeWithRequestId (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:123070:28)\n    at IOSession.Session.executeCommand (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:123079:33)\n    at IOSession.Session.onMessage (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:123099:35)\n    at Interface.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:124362:27)\n    at emitOne (events.js:116:13)\n    at Interface.emit (events.js:211:7)\n    at Interface._onLine (readline.js:282:10)\n    at Interface._normalWrite (readline.js:424:12)\n    at Socket.ondata (readline.js:141:10)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    at Socket.Readable.push (_stream_readable.js:208:10)\n    at Pipe.onread (net.js:594:20)"}
Info 899  [12:3:19.730] request:
    {"seq":28,"type":"request","command":"completionEntryDetails","arguments":{"file":"/Users/timon/Projects/sketch/sketch-frontend/projects/cloud-web/src/modules/shares/components/ShareSettingsModal.js","line":27,"offset":2,"entryNames":[{"name":"MemberList","source":"/Users/timon/Projects/sketch/sketch-frontend/projects/cloud-web/src/containers/MemberList/MemberList"}]}}
Info 900  [12:3:19.731] getCompletionData: Get current token: 0
Info 901  [12:3:19.731] getCompletionData: Is inside comment: 0
Info 902  [12:3:19.731] getCompletionData: Get previous token 1: 0
Info 903  [12:3:19.731] getCompletionData: Get previous token 2: 0
Info 904  [12:3:19.731] getCompletionsAtPosition: isCompletionListBlocker: 0
Info 905  [12:3:19.747] getCompletionData: Semantic work: 16
Err 906   [12:3:19.756] Exception on executing command {"seq":28,"type":"request","command":"completionEntryDetails","arguments":{"file":"/Users/timon/Projects/sketch/sketch-frontend/projects/cloud-web/src/modules/shares/components/ShareSettingsModal.js","line":27,"offset":2,"entryNames":[{"name":"MemberList","source":"/Users/timon/Projects/sketch/sketch-frontend/projects/cloud-web/src/containers/MemberList/MemberList"}]}}:

    Debug Failure. Unknown entity name kind.

    Error: Debug Failure. Unknown entity name kind.
    at resolveEntityName (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:32172:32)
    at getTargetOfExportAssignment (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:31998:29)
    at getTargetOfAliasDeclaration (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:32020:28)
    at Object.getImmediateAliasedSymbol (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:30421:45)
    at getDefaultExportInfoWorker (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:108207:39)
    at getDefaultLikeExportInfo (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:108189:24)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:107986:35
    at forEachExternalModule (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:108329:21)
    at getAllReExportingModules (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:107981:13)
    at Object.getImportCompletionAction (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:107967:31)
    at getCompletionEntryCodeActionsAndSourceDisplay (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:94059:33)
    at Object.getCompletionEntryDetails (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:94009:30)
    at Object.getCompletionEntryDetails (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:114821:35)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:122627:57
    at Object.mapDefined (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:578:30)
    at IOSession.Session.getCompletionEntryDetails (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:122625:33)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:121672:61)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:123079:88
    at IOSession.Session.executeWithRequestId (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:123070:28)
    at IOSession.Session.executeCommand (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:123079:33)
    at IOSession.Session.onMessage (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:123099:35)
    at Interface.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:124362:27)
    at emitOne (events.js:116:13)
    at Interface.emit (events.js:211:7)
    at Interface._onLine (readline.js:282:10)
    at Interface._normalWrite (readline.js:424:12)
    at Socket.ondata (readline.js:141:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
Info 907  [12:3:19.756] response:
    {"seq":0,"type":"response","command":"completionEntryDetails","request_seq":28,"success":false,"message":"Error processing request. Debug Failure. Unknown entity name kind.\nError: Debug Failure. Unknown entity name kind.\n    at resolveEntityName (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:32172:32)\n    at getTargetOfExportAssignment (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:31998:29)\n    at getTargetOfAliasDeclaration (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:32020:28)\n    at Object.getImmediateAliasedSymbol (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:30421:45)\n    at getDefaultExportInfoWorker (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:108207:39)\n    at getDefaultLikeExportInfo (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:108189:24)\n    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:107986:35\n    at forEachExternalModule (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:108329:21)\n    at getAllReExportingModules (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:107981:13)\n    at Object.getImportCompletionAction (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:107967:31)\n    at getCompletionEntryCodeActionsAndSourceDisplay (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:94059:33)\n    at Object.getCompletionEntryDetails (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:94009:30)\n    at Object.getCompletionEntryDetails (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:114821:35)\n    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:122627:57\n    at Object.mapDefined (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:578:30)\n    at IOSession.Session.getCompletionEntryDetails (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:122625:33)\n    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:121672:61)\n    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:123079:88\n    at IOSession.Session.executeWithRequestId (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:123070:28)\n    at IOSession.Session.executeCommand (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:123079:33)\n    at IOSession.Session.onMessage (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:123099:35)\n    at Interface.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:124362:27)\n    at emitOne (events.js:116:13)\n    at Interface.emit (events.js:211:7)\n    at Interface._onLine (readline.js:282:10)\n    at Interface._normalWrite (readline.js:424:12)\n    at Socket.ondata (readline.js:141:10)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    at Socket.Readable.push (_stream_readable.js:208:10)\n    at Pipe.onread (net.js:594:20)"}
Info 908  [12:3:20.124] request:
    {"seq":29,"type":"request","command":"completionEntryDetails","arguments":{"file":"/Users/timon/Projects/sketch/sketch-frontend/projects/cloud-web/src/modules/shares/components/ShareSettingsModal.js","line":27,"offset":2,"entryNames":[{"name":"MemberList","source":"/Users/timon/Projects/sketch/sketch-frontend/projects/cloud-web/src/modules/shares/components/ShareMetaSidebar/MemberList"}]}}
Info 909  [12:3:20.124] getCompletionData: Get current token: 0
Info 910  [12:3:20.124] getCompletionData: Is inside comment: 0
Info 911  [12:3:20.124] getCompletionData: Get previous token 1: 0
Info 912  [12:3:20.124] getCompletionData: Get previous token 2: 0
Info 913  [12:3:20.124] getCompletionsAtPosition: isCompletionListBlocker: 0
Info 914  [12:3:20.141] getCompletionData: Semantic work: 17
Err 915   [12:3:20.148] Exception on executing command {"seq":29,"type":"request","command":"completionEntryDetails","arguments":{"file":"/Users/timon/Projects/sketch/sketch-frontend/projects/cloud-web/src/modules/shares/components/ShareSettingsModal.js","line":27,"offset":2,"entryNames":[{"name":"MemberList","source":"/Users/timon/Projects/sketch/sketch-frontend/projects/cloud-web/src/modules/shares/components/ShareMetaSidebar/MemberList"}]}}:

    Debug Failure. Unknown entity name kind.

    Error: Debug Failure. Unknown entity name kind.
    at resolveEntityName (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:32172:32)
    at getTargetOfExportAssignment (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:31998:29)
    at getTargetOfAliasDeclaration (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:32020:28)
    at Object.getImmediateAliasedSymbol (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:30421:45)
    at getDefaultExportInfoWorker (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:108207:39)
    at getDefaultLikeExportInfo (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:108189:24)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:107986:35
    at forEachExternalModule (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:108329:21)
    at getAllReExportingModules (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:107981:13)
    at Object.getImportCompletionAction (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:107967:31)
    at getCompletionEntryCodeActionsAndSourceDisplay (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:94059:33)
    at Object.getCompletionEntryDetails (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:94009:30)
    at Object.getCompletionEntryDetails (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:114821:35)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:122627:57
    at Object.mapDefined (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:578:30)
    at IOSession.Session.getCompletionEntryDetails (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:122625:33)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:121672:61)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:123079:88
    at IOSession.Session.executeWithRequestId (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:123070:28)
    at IOSession.Session.executeCommand (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:123079:33)
    at IOSession.Session.onMessage (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:123099:35)
    at Interface.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:124362:27)
    at emitOne (events.js:116:13)
    at Interface.emit (events.js:211:7)
    at Interface._onLine (readline.js:282:10)
    at Interface._normalWrite (readline.js:424:12)
    at Socket.ondata (readline.js:141:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
Info 916  [12:3:20.148] response:
    {"seq":0,"type":"response","command":"completionEntryDetails","request_seq":29,"success":false,"message":"Error processing request. Debug Failure. Unknown entity name kind.\nError: Debug Failure. Unknown entity name kind.\n    at resolveEntityName (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:32172:32)\n    at getTargetOfExportAssignment (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:31998:29)\n    at getTargetOfAliasDeclaration (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:32020:28)\n    at Object.getImmediateAliasedSymbol (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:30421:45)\n    at getDefaultExportInfoWorker (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:108207:39)\n    at getDefaultLikeExportInfo (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:108189:24)\n    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:107986:35\n    at forEachExternalModule (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:108329:21)\n    at getAllReExportingModules (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:107981:13)\n    at Object.getImportCompletionAction (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:107967:31)\n    at getCompletionEntryCodeActionsAndSourceDisplay (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:94059:33)\n    at Object.getCompletionEntryDetails (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:94009:30)\n    at Object.getCompletionEntryDetails (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:114821:35)\n    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:122627:57\n    at Object.mapDefined (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:578:30)\n    at IOSession.Session.getCompletionEntryDetails (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:122625:33)\n    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:121672:61)\n    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:123079:88\n    at IOSession.Session.executeWithRequestId (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:123070:28)\n    at IOSession.Session.executeCommand (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:123079:33)\n    at IOSession.Session.onMessage (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:123099:35)\n    at Interface.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:124362:27)\n    at emitOne (events.js:116:13)\n    at Interface.emit (events.js:211:7)\n    at Interface._onLine (readline.js:282:10)\n    at Interface._normalWrite (readline.js:424:12)\n    at Socket.ondata (readline.js:141:10)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    at Socket.Readable.push (_stream_readable.js:208:10)\n    at Pipe.onread (net.js:594:20)"}
```

**Comment by DanielRosenwasser** [comment]
@sandersn please make sure the fix makes its way into both `master` and `release-3.1`

**Comment by Alexand3r** [comment]
A small update on the issue
I've been also tracking the other issue which is similar to mine #27640 
I've upgraded and set **typescript@next 3.2.0-dev.20181011**, however that did not work.
I made it work by completely removing **typescript** package AND **typings** package and then re-adding **typescript@next**, only after that started to work again with no issues.
Probably the reason that it still didn't work is that **typings** package was using **typescript@2.9.2**
```
10:41:16 - andrei[~]$ npm -g list typescript
/home/andrei/.nvm/versions/node/v10.10.0/lib
├── typescript@3.2.0-dev.20181011 
└─┬ typings@2.1.1
  └─┬ typings-core@2.3.3
    └── typescript@2.9.2 

10:41:21 - andrei[~]$ npm remove -g typescript
removed 1 package in 0.105s

10:41:33 - andrei[~]$ npm -g list typescript  
/home/andrei/.nvm/versions/node/v10.10.0/lib
└─┬ typings@2.1.1
  └─┬ typings-core@2.3.3
    └── typescript@2.9.2 
```

**Comment by sandersn** [comment]
@Alexand3r so it sounds like the issue is fixed with `typescript@next`?

**Comment by sandersn** [comment]
@andy-ms and I confirmed that it is fixed on 3.1 and master and broken on, at least, 3.0.3.

**Comment by Alexand3r** [comment]
@sandersn yes it is fixed, but only if all instances of typescript have been removed (including npm modules dependant on typescript)

**Comment by huhuanming** [comment]
![image](https://user-images.githubusercontent.com/5743863/47489278-ca821d00-d878-11e8-91a2-ca30328ee9b6.png)
not fix, i am still stuck in a dilemma with this bug.
And it does not resolve in VSCode Insider version.
