### ISSUE TITLE
When trying to use mapped tuples as rest parameters error 'A rest parameter must be of an array type' given

### ISSUE THREAD

**Issue by Roaders** [microsoft/TypeScript#29919]
**TypeScript Version:**  3.2

**Search Terms:** mapped tuples rest 

**Code**

```ts
type FuncParams<T> = T extends (...args: infer P) => any ? P : never;
type Stringify<T> = {
    [K in keyof T]: string;
};
type Optional<T> = {
    [K in keyof T]?: T[K];
};

type ThreeParamFunc = (paramOne: string, paramTwo: number, paramThree: boolean) => void;

type Params = FuncParams<ThreeParamFunc>; // [string, number, boolean]
type StringParams = Stringify<FuncParams<ThreeParamFunc>>; // [string, string, string]
type OptionalParams = Optional<FuncParams<ThreeParamFunc>>; // [string?, number?, boolean?]

function doStuff<T>(func: T, ...params: FuncParams<T>) { // works fine
}

function doOptionalStuff<T>(func: T, ...params: Optional<FuncParams<T>>) { // A rest parameter must be of an array type.
}

function doStringStuff<T>(func: T, ...params: Stringify<FuncParams<T>>) { // A rest parameter must be of an array type.
}
```

**Expected behavior:**
I should be able to use a mapped tuple as a rest param in a function

**Actual behavior:**
I get the error `A rest parameter must be of an array type.`

**Playground Link:** 
[Link](https://www.typescriptlang.org/play/#src=%0D%0Atype%20FuncParams%3CT%3E%20%3D%20T%20extends%20(...args%3A%20infer%20P)%20%3D%3E%20any%20%3F%20P%20%3A%20never%3B%0D%0Atype%20Stringify%3CT%3E%20%3D%20%7B%0D%0A%20%20%20%20%5BK%20in%20keyof%20T%5D%3A%20string%3B%0D%0A%7D%3B%0D%0Atype%20Optional%3CT%3E%20%3D%20%7B%0D%0A%20%20%20%20%5BK%20in%20keyof%20T%5D%3F%3A%20T%5BK%5D%3B%0D%0A%7D%3B%0D%0A%0D%0Atype%20ThreeParamFunc%20%3D%20(paramOne%3A%20string%2C%20paramTwo%3A%20number%2C%20paramThree%3A%20boolean)%20%3D%3E%20void%3B%0D%0A%0D%0Atype%20Params%20%3D%20FuncParams%3CThreeParamFunc%3E%3B%20%2F%2F%20%5Bstring%2C%20number%2C%20boolean%5D%0D%0Atype%20StringParams%20%3D%20Stringify%3CFuncParams%3CThreeParamFunc%3E%3E%3B%20%2F%2F%20%5Bstring%2C%20string%2C%20string%5D%0D%0Atype%20OptionalParams%20%3D%20Optional%3CFuncParams%3CThreeParamFunc%3E%3E%3B%20%2F%2F%20%5Bstring%3F%2C%20number%3F%2C%20boolean%3F%5D%0D%0A%0D%0Afunction%20doStuff%3CT%3E(func%3A%20T%2C%20...params%3A%20FuncParams%3CT%3E)%20%7B%20%2F%2F%20works%20fine%0D%0A%7D%0D%0A%0D%0Afunction%20doOptionalStuff%3CT%3E(func%3A%20T%2C%20...params%3A%20Optional%3CFuncParams%3CT%3E%3E)%20%7B%20%2F%2F%20A%20rest%20parameter%20must%20be%20of%20an%20array%20type.%0D%0A%7D%0D%0A%0D%0Afunction%20doStringStuff%3CT%3E(func%3A%20T%2C%20...params%3A%20Stringify%3CFuncParams%3CT%3E%3E)%20%7B%20%2F%2F%20A%20rest%20parameter%20must%20be%20of%20an%20array%20type.%0D%0A%7D)

**Comment by Andarist** [comment]
Having the same problem - prepared a [simpler repro](https://www.typescriptlang.org/play/#src=type%20Mapped%3CT%3E%20%3D%20%7B%20%5BP%20in%20keyof%20T%5D%3A%20T%5BP%5D%20extends%20string%20%3F%20%5Bnumber%5D%20%3A%20%5Bstring%5D%20%7D%0D%0A%0D%0Adeclare%20function%20test%3CT%20extends%20%5Bnumber%5D%20%7C%20%5Bstring%5D%3E(%0D%0A%20%20a%3A%20T%2C%0D%0A%20%20fn%3A%20(...args%3A%20Mapped%3CT%3E)%20%3D%3E%20any%0D%0A)) (with artificial code ofc).

Real world use case would be to cover reselect's createSelector API in generic manner - https://github.com/reduxjs/reselect#createselectorinputselectors--inputselectors-resultfunc

**Comment by Roaders** [comment]
I also get this issues here:

[playground](http://www.typescriptlang.org/play/?ts=3.3.3#code/FAFwngDgpgBAYgVwHYGMQEsD2SAKBDAJzwFsBnAHgBUA+GAXhkpigA8QokATUmACgDpBEQiVIAuGOiQAzKARgAlAJT1aeJGBgB+RTAlIoANzkBuYKEixieECgAWiVFVoNehvABsEUCZRV1aACNMTA8odTNgKXYCaTwUWABJAFkbezlnAG9gGFyYa1s7CQL7RxRnMzyYEEwAZRACKQBzCV5-WlIG5rMAX3NwaBhUwoBVJCwkZ3p8tIdkcpoYAB8YFNmMmkiB2EpMYfSCCiZWdi4edTAAbQBdFxhsqsucSSQYAGsoMExpRmuJfbsYwmVCet165micjiCVWtRIEDCDzy0nmAHkDLxsD4YJ1GkgmgAaaoAd0w+gQxECciJIDsBCg2OCoXCSCUEga3nBwBQ2E6OPhYQkiThxARsAYmR6MDw5w0kRRqAw2Bg9JACAISABGyJAGlmGwONx3p9vowic8TobZVdbrxSJh1QlfESkCRsTqlEjcqr1a8vVUYBACJgWGAykqkK1BPxhEQyBJwxN8HGjpcdbd2tUCN4CTkA7lOHtZlGhCJ44wi4U5BRE9hk6IQenqNRMxzYAB6ds4oPhTgwQtQHgAOVRTFJBDeMB5BHpaA8YAkAEEVYOQIGy1AYvkEHyqTBTeppTO8Jptvw87k+n1gD6NVqCHaBVAiQAiBUodFQF9KGPB0O1pBeBfF8iQAFhpbMoCUIA)

```
type FunctionParams<T> = T extends (...params: infer R) => any ? R : never;

type matchFunc<T> = (value: T) => boolean;

interface IMatcher<T>{
    match: matchFunc<T>;
    toString: () => string;
}

type MatchUnion<T> = matchFunc<T> | IMatcher<T>;

type ToMatchers<T extends any[]> = {
    [P in keyof T]: MatchUnion<T[P]>;
}

interface ISample{
    funcOne(one: string, two: number, three: boolean): true;
}

const sample: ISample = {} as any;

function returnMatcher<T, K extends keyof T, P extends any[]>(source: T, name: K){
    return {
        proxyFunction: (...params: FunctionParams<T[K]>) => true,
        doMatch: (...params: ToMatchers<FunctionParams<T[K]>>) => true // A rest parameter must be of an array type.
    }
}

returnMatcher(sample, "funcOne").proxyFunction("", 4, true)
```

**Comment by Roaders** [comment]
I'd be interested to hear why this is marked as a suggestion rather than a bug. As far as I see it you can usually use a tuple type as a function parameter but in this scenario (and other similarly complicated scenarios) it doesn't work.

Can anyone explain why it doesn't work in this case? I have tested my mapped type with function parameters and on it's own it works fine as a rest param:
```
type FunctionParams<T> = T extends (...params: infer R) => any ? R : never;

type matchFunc<T> = (value: T) => boolean;

interface IMatcher<T>{
    match: matchFunc<T>;
    toString: () => string;
}

type MatchUnion<T> = matchFunc<T> | IMatcher<T>;

type ToMatchers<T extends any[]> = {
    [P in keyof T]: MatchUnion<T[P]>;
}

interface ISample{
    funcOne(one: string, two: number, three: boolean): true;
}

const sample: ISample = {} as any;

type MappedParams= ToMatchers<FunctionParams<ISample["funcOne"]>>;

function processMatchers(...params: MappedParams) {
}
```
[playground](http://www.typescriptlang.org/play/?ts=3.3.3&ssl=26&ssc=2&pln=2&pc=1#code/FAFwngDgpgBAYgVwHYGMQEsD2SAKBDAJzwFsBnAHgBUA+GAXhkpigA8QokATUmACgDpBEQiVIAuGOiQAzKARgAlAJT1aeJGBgB+RTAlIoANzkBuYKEixieECgAWiVFVoNehvABsEUCZRV1aACNMTA8odTNgKXYCaTwUWABJAFkbezlnAG9gGFyYa1s7CQL7RxRnMzyYEEwAZRACKQBzCV5-WlIG5rMAX3NwaBhUwoBVJCwkZ3p8tIdkcpoYAB8YFNmMmkiB2EpMYfSCCiZWdi4edTAAbQBdFxhsqsucSSQYAGsoMExpRmuJfbsYwmVCet165micjiCVWtRIEDCDzy0nmAHkDLxsD4YJ1GkgmgAaaoAd0w+gQxECciJIDsBCg2OCoXCSCUEga3nBwBQ2E6OPhYQkiThxARsAYmR6MDw5w0W0sQzwEGgnHwRDIDF2ALkFDKGGwatE5GFAqglwARCjUOioObbtRIla0BMYBACJgEqRSNrDgIhCIyP8lSrDWQVNk+kA)

**Comment by OxleyS** [comment]
Problem still exists in Typescript 3.7.2. Looks like a bug. Simple reproduction: [Playground](https://www.typescriptlang.org/play/#code/C4TwDgpgBAClC8UDaBnYAnAlgOwOYBopsBXAWwCMJ0BdAbgFgAoJgehagElsBjAG2IAmEFFHQQAjsUxjSEbMBEAzAPbpkABmqEkARi1Rec3MAAWhMMrCEIwbgDomoSFACyCKAG9kAaSg4oANYQIMqKsNQAXLBI3tRQAL4MzIzcythoUIo67gAUdvlgAIbohaQoUTAAlAgAfFBFJWVImrRQbFAA8t5MqenAmQBMufl2DaXlrtXwdWNNLW3sAKLo6KpRAErC-bM2VFCkxBmUUKFQxSUgUE4QQA)

If you mouse over `P`, it shows up as `[string, number]` as expected. If you mouse over `M`, it looks like it's expanded the entire definition of `Array` as an interface:
```
type M = {
    [x: number]: string | number;
    0: string;
    1: number;
    length: 2;
    toString: () => string;
    toLocaleString: () => string;
    pop: () => string | number | undefined;
    push: (...items: (string | number)[]) => number;
    concat: {
        ...;
    };
    ... 22 more ...;
    values: {
        ...;
    };
}
```

While this is compatible in many ways, it is ultimately not a tuple anymore, so when you try to use it as a rest parameter it complains as such.

**Comment by dragomirtitian** [comment]
@OxleyS Actually the original problem was solved, if you go through a generic mapping type the result will be a tuple: 

```ts
type P = [string, number];


type M<T> = { [K in keyof T]: T[K] };

const f1 = (...params: P) => params[0]; // OK
const f2 = (...params: M<P>) => params[0]; // OK
```
[Playground Link](https://www.typescriptlang.org/play/?ssl=7&ssc=49&pln=1&pc=1#code/C4TwDgpgBAClC8UDaBnYAnAlgOwOYBopsBXAWwCMJ0BdAbgFgAoJp0SKAWQB4AVAPgRQA3sgDSUHFADWEEAHsAZlB7UAXMqSjqUAL4NmjAMZzsaKAoCMggBQA6e2ACG6R6RTqYASgQCnLt0gADHRQAPShUADyokzGpsDmAEw29rZ+ru6cXDB83vC+zhlBIeFRokA)

Not sure  why mapping directly over a tuple is not supported though.

**Comment by RReverser** [comment]
I was about to raise a new issue, but it sounds like the same issue as described in the last comments? [Playground](http://www.typescriptlang.org/play/index.html?ssl=1&ssc=1&pln=12&pc=31#code/PTAEDEHsCdQZ0gWwKamsghggdqD9kAHDaDAF1QAtkAbQ5WAdxgGs493kAPegYwoAmAGjTJEGQoQCW2AOagAVgFc4ZUGWrqlhGqikVEcAHQAoMgE96oALISACiQyGAErXrQAPAEEAfKAC8oADeoADaANKgMqAsyOaQAGagXgC6AFzwZNAy8gC+ANxmlqi2hA6khh7goNwU2ALsABRGLSSycBnYSogARgyhKQCUAX4AbpBSAn6BpeVOcK50DB5zKBTQcFU+PoUmumro4oQZs46VjRid3X3QIj1XvQzD-mMTUwFhAOQYnyKfPZ8UoV9qAuA8bh9DhIjLo5BpdiBQAAhJRqGQ0GQ5eBOVAWKw9dAYNh4epRdbkZDsSCjBh4Gg0GJxdgyXg0JQCLFeaCkcxGQjQSBkQXFUBrSiQBppIpWU4VOAAJiqNS4dQaoGarWg7XB-SGI1A40m02CYUi0Vi8SSq2Q6024B86Uy2TkoAKJj2NtER3lJ3sZwVHguOtuoHuoC6j2gz1eRo+oW+v1A-0BwM95mDkLEEnlMOQcMo+SAA)

```typescript
// For some reason a separate helper works as expected, remapping just the tuple items.
type MapParamsHelper<A> = { [K in keyof A]: string };
type MapParams<F extends (...args: number[]) => void> = MapParamsHelper<Parameters<F>>;

let remap: MapParams<(a: number, b: number) => void> = ['a', 'b'];
let x: number = remap.length;

// But inlining same type breaks and iterates over all keys including Array.prototype methods:
type MapParams2<F extends (...args: number[]) => void> = { [K in keyof Parameters<F>]: string };

let remap2: MapParams2<(a: number, b: number) => void> = ['a', 'b'];
let y: number = remap2.length;
```

@RyanCavanaugh this is marked as a "suggestion" but I think it's actually a bug.

**Comment by OxleyS** [comment]
I don't think it's really solved, I think it's just inconsistent in its behavior. Here's another example that uses a generic mapping type on a tuple and gives the same error: [Playground](https://www.typescriptlang.org/play/#code/JYOwLgpgTgZghgYwgAgJICE4C9kG9kwD2hAXMgBRxkDOYUoA5gDTIBGA-GSAK4C2r0AJTIAvAD5kAN0LAAJgG5kAXwCwAKDABPAA4oAsgB4AKhJF5kAbQDSyUMgDWETYRjIjAXTJHr75fPUIhCC0BACMosjGyBAAHpAgstRomFgsAErRcRAJSQAKcFBwvBCQUNTGFgBERISV7mJi5AB0LdoFRdRkacLiyG2FvNQWAAzuigD048gA8lYBQSEwAEwRBhmx8YnI+QMl0OUY2FU1dQ3Nre2DXT0S-R0jY8iTM3NqgcFgBADMq0aZm0lDqlkOssjlkIYdkU9mUKtViKczi0mncriCbn1LkNRhMpgBRKBQQhQdRAA)

I think the common ground between all the examples that people have posted as not working is the use of a type such as `Parameters`. Could the problem be that the type system is considering the case where `Parameters` expands to `never` and raising an error based on that?

**Comment by RReverser** [comment]
@OxleyS I don't think that's the case; at least it doesn't explain why a workaround with an intermediate generic type works (see my example).

**Comment by levenleven** [comment]
Same error when using builtin `Parameters` and `Partial`:
```typescript
function foo<F extends (...args: any[]) => any>(fn: F, ...args: Partial<Parameters<F>>) { }
```
Error is there, though actual type is resolved properly. [Playground](https://www.typescriptlang.org/play/index.html#code/PTAEAEBcGcFoEsDmA7A9gJwKYCgBmBXZAY0nlWVF1VQB4AxUTAD0k2QBNpQAKAOn4CG6RNABcoAcgCeAbQC6ASlABeAHwTpq7rmTi6AGlD9eQkeIAKQ0gIA2NS+gEBbTK3TR6q1UoDeoAL7YeIQkZBQARkLcAuLI+E7hmOiG4eLQkOjwyIi+AUEgoAButvDsoPjQAoiY0EFUqNyRyaAAjIYA5C3tCgDcddSNQoYtvf0NTaPYBcwADpgkjOjoGGODzW2gne0dAuzs8KTktqAzQs6uSd19eANNw4YZ+JijQA)

**Comment by alshdavid** [comment]
Here is another failure
```typescript
type ProxyParameters<T extends (...args: any) => any> = {
  [K in keyof Parameters<T>]: Parameters<T>[K]
} 

const f1 = (foo: string): string => foo
const f2 = (...args: Parameters<typeof f1>): string => args[0]
// Error:
const f3 = (...args: ProxyParameters<typeof f1>): string => args[0]
```
[Playground](https://www.typescriptlang.org/play?ssl=1&ssc=1&pln=8&pc=1#code/C4TwDgpgBACgTgewB4hgQzmgthYE4DOAPACpQRJ4B2AJgVABQB0LGA5gQFxRpUgCUUALwA+HnzFCoAbwCwAKChQA2gGkoASypQA1hBAIAZrAzZc+YiREBdbukw48hUiLXWFAXygKFAYwRUBMBQhgCMwoyGCAjcQXBabPyxwPFUbMJiUQh+AUEhAEwRzKxwHHamjhZEoJBGIaEiSVBxCRk8pQTKAAzu8v6BwYYAzEUsTOxcsIgo9mZOxDUQdWGNyanpou0c3b1AA)

**Comment by Semperia** [comment]
The issue still exists on typescript 4.5.4. In my case applying generics directly on inferred parameters instead of `Parameters<T>` will fix this error, and I've checked they are actually the same type

```typescript
type PromisifyTuple<T extends readonly unknown[] | []> =  { [P in keyof T]: Promise<T[P]> }

// it's really an tuple
type test = PromisifyTuple<[string, number, {}, Map<string, number>]>

// will raise ts2370
type Transform1<T extends (...args: any[]) => any> = (...args: PromisifyTuple<Parameters<T>>) => ReturnType<T>

// ok if PromisifyTuple is immediately applied on inferred parameters
type PromisifiedArguments<T extends (...args: any[]) => any> = T extends (...args: infer P) => any ? PromisifyTuple<P> : never;
type Transform2<T extends (...args: any[]) => any> = (...args: PromisifiedArguments<T>) => ReturnType<T>

// a is assignable to b and b is assignable to a, they computes to the same type
type TestFunction = (a: string, b: number) => object
let a: PromisifiedArguments<TestFunction> | undefined
let b: PromisifyTuple<Parameters<TestFunction>> | undefined
a = b;
b = a;
```

[playground](https://www.typescriptlang.org/play?target=99&ssl=18&ssc=7&pln=1&pc=1#code/C4TwDgpgBACgTgewLYEsDOKBmIAqBXMAGwgB4coIAPYCAOwBM0o4IBDehWwkKPWga1oIA7rQDaAXSgAfKJIB8UALxQoAbzkwoKWlH4QQCTFBwSAXLESo0pHGJgTFAXwBQLgPTvtwAORMWrITcUKy6wATELqCQUDRowMqWyOhYuBGkYvFwOgDmADRQtHhIAEYQcAVqTgUAsqxgJFm5BUWl5fKObp5QwihBzKzo0MBoAEwAzADsAAxR4NA4cKFomAhwSACMZBTUdIxQABQAdCescDloFqEgkgCUyorXiirHp+eXSdap+ESkMGesJAQGhwNBkeTye5KRQAJWBeDgtBw83BXS8CH42mM8GSGGwP2I2iYKCQQPoKFYNGC9SIKAg9CgnG0tEw5RYDLAAKBILQcxiOK+mDp9AAgudinQRtsqDQGExXkczhcrrQbhIoY9Vc8TDtZfsFUqPjpWXBYBqQqqoAB+T4pfHpEgwRQWWgQABu5QA3HyFktaCs1khRtLdnLDidFe8VWrzU9Egao7a8cKxTkJbQpThIQ8oHDwojkZBUR4vKwiSE0BgcrRWCVCcAEFAShaGc30BWqzW68NG6wCsAABYGKAAY2QYDwcVijcH0DQgOG8x9Jgg8QAYnwR8AUEyXqwLE1aPkmy7imU4OaECUAFYQLcuYgJfdJrAp8VAjNgnCr4Ab2hbndaEUWQ+HoCAhVdegH2BE8X3tX5HS5YFyi-H8-wAzgIRkXgGHAnR6RcMsVBKb1mxUVhPSAA)

**Comment by Harpush** [comment]
Same issue here... Mapped tuple type on `ConstructorParameters` will result in non array. Trying to assign it to an array variable will fail. While just mapping over a tuple works in that assignment (no infer).
```ts
type MapTupleToObject<T extends any[]> = {[P in keyof T]: {value: T[P]}};

const testOne = <T extends any[]>(tuple: MapTupleToObject<T>) => {
  // WORKS!
  const a: any[] = tuple;
}

const testTwo = <T extends new (...args: any[]) => any>(tuple: MapTupleToObject<ConstructorParameters<T>>) => {
  // DOESN'T WORKS!
  const a: any[] = tuple;
}

const testThree = <T extends new (...args: any[]) => any>(tuple: ConstructorParameters<T>) => {
  // WORKS!
  const a: any[] = tuple;
}
```

**Comment by DuBistKomisch** [comment]
Same issue when trying to spread a mapped tuple into another array type:

```
lib/types/json-schema.ts:213:10 - error TS2574: A rest element type must be an array type.

213       ? [...{ -readonly [K in keyof I]: JSONSchemaDataDef<I[K], D> }, ...JSONSchemaDataDef<A, D>[]]
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

However it does work by passing it through a `Concat` recursive conditional type instead: https://stackoverflow.com/a/64631060

Definitely seems like an inconsistency that could be fixed.

**Comment by freshgum-bubbles** [comment]
__Use-case__

Not sure if it helps, but I can provide an explicit use-case for this functionality: mapping an array passed to a function.

Currently, due to this not existing, the only workaround to map arrays passed to functions is to make like 20 overloads.

```ts
type Cast<U> = { value: U };

function Y<U1> (args: [U1]): [Cast<U1>];
function Y<U1, U2> (args: [U1, U2])]: [Cast<U1>, Cast<U2>];
function Y<U1, U2, U3> (args: [U1, U2, U3]): [Cast<U1>, Cast<U2>, Cast<U3>];
function Y<U1, U2, U3, U4> (args: [U1, U2, U3, U4]): [Cast<U1>, Cast<U2>, Cast<U3>, Cast<U4>];
function Y<U1, U2, U3, U4, U5> (args: [U1, U2, U3, U4, U5]): [Cast<U1>, Cast<U2>, Cast<U3>, Cast<U4>, Cast<U5>];
function Y (args: unknown[]): Cast<unknown>[] {
  return args.map(x => ({ value: x }));
}
```

[This is exactly the hack I made in TypeDI to type-check service dependencies](https://github.com/freshgum-bubbles/typedi/pull/38/commits/f518d99c33d7333081744529f98dc4af8ed87119). The obvious problem is that it's... well, it's horrendous.  Sooooo I reverted it, but I'm thinking of undoing that revert as this issue doesn't seem to be gaining any attention.

Once this is implemented, I could simplify the above to...

```ts
type Cast<U> = { value: U };
type CastMany<UArgs extends any[]> = {
  [key in keyof UArgs]: Cast<UArgs[key]>;
}

function Y<UArgs extends any[]> (args: UArgs): CastMany<UArgs> {
  return args.map(x => ({ value: x }));
}
```

**Comment by freshgum-bubbles** [comment]
FYI: This seems to have been secretly fixed in the current version of TypeScript.

[TS 5.0.4 (presents ts2370)](https://www.typescriptlang.org/play?ts=5.0.4#code/C4TwDgpgBAsghmSATAPAFQHxQLxQN5QDaAClAJYB2UA1hCAPYBmUaAugFwsmtQQAewCBSQBnKCOAAnSgHMoAfiIUArgFsARhEk9OhCdIoyeAXwCwAKAtIIAYwA2cSdEbKKN4GXpVBE9LwFCokpqmtpQAD5E+rKsGAAUFlBQcJxoADSJUIwUnHEAdAWOMiKc8IgQqJgAlDhYcBQgFlWc9SAA3EA)
[TS 5.2.2](https://www.typescriptlang.org/play?ts=5.2.2#code/C4TwDgpgBAsghmSATAPAFQHxQLxQN5QDaAClAJYB2UA1hCAPYBmUaAugFwsmtQQAewCBSQBnKCOAAnSgHMoAfiIUArgFsARhEk9OhCdIoyeAXwCwAKAtIIAYwA2cSdEbKKN4GXpVBE9LwFCokpqmtpQAD5E+rKsGAAUFlBQcJxoADSJUIwUnHEAdAWOMiKc8IgQqJgAlDhYcBQgFlWc9SAA3EA)

**Comment by Andarist** [comment]
I bisected this particular change that @freshgum-bubbles mentioned to [this diff](https://github.com/microsoft/TypeScript/compare/86f811440484f6a91e3d2a5ddaeb05eed8bf95cc...f218a562bfb417ecec263fc96d7a7a71abf96268)

**Comment by xixixao** [comment]
I'm also running into this problem, and here's an example of just how broken this currently is:

Works fine:
```ts
type Rec = Record<string, string[]>;

type M<T> = { [K in keyof T]: T[K] };

function foo<E extends Rec, Key extends keyof Rec>(
  e: E,
  key: Key,
  ...args: M<E[Key]>
) {}
```
Now add a constraints to `M`, you get an error:
```ts
type Rec = Record<string, string[]>;

type M<T extends string[]> = { [K in keyof T]: T[K] };

function foo<E extends Rec, Key extends keyof Rec>(
  e: E,
  key: Key,
  ...args: M<E[Key]> // A rest parameter must be of an array type
) {}
```
even though it would seem it's even more obvious that the mapped type is an array in this second version!

**Comment by bruyeret** [comment]
I also encountered this issue.
This is something that works:
```ts
type MyGeneric<T> = { value: T };

type WrapInMyGeneric<T extends any[]> = {
  [P in keyof T]: MyGeneric<T[P]>;
};

// ✅ Use a tuple
declare function f1(...args: WrapInMyGeneric<[string, number]>): void;

// ✅ Use any array
declare function f2(...args: WrapInMyGeneric<any[]>): void;

// ✅ Use the parameters of a function
declare function f3(...args: WrapInMyGeneric<Parameters<(a: string, b: number) => void>>): void;

// ❌ Use the parameters of a generic function
declare function f4<F extends (...args: any[]) => any>(...args: WrapInMyGeneric<Parameters<F>>): void;
```

The funny thing is that if I replace my generic type with the type itself, it works:
```ts
type MyGeneric<T> = T;
```

**Comment by STofone** [comment]
```typescript
type AnyFunction = (...args: any[]) => any;
interface TestService {
  [key: string]: {
    [key: string]: AnyFunction;
  };
}
declare function f<S extends keyof TestService , F extends keyof TestService [S], A extends Parameters<TestService [S][F]>>(k1: S, k2: F, ...args: A): void;
```
❌report at `A` : Rest parameter must be an array type or a generic with array constraint
