### ISSUE TITLE
console.log auto imports import console=require('console');

### ISSUE THREAD

**Issue by mschipperheyn** [microsoft/TypeScript#30471]
- VSCode Version:1.31.1
- OS Version:Mac OS Current

Steps to Reproduce:
type `console.`. 7 times out of 10, vscode will insert `import console=require('console');`in the imports top of the file leading to a compilation error.

Single most annoying issue of vs code by far.

Does this issue occur when all extensions are disabled?: Not sure

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled? Make sure you are using the latest TypeScript version too

Also @Zlass which version of the node typings are you using? I don't see that declaration in the latest `@types/node` and have not been able to repro this issue

**Comment by Zlass** [comment]
Ok, I believe I found the cause. Seems like it's a bug related `@types/styled-components` having a dependacy on `@types/react-native`, which conflicts with the node's `console` type.

 I was able to reproduce it in the insider build by creating a new typescript react app with `create-react-app` and installing `@types/styled-components`.

I don't think this is a VS Code issue and there's already an open issue for it in `DefinitelyTyped` [here](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/33015)

**Comment by mschipperheyn** [comment]
Hmmm, I don't use styled components. Not impossible that it came along with some other library

**Comment by Zlass** [comment]
@mschipperheyn I'd recommend checking what shows up when you try to auto-complete `console`. I was able to figure out what package was declaring another definition of `console` by peeking at the references of each auto-complete suggestion.

**Comment by SukhKalsi** [comment]
I'm experiencing the same (on version 1.30.2). It's a React Native project, not using Styled Components (but any other lib might). When typing `console` below is the respective output of auto complete. The first does an auto `import`, the second does an auto `require`.

<img width="733" alt="Screen Shot 2019-03-20 at 17 47 43" src="https://user-images.githubusercontent.com/10895271/54707376-daa4dc80-4b38-11e9-9958-7e60cf301a38.png">

**Comment by BrendonSled** [comment]
Add a **console.d.ts** file to your src root and add the following contents:
```
declare module 'console' {
    export = typeof import("console");
}
```
That will fix your import

**Comment by SukhKalsi** [comment]
Thanks @BrendonSled for that temp fix... that seems to have resolved it for me - now to add this to all my other projects 🙈

**Comment by 03t02** [comment]
@BrendonSled thanks you !! Finally a tmp solution

**Comment by DanFoad** [comment]
Anyone have an update on this beyond temporary solutions? Google only returns this link and the StackOverflow link posted before

**Comment by aloehh** [comment]
@BrendonSled  thx for your solution

**Comment by jamespacileo** [comment]
This is driving me crazy...

**Comment by atrauzzi** [comment]
Argh, this is so annoying!

**Comment by mattcarlotta** [comment]
Same problem here. I'm on Linux Mint 19.1.

The only way I could get around this `auto import` feature is to either:

Go to `File` :arrow_forward: `Preferences` :arrow_forward: `Settings` :arrow_forward: Search for `Javascript Auto Imports` :arrow_forward: uncheck `Enable/disable auto imports suggestions`.

**OR**

Go to `File` :arrow_forward: `Preferences` :arrow_forward: `User Snippets`:arrow_forward: Select `global.code-snippets` :arrow_forward: Save it to `/vscode/snippets/global.code.snippets` :arrow_forward: then add and save this global snippet (this will make the console snippet below the first entry in the auto suggest list):

```
{
  "Print to console": {
    prefix: ["console", "console.", "console.l", "console.lo", "console.log"],
    body: ["console.log($1);"],
    description: "Log output to console"
  }
};
```

**Comment by EKoetsjarjan** [comment]
same problem here visual studio 1.33.1 node 10
temp solution worked for me...

**Comment by funwithtriangles** [comment]
This is infuriating. Would be great if we could blacklist certain auto imports.

**Comment by AndrewMorsillo** [comment]
This is exceedingly annoying. The workaround posted by @BrendonSled is invalid according to strict ts. Any other way to fix this?

```
'export=' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.   ts(7022)
```

**Comment by nicoceledon** [comment]
> Add a **console.d.ts** file to your src root and add the following contents:
> 
> ```
> declare module 'console' {
>     export = typeof import("console");
> }
> ```
> 
> That will fix your import

For me, as I'm working with js files, had to create a `console.d.js` file with the same content

**Comment by lettertwo** [comment]
@AndrewMorsillo give some suggestions on [this issue](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/33015) a try.

In particular, both [this suggestion](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/33015#issuecomment-463062037) and [this suggestion](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/33015#issuecomment-492569991) seem to have improved the situation for me.

**Comment by mjbvz** [comment]
@RyanCavanaugh Any way we can improve the experience even if there is an incorrect d.ts from a package?

**Comment by coppyC** [comment]
```
declare module 'console' {
    export = typeof import("console");
}
```
the code has an error but can fix the problem

I think it's not beautiful

my template solution is 
```
yarn add @types/node@0.12.23
```
the version don't declare the module "console"

**Comment by timothystewart6** [comment]
Credit to @mattcarlotta for his answer.  I am just formatting this for JSON since VSCode doesn't seem to respect it otherwise:

```
{
	"Print to console": {
	  "prefix": ["console", "console.", "console.l", "console.lo", "console.log"],
	  "body": ["console.log($1);"],
	  "description": "Log output to console"
	}
}
```

This has been driving me 🙃  on React Native projects

**Comment by DanielRosenwasser** [comment]
This issue should have been fixed. If you're still running into this, please

1. [ensure that you still see the behavior after installing this plugin](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next)
2. provide a minimal reproduction of the issue.

**Comment by coppyC** [comment]
@DanielRosenwasser 
I install the plugin and then lost any auto import.
I want the auto import, but dont't want to auto import the console.

**Comment by DanielRosenwasser** [comment]
Okay, that sounds like a separate issue that you should file on https://github.com/Microsoft/TypeScript.

**Comment by dkniffin** [comment]
@DanielRosenwasser That plugin resolved it for me. I'm not quite sure I understand what that does. Is that a workaround until a new version of VSCode is pushed out, or is that a more permanent solution?

**Comment by DanielRosenwasser** [comment]
It means the problem has already been fixed and will be fixed in the next version of VS Code.

**Comment by imoby** [comment]
this is still not fixed in the latest version of vscode

**Comment by topwebtek7** [comment]
Do we have any recent update for this issue? this issue still persist in the latest version of vscode for me as well.

**Comment by DanielRosenwasser** [comment]
Sorry, my bad. It will be in next month's release. Insiders and users of https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next will have the fix available.

**Comment by darkheartfelt** [comment]
@DanielRosenwasser Are you sure about that? I have `JavaScript and TypeScript Nightly` installed and I'm still getting this issue.

**Comment by a-ursino** [comment]
I'm seeing the issue with both VScode Insider (without the plugin) and VSCode (with the plugin installed). They both seem to use `TS 3.6.0-dev.20190810`

VSCode
```
Version: 1.37.0
Commit: 036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8
Date: 2019-08-08T01:22:37.660Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.7.0
```

VSCode Insider
```
Version: 1.38.0-insider
Commit: ffa22b268f451b5211abbe2d2a47e6b753b55b1a
Date: 2019-08-13T07:23:55.783Z
Electron: 4.2.9
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.7.0
```
![Screenshot 2019-08-13 at 17 08 37](https://user-images.githubusercontent.com/157641/62957996-c2867000-bded-11e9-8ed3-52065901855d.png)

**Comment by jeroenptrs** [comment]
Could this please be reopened? Because it's not fixed yet (not even with the Typescript Nightly plugin)

**Comment by andrewbranch** [comment]
Hey all, is someone able to share an actual repo that has this issue? It sounds crazy, but I can’t repro at all. TypeScript has had [special handling](https://github.com/microsoft/TypeScript/blob/11c28d6dd02f4a7d5e0d1f26c327d81b8fb85325/src/services/completions.ts#L1289-L1292) for excluding auto-imports for declarations that just re-export a global for over a year. The fact that that’s not happening for all of you means something very strange, but apparently quite common, is going on.

My best guess is that some combination of dependencies has given you two different versions of `@types/node` simultaneously, and somehow that’s throwing a wrench in the system. I’m going to attempt to invent scenarios like that, but if someone can provide an exact environment where this happens, it will definitely speed up the fix.

**Comment by DanielRosenwasser** [comment]
Looks like this won't make it into the RC, but should make it into the nightly and the proper release of 3.6.

**Comment by jpenna** [comment]
I run Mac and Ubuntu. Mac is fine, Ubuntu has this issue.

For whoever is saying [JavaScript and TypeScript Nightly](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next) isn't working, make sure to configure it properly:

1. Open a JavaScript or TypeScript file in VS Code.
2. In the VS Code command palette, run the TypeScript: Select TypeScript version command.
3. **Make sure you have Use VS Code's version selected**

**Comment by tlaak** [comment]
I was happily living without this issue until I installed styled-components and there it is again.

**Comment by andrewbranch** [comment]
@tlaak what version of TypeScript are you using? I’m quite sure I fixed this in 3.6. Of course, older versions of TypeScript will continue to exhibit this behavior forever.

**Comment by tlaak** [comment]
@andrewbranch I think I was using the older 3.5.x version set up by create-react-app. But anyway, I don't have access to the project anymore so can't confirm.

**Comment by JessicaYeh** [comment]
@andrewbranch I just had the pleasure of running into this very annoying issue with my project, and after upgrading TypeScript from 3.5.x to 3.6 I can confirm that it's fixed!! 🎉 FYI for anyone else with this issue: make sure that the version of Typescript in the bottom right corner of VS Code is also set to 3.6.x

**Comment by codercodingthecode** [comment]
I can confirm that in 3.5.x is there, and on 3.6.2, no more console auto import.
Which 3.6.2 is the vscode default ts version seems like.

![image](https://user-images.githubusercontent.com/20182536/66162641-4c83d580-e5f4-11e9-8878-90a7b29a7c8e.png)

![image](https://user-images.githubusercontent.com/20182536/66162761-8654dc00-e5f4-11e9-9880-a649ccaf42e8.png)

**Comment by Iulia-Soimaru** [comment]
> You can figure it out by following the path of where ever import console=require('console') leads to. Credit to this stackoverflow.

@Zlass this is a life saver 🙏 

For anyone who still have issues: you can follow steps on [stackoverflow](https://stackoverflow.com/questions/53279182/vscode-imports-import-console-requireconsole-automatically)

**Comment by Arcanorum** [comment]
It is back...

**Comment by mjbvz** [comment]
@Arcanorum Please create new issues instead of posting on 4 year old ones
