### ISSUE TITLE
Update declaration of ts.Iterator to be compatible with ES2015 IteratorResult type

### ISSUE THREAD

**Issue by ajafff** [microsoft/TypeScript#31214]
**TypeScript Version:**  3.5.0-dev.20190502

**Search Terms:**

**Code**

I'm trying to use the API changes of #31101, but I run into assignability issues.
```ts
import * as ts from 'typescript';
return ts.getParsedCommandLineOfConfigFile('foo', {}, undefined!, new Map<string, ts.ExtendedConfigCacheEntry>());
```

**Expected behavior:**

No type error.

**Actual behavior:**

```
Argument of type 'Map<string, ExtendedConfigCacheEntry>' is not assignable to parameter of type 'Map<ExtendedConfigCacheEntry>'.
  Types of property 'keys' are incompatible.
    Type '() => IterableIterator<string>' is not assignable to type '() => Iterator<string>'.
      Type 'IterableIterator<string>' is not assignable to type 'Iterator<string>'.
        Types of property 'next' are incompatible.
          Type '(value?: any) => IteratorResult<string>' is not assignable to type '() => { value: never; done: true; } | { value: string; done: false; }'.
            Type 'IteratorResult<string>' is not assignable to type '{ value: never; done: true; } | { value: string; done: false; }'.
              Type 'IteratorResult<string>' is not assignable to type '{ value: string; done: false; }'.
                Types of property 'done' are incompatible.
                  Type 'boolean' is not assignable to type 'false'.
```

**Comment by rbuckton** [comment]
This isn't an issue with lib.d.ts, but our own definition in `src/compiler/core.ts`. This should be fixed when #30790 is merged.

**Comment by ajafff** [comment]
@rbuckton this issue still exists with the latest nightly release. The error message is still the same. Can you please reopen this issue?
