### ISSUE TITLE
navigator.mediaDevices should have getDisplayMedia

### ISSUE THREAD

**Issue by sainnr** [microsoft/TypeScript#33232]
**TypeScript Version:** Version 3.7.0-dev.20190904, also 3.6.2

**Search Terms:** web api, media devices, display media, screen capture, navigator, types

**Code**

```ts
const opts = { audio: false, video: true }
navigator.mediaDevices.getDisplayMedia(opts) // TS2339: Property 'getDisplayMedia' does not exist on type 'MediaDevices'.
```

per `lib.dom.d.ts`, `MediaDevices` has `getUserMedia` but not `getDisplayMedia`. also: https://github.com/Microsoft/TypeScript/blob/master/src/lib/dom.generated.d.ts#L10201

**Expected behavior:**
`getDisplayMedia` should be present on `MediaDevices`, according to https://github.com/w3c/mediacapture-screen-share/pull/86

**Actual behavior:**
`getDisplayMedia` is missing on `MediaDevices`

**Playground Link:** 
https://www.typescriptlang.org/play/#code/MYewdgzgLgBCAOUIwLwwN4wIYFcAmAliAFwwBmWANhAKYA0MAbgXjSTFAE440wC+AKDBZmAcyxQQnAHQBbGoSwARGs2A0I00TShKCEeJSwBPALIKCWABQIkASiA

**Related Issues:** 

- https://github.com/microsoft/TypeScript/issues/31821
- https://github.com/w3c/mediacapture-screen-share/pull/86

**Comment by wiput1999** [comment]
why they still not fix this problem... then how they're using right now

**Comment by madabhaviamit** [comment]
Hi Team,

Looks like this issue is not fixed yet, getDisplayMedia is still missing on mediaDevices. 
What can be an alternative to use for getting the getDisplayMedia capability? I am using angular 6 in my project..

**Comment by LolliDepp** [comment]
still an issue

**Comment by wiput1999** [comment]
@LolliDepp Yeah still an issue

**Comment by danouche93** [comment]
someone got to fix the issue?

**Comment by aponski** [comment]
I'm also having this issue

**Comment by aponski** [comment]
Is there a workaround for this error? I'm using Angular 9 and can't build project.

**Comment by aponski** [comment]
Workaround to disable Typescript error:
`const mediaDevices = navigator.mediaDevices as any; 
  const stream = await mediaDevices.getDisplayMedia();`

**Comment by Soflar** [comment]
Also having the issue =(

**Comment by TheBegining** [comment]
Same issue :(
typescript 3.7.2

**Comment by moonrailgun** [comment]
Still a problem in nightly version.

Maybe you can define it by yourself:

```typescript
declare global {
  interface MediaDevices {
    getDisplayMedia(constraints?: MediaStreamConstraints): Promise<MediaStream>;
  }

  // if constraints config still lose some prop, you can define it by yourself also
  interface MediaTrackConstraintSet {
    displaySurface?: ConstrainDOMString;
    logicalSurface?: ConstrainBoolean;
    cursor?: ConstrainBoolean;
    // more....
  }
}
```

**Comment by AlbyGNinja** [comment]
Nope, still this problem, also trying workaround..

**Comment by mivanovaxway** [comment]
Workarounds are bad. getDisplayMedia is complex as it is. We need good definitions.

**Comment by riotrah** [comment]
Seconded - any progress? This API is probably only going to grow in in importance and popularity.

**Comment by voigtd** [comment]
Still an issue

**Comment by srivatsav-prayaga** [comment]
Confirm if it's user media or display media guys!

**Comment by Akimotorakiyu** [comment]
Still issue!

**Comment by MichielS-1848709** [comment]
@sandersn please have a look at this!

**Comment by canvascat** [comment]
Will it be resolved in v4.2.0 ?

**Comment by Caesar2011** [comment]
Typescript 4.2.3, 18 months later and still not fixed. It would be so simple!

**Comment by mbalc** [comment]
a fix for this would have really helped me during my ongoing, new adventure with WebRTC

**Comment by SgAkErRu** [comment]
Typescript 4.3.5, still not fixed. I think it's because getDisplayMedia is [W3C Working Draft](https://www.w3.org/TR/screen-capture/), but that feature common used and supported by three leading browsers (Firefox, Chrome, Safari), according to [Mozilla MDN ](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getDisplayMedia).

**Comment by YongzeYao** [comment]
Plz add definitions for this!

**Comment by roerohan** [comment]
```
Property 'getDisplayMedia' does not exist on type 'MediaDevices'.
```
Is a fix being made for this?

**Comment by akhil-rana** [comment]
Please add definitions for getDisplayMedia. This is being used everywhere and is a web standard now.

**Comment by kim3er** [comment]
If I understand the process correctly ultimately means we get these new types, it looks like `getDisplayMedia` is on it's way. 

https://github.com/microsoft/TypeScript-DOM-lib-generator/issues/992#issuecomment-911796224

**Comment by sandersn** [comment]
1. TS 4.4 includes `getDisplayMedia`
2. If you can't upgrade to 4.4, you can add a reference to `@types/web@0.0.2` (or higher) and **remove** `'dom'` from your `'lib'` array in tsconfig.
