### ISSUE TITLE
Optional chaining when referencing array element causes overly strict type narrowing 

### ISSUE THREAD

**Issue by DylanSp** [microsoft/TypeScript#35970]
I'm having an issue where optional chaining causes more type narrowing than it should.

**Search Terms:**
* Optional chaining
* Type narrowing

**Code**
```ts
interface Left {
    tag: "left";
    left: string;
}

interface Right {
    tag: "right",
    right: number;
}

type Union = Left | Right;

const arr: Array<Union> = [
    {
        tag: "left",
        left: "someStr"
    },
    {
        tag: "right",
        right: 0
    }
];

let i = 0;
while (arr[i]?.tag === "left") {
    i += 1;

    if (arr[i].tag === "right") {
        console.log("I should be reachable");
    }

    if (arr[i]?.tag === "right") {
        console.log("I should ALSO be reachable");
    }
}
```

**Expected behavior:**
Code compiles without errors.

**Actual behavior:**
Compilation fails with error TS2367: "This condition will always return false since the types '"left"' and '"right"' have no overlap" on ` if (arr[i]?.tag === "right")`

Because `i` is changed before the `if` checks, `arr[i]?.tag` should allow for the possibility of being `"right"` as well as `"left"`.

**Playground Link:** [Here](https://www.typescriptlang.org/play/?ssl=36&ssc=1&pln=1&pc=1#code/JYOwLgpgTgZghgYwgAgDIRmZBvAsAKGSOTDgHMAuZAIgBsMxqBuA45ezKgZzClDJb4AvgQKhIsRCgBKwMgAsseQsVKUafBYwA0rYpsVUQAVwC2AI2iCR+AmACeABxQBVEMAD2IZAF40DZAAfZFktQQIELx5kOCgoKgBBOLh7AB43TxAAPl9kAG09ImU2NjUqOgZqXRUS9gZyrg9TCABlXmpC5CFqtmLaknJygx1OtmGqAAZOmwBdcPx6LGBcicEAd3lgemQAClioPOAZgH4AOjVfHz8KzGoAShxO5YBqPwBGebZgGF39w5nzuRLtdhvdHjUSpEQI16KdaB4yDtqABJZBceQeYy0AAmyEsyCgEEQ8jg5no90EbBsTx+ezi-zOFyuILkijBfVqUJhEDhCKRqPRmJxyASqBaAHk8ShCcTSeS7pTiDYbEA)

**Comment by RyanCavanaugh** [comment]
Should be fixed by #36089

**Comment by DylanSp** [comment]
Testing in the TypeScript playground with nightly (version 3.8.0-dev.20200109), the problem still appears; I still see an error reported on `if (arr[i]?.tag === "right")`.

**Comment by RyanCavanaugh** [comment]
I misread the repro. Simplified
```ts
let i = 0;
declare const arr: { tag: ("left" | "right") }[];

// No error
while (arr[i].tag === "left") {
    i += 1;

    if (arr[i].tag === "right") {
        console.log("I should ALSO be reachable");
    }
}

// Error
while (arr[i]?.tag === "left") {
    i += 1;

    if (arr[i]?.tag === "right") {
        console.log("I should ALSO be reachable");
    }
}
```

**Comment by ahejlsberg** [comment]
This is a bit nastier than meets the eye:

```ts
if (arr[i]?.tag === "left") {
    const x = arr[i * 2]?.tag;  // Type is "left" -- wat?
}
```

**Comment by DylanSp** [comment]
Confirmed that it's fixed on the Playground, using nightly (version 3.8.0-dev.20200117). Thanks for the quick response!
