### ISSUE TITLE
every does not respect typeguard 

### ISSUE THREAD

**Issue by deser** [microsoft/TypeScript#36892]
**TypeScript Version:**  3.7.5

**Search Terms:**
every, type guard

**Code**
https://www.typescriptlang.org/play/index.html#code/JYOwLgpgTgZghgYwgAgPrIN4FgBQz-LADOAcgK4C2ARtABQBucANmRAPwBcycIAngJRdGLFMWQhKNKLgC+AblwIA9iCJg0yALyZcBQqUnQuDZqy48BWgHzJhrWbkUq1hSBS2Z5T1eozIAHgA0yLzBAO7BABbIMh7AbtxEmAFcEtTQyAA+yGQgACYQMKAQeXIhqYZQWTn5hcWlyGEV6VXZuQVFICVlkc1S1e11XXkxCjjeLgAOSkTxwCoeANpBIeFRALoAdBD00Ly0qJvE5C38ugRsyLTYeHp3+EHn93qhT8-4EW-vkV8EMme3fBcQadbqOHDAGBXaazMDzED8ZJvJgQdT+fweGFzFSbfxjPTKVRKFGbJhKADmtHRAGpqfwxjJwcggA

See pic with issue below:
![image](https://user-images.githubusercontent.com/3010698/74931469-b7da1280-53f0-11ea-81b0-7a1be8a18004.png)

**Expected behavior:**
`xx` is `number`

**Actual behavior:**
`xx` is `number | undefiend`

**Playground Link:** https://www.typescriptlang.org/play/index.html#code/JYOwLgpgTgZghgYwgAgPrIN4FgBQz-LADOAcgK4C2ARtABQBucANmRAPwBcycIAngJRdGLFMWQhKNKLgC+AblwIA9iCJg0yALyZcBQqUnQuDZqy48BWgHzJhrWbkUq1hSBS2Z5T1eozIAHgA0yLzBAO7BABbIMh7AbtxEmAFcEtTQyAA+yGQgACYQMKAQeXIhqYZQWTn5hcWlyGEV6VXZuQVFICVlkc1S1e11XXkxCjjeLgAOSkTxwCoeANpBIeFRALoAdBD00Ly0qJvE5C38ugRsyLTYeHp3+EHn93qhT8-4EW-vkV8EMme3fBcQadbqOHDAGBXaazMDzED8ZJvJgQdT+fweGFzFSbfxjPTKVRKFGbJhKADmtHRAGpqfwxjJwcggA

**Comment by RyanCavanaugh** [comment]
Control flow analysis isn't capable of doing backwards reasoning like would be required to identify this as not undefined

**Comment by OliverJAsh** [comment]
Fixed by https://github.com/microsoft/TypeScript/pull/38200?

**Comment by HaleTom** [comment]
@OliverJAsh  sadly this issue still remains.

Here is another (possibly simpler) example:

https://www.typescriptlang.org/play?#code/C4TwDgpgBAMgkgOwCYQB4B4YBooCUB8UAvFALICGYmOAyhMOgfgNwCwAUKJHoihtnkIkKVXLXqZ8LDhwDGAewQBnYFADm9XmghKAYgCd5AWwCC+tUuJRqggBQcojqABstqAPwAuWG5sEsDk76bl48yGh++BwAlN4A2vDh-Dj+YXyRALrEhADegY4Kyqrk5pYkca5JOMFJGWzs+VAAlgBmULYlFgB0EABuEPogHebZUFwQ8m2dxEQkAK7hLU0IEEjR0VB57E47UPr0c-oIUHErAO5klLYb5JaJ6QKp55dg11C3aRGP+HWNAL4ybZBA5HE6VPjVNy-dh-IA
