### ISSUE TITLE
Missed `Object.assign` for es5 target in compiler output

### ISSUE THREAD

**Issue by eKazim** [microsoft/TypeScript#39140]
Found a strange behavior of the compiler when use React with styled-components. It looks like the spread statement (for merge props) is not converted to an `Object.assign` call (for es5 target) when using `React.createElement` inside the `styled` function.
Below there is an example using the material-like component `Typography`. As result, styled-component `Label` is transpiled without `assign` function.
In previous versions of Typescript (3.8.x and lower) this code has been compiled correctly.
If i replace inline-call by a constant variable, then it will be compiled with `assign`. You can try this in playground.

**TypeScript Version:**  3.9.5 (3.9.x)

**Search Terms:** styled-components createElement Object.assign

**Actual behavior:**
Compiler miss `Object.assign` call for spread-statement.

**Expected behavior:**
In output for es5 target all spread-statements for objects must be replaced by `Object.assign` calls.

**Related Issues:**
Possible related with last optimizations of compiler in version 3.9 (issues like #37213)

**Code**
```ts
import React from 'react';
import styled from 'styled-components';
import classnames from 'classnames';

interface TypographyProps {
  children: React.ReactNode;
  variant?: Variant;
  color?: Color;
  weight?: FontWeight;
  className?: string;
  id?: string;
}

type Variant =
  | 'h1'
  | 'h2'
  | 'h3'
  | 'h4'
  | 'body'
  | 'subtitle'
  | 'caption'
  | 'overline';

type Color =
  | 'primary'
  | 'secondary'
  | 'main'
  | 'disabled';

type FontWeight = 'normal' | 'medium' | 'bold';

const Typography = React.forwardRef<HTMLParagraphElement, TypographyProps>(({
  children,
  variant,
  color,
  weight,
  className,
  ...other
}, ref) => {
  const combinedClassName = classnames(
    className,
    {
      variant: `variant-${variant}`,
      color: `color-${color}`,
      weight: `weight-${weight}`,
    }
  );

  return (
    <p
      className={combinedClassName}
      ref={ref}
      {...other}
    >
      {children}
    </p>
  );
});

const Label = styled(
  (props) => React.createElement(Typography, {
    as: 'label', variant: 'body', color: 'secondary', ...props,
  })
)`
  display: block;
  margin-bottom: 16px;
`;

const SomeComponentWithLabel = ({ children, ...otherProps }: any) => {
  return (
    <Label {...otherProps}>{children}</Label>
  );
}

```

<details><summary><b>Output</b></summary>

```ts
var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
var __assign = (this && this.__assign) || function () {
    __assign = Object.assign || function(t) {
        for (var s, i = 1, n = arguments.length; i < n; i++) {
            s = arguments[i];
            for (var p in s) if (Object.prototype.hasOwnProperty.call(s, p))
                t[p] = s[p];
        }
        return t;
    };
    return __assign.apply(this, arguments);
};
var __rest = (this && this.__rest) || function (s, e) {
    var t = {};
    for (var p in s) if (Object.prototype.hasOwnProperty.call(s, p) && e.indexOf(p) < 0)
        t[p] = s[p];
    if (s != null && typeof Object.getOwnPropertySymbols === "function")
        for (var i = 0, p = Object.getOwnPropertySymbols(s); i < p.length; i++) {
            if (e.indexOf(p[i]) < 0 && Object.prototype.propertyIsEnumerable.call(s, p[i]))
                t[p[i]] = s[p[i]];
        }
    return t;
};
import React from 'react';
import styled from 'styled-components';
import classnames from 'classnames';
var Typography = React.forwardRef(function (_a, ref) {
    var children = _a.children, variant = _a.variant, color = _a.color, weight = _a.weight, className = _a.className, other = __rest(_a, ["children", "variant", "color", "weight", "className"]);
    var combinedClassName = classnames(className, {
        variant: "variant-" + variant,
        color: "color-" + color,
        weight: "weight-" + weight,
    });
    return (React.createElement("p", __assign({ className: combinedClassName, ref: ref }, other), children));
});
var Label = styled(function (props) { return React.createElement(Typography, {
    as: 'label', variant: 'body', color: 'secondary', ...props,
}); })(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n  display: block;\n  margin-bottom: 16px;\n"], ["\n  display: block;\n  margin-bottom: 16px;\n"])));
var SomeComponentWithLabel = function (_a) {
    var children = _a.children, otherProps = __rest(_a, ["children"]);
    return (React.createElement(Label, __assign({}, otherProps), children));
};
var templateObject_1;

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "useDefineForClassFields": false,
    "alwaysStrict": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "downlevelIteration": false,
    "noEmitHelpers": false,
    "noLib": false,
    "noStrictGenericChecks": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "esModuleInterop": true,
    "preserveConstEnums": false,
    "removeComments": false,
    "skipLibCheck": false,
    "checkJs": false,
    "allowJs": false,
    "declaration": true,
    "experimentalDecorators": false,
    "emitDecoratorMetadata": false,
    "target": "ES2017",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play/index.html?experimentalDecorators=true&emitDecoratorMetadata=true&target=1&jsx=2&ssl=1&ssc=1&pln=15&pc=1#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4AoUSWOAZxgE8AbJAEzm1wPubYFo0uSADskwmLTKVw0eGiYpatYShBJaHHHnzzFy1eqmVxSKJnRI4AFQaQA5lBRgAFgwAKOMBoDe5OHDRnYCZWImEALkRiGAA6ZHQYADkIViQKfwA3FChgFHEAfkiANWzc8XSAiCZoQrgAYSroCoB3JGA7ZxhagDEIcQB1No6YCt0lRINa+hzhOwrgVimYGbnyAF9yckYwSxKcvPgAXj84AB8CZwBGfBPz-GcAJhv-O+cAZmezi4AWT7uAIxSDD+3AArv8YMAYCwQTonJC+rCIBlTExgKIjNtLA1qlA4McXgQwDkQNlgbduEhBMJWGTYaT0bDWMBaCh-ixWJjbJZegMhp18QRhNBSUx8F98GpmaCQOKAVVORRyNT6NZbBAHE5XIL4hgYphoM1sqxkJgADwACSsAFkADJubIoTUuACiLDU4gANGr7I4XO5PLQAHwAChDvn8gWCoTEnpOWX2XpOglxcf8rXanTTAQU4wM2ZihYgMGcpnW3qImAAlPig3AI5VhKrBCB-ui2HVc7QJmpBWN9GpaCGTpGuz2kNn-A3-JlSgdIgADBNlGB8AAk3mXBzWC8nM5T0EXB6g6+8x53e-T-Jgi4zw1Pd86F5HcA2-irSv8RBgoKgwjgw4znAZpgC+o56OOhxnrgbaiKwnYQQYb5AXAlZQZWyFAd4hYxMWpZQJhcBBmB9ZRiEYSEWaAD0YDEe+FBrB+mwqvAtpskgTCCjwHKAQBxIQF4NaHHWuqxGgRAoDASBukgHowCGNi+lqDDetOcCKJE+AKP8HH4N6W7iJpgKsMC3rHpptBUn0tJQKZcA4fxXjZox5BVguJzMrQYAKAwkTshAaAANYVKSUB2OifCAjAMC4JElwAGxgAAHhQC5KixcAAMq4EgDQyKIAxQs4bE6ZxhwAd4ARBORsb2UWJamB4AkaGskR5AwQl1g236-v+vH+GaJUcfWOF4Y1gZrEGZ7VTGwhrNRQ1MHRcBMWsQA)

**Comment by MartinJohns** [comment]
[Playground Link for TypeScript 3.8.3](https://www.staging-typescript.org/play?target=1&ts=3.8.3#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4AoUSWOAZxgE8AbJAEzm1wPubYFo0uSADskwmLTKVw0eGiYpatYShBJaHHHnzzFy1eqmVxSKJnRI4AFQaQA5lBRgAFgwAKOMBoDe5OHDRnYCZWImEALkRiGAA6ZHQYADkIViQKfwA3FChgFHEAfkiANWzc8XSAiCZoQrgAYSroCoB3JGA7ZxhagDEIcQB1No6YCt0lRINa+hzhOwrgVimYGbnyAF9yckYwSxKcvPgAXj84AB8CZwBGfBPz-GcAJhv-O+cAZmezi4AWT7uAIxSDD+3AArv8YMAYCwQTonJC+rCIBlTExgKIjNtLA1qlA4McXgQwDkQNlgbduEhBMJWGTYaT0bDWMBaCh-ixWJjbJZegMhp18QRhNBSUx8F98GpmaCQOKAVVORRyNT6NZbBAHE5XIL4hgYphoM1sqxkJgADwACSsAFkADJubIoTUuACiLDU4gANGr7I4XO5PLQAHwAChDvn8gWCoTEnpOWX2XpOglxcf8rXanTTAQU4wM2ZihYgMGcpnW3qImAAlPig3AI5VhKrBCB-ui2HVc7QJmpBWN9GpaCGTpGuz2kNn-A3-JlSgdIgADBNlGB8AAk3mXBzWC8nM5T0EXB6g6+8x53e-T-Jgi4zw1Pd86F5HcA2-irSv8RBgoKgwjgw4znAZpgC+o56OOhxnrgbaiKwnYQQYb5AXAlZQZWyFAd4hYxMWpZQJhcBBmB9ZRiEYSEWaAD0YDEe+FBrB+mwqvAtpskgTCCjwHKAQBxIQF4NaHHWuqxGgRAoDASBukgHowCGNi+lqDDetOcCKJE+AKP8HH4N6W7iJpgKsMC3rHpptBUn0tJQKZcA4fxXjZox5BVguJzMrQYAKAwkTshAaAANYVKSUB2OifCAjAMC4JElwAGxgAAHhQC5KixcAAMq4EgDQyKIAxQs4bE6ZxhwAd4ARBORsb2UWJamB4AkaGskR5AwQl1g236-v+vH+GaJUcfWOF4Y1gZrEGZ7VTGwhrNRQ1MHRcBMWsQA) (correctly using `Object.assign`)

```
var Label = styled(function (props) { return React.createElement(Typography, __assign({ as: 'label', variant: 'body', color: 'secondary' }, props)); })(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n  display: block;\n  margin-bottom: 16px;\n"], ["\n  display: block;\n  margin-bottom: 16px;\n"])))
```

[Playground Link for TypeScript 3.9.2](https://www.staging-typescript.org/play?target=1&ts=3.9.2#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4AoUSWOAZxgE8AbJAEzm1wPubYFo0uSADskwmLTKVw0eGiYpatYShBJaHHHnzzFy1eqmVxSKJnRI4AFQaQA5lBRgAFgwAKOMBoDe5OHDRnYCZWImEALkRiGAA6ZHQYADkIViQKfwA3FChgFHEAfkiANWzc8XSAiCZoQrgAYSroCoB3JGA7ZxhagDEIcQB1No6YCt0lRINa+hzhOwrgVimYGbnyAF9yckYwSxKcvPgAXj84AB8CZwBGfBPz-GcAJhv-O+cAZmezi4AWT7uAIxSDD+3AArv8YMAYCwQTonJC+rCIBlTExgKIjNtLA1qlA4McXgQwDkQNlgbduEhBMJWGTYaT0bDWMBaCh-ixWJjbJZegMhp18QRhNBSUx8F98GpmaCQOKAVVORRyNT6NZbBAHE5XIL4hgYphoM1sqxkJgADwACSsAFkADJubIoTUuACiLDU4gANGr7I4XO5PLQAHwAChDvn8gWCoTEnpOWX2XpOglxcf8rXanTTAQU4wM2ZihYgMGcpnW3qImAAlPig3AI5VhKrBCB-ui2HVc7QJmpBWN9GpaCGTpGuz2kNn-A3-JlSgdIgADBNlGB8AAk3mXBzWC8nM5T0EXB6g6+8x53e-T-Jgi4zw1Pd86F5HcA2-irSv8RBgoKgwjgw4znAZpgC+o56OOhxnrgbaiKwnYQQYb5AXAlZQZWyFAd4hYxMWpZQJhcBBmB9ZRiEYSEWaAD0YDEe+FBrB+mwqvAtpskgTCCjwHKAQBxIQF4NaHHWuqxGgRAoDASBukgHowCGNi+lqDDetOcCKJE+AKP8HH4N6W7iJpgKsMC3rHpptBUn0tJQKZcA4fxXjZox5BVguJzMrQYAKAwkTshAaAANYVKSUB2OifCAjAMC4JElwAGxgAAHhQC5KixcAAMq4EgDQyKIAxQs4bE6ZxhwAd4ARBORsb2UWJamB4AkaGskR5AwQl1g236-v+vH+GaJUcfWOF4Y1gZrEGZ7VTGwhrNRQ1MHRcBMWsQA) (incorrectly uses object spread)

```
var Label = styled(function (props) { return React.createElement(Typography, {
    as: 'label', variant: 'body', color: 'secondary', ...props,
}); })(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n  display: block;\n  margin-bottom: 16px;\n"], ["\n  display: block;\n  margin-bottom: 16px;\n"])));
```

**Comment by weswigham** [comment]
I believe this has already been fixed in the nightly (indeed, you can see as much in the nightly playground). I'm currently unsure what change is responsible, but something more than a week old, as I've looked through the recent changes.

@RyanCavanaugh should I look into what change is responsible for a 3.9 port, or does it not matter?

**Comment by RyanCavanaugh** [comment]
I'm OK with not porting if we don't get any other reports of this.

**Comment by pablopalacios** [comment]
@weswigham I still see this issue with ts 4.8.3 and I think it's still relevant. I would expect that, by setting the correct libs in the compiler options, I would be able to have es5 syntax with support for es6 libs as it's described in the [docs](https://www.typescriptlang.org/tsconfig#lib):

> Your runtime platform provides certain JavaScript API objects (maybe through polyfills), but doesn’t yet support the full syntax of a given ECMAScript version

However this is not really happening:

### Input
```ts
const a = { foo: "bar" };
({ ...a });
Object.assign({}, a);
```

### Output
`tsc -t es5 --lib es6`

```js
var __assign = (this && this.__assign) || function () {
    __assign = Object.assign || function(t) {
        for (var s, i = 1, n = arguments.length; i < n; i++) {
            s = arguments[i];
            for (var p in s) if (Object.prototype.hasOwnProperty.call(s, p))
                t[p] = s[p];
        }
        return t;
    };
    return __assign.apply(this, arguments);
};
var a = { foo: "bar" };
(__assign({}, a));
Object.assign({}, a);
```

`tsc -t es6`

```js
const a = { foo: "bar" };
(Object.assign({}, a));
Object.assign({}, a);
```

The funny thing is that both targets don't support object spread and have support to `Object.assign`, but the output is completely different: the compiler is still creating a polyfill when targeting `es5`.

**Comment by frankbo** [comment]
@weswigham I face the same issue. I assume that there are not many people looking in the transpiled code, but still it bloats the output up. Could you test the example above and reopen the ticket as a bug when you have the same outcome?

**Comment by RyanCavanaugh** [comment]
The behavior described in https://github.com/microsoft/TypeScript/issues/39140#issuecomment-1250873523 is intentional.

**Comment by pablopalacios** [comment]
@RyanCavanaugh I will not dare to question if this is right or wrong since I bet you know what you are doing. However, what is the reasoning behind it?

**Comment by RyanCavanaugh** [comment]
I guess you'd have to tell me why you think it's *not* the expected behavior? `lib` does not control downleveling behavior, nor should it, since you might be specifying e.g. `lib: none` and supplying a custom lib.
