### ISSUE TITLE
Typescript tsconfig.json cannot find global type 'Boolean'

### ISSUE THREAD

**Issue by roa-nyx** [microsoft/TypeScript#40509]
Issue Type: <b>Bug</b>

This is a minimal reproducible example of an issue I'm experiencing with a code project that has been working for a long time without issue.

### Steps to reproduce
- Create new folder, and open folder in VSCode.
- Create a tsconfig.json file (I have tried with just an empty config `{}` and with a few `compilerOptions` as well and have the same issue).
- Use `npm init` to create a package.json (default values is fine)
- Use `npm install typescript`.
- Create an `index.ts` file (you can leave the file empty).

### Problem
The problems tab will now show seven errors all of which say `Cannot find global type 'Boolean'. ts [1,1]` (See screenshot for my tsconfig and the problems tab). All these errors are attributed to the `tsconfig.json` file. I'm not sure if this is resultant from these errors or something else but type resolution/intellisense appears to fail throughout all typescript files.

![image](https://user-images.githubusercontent.com/8572438/92850012-f3065800-f3b9-11ea-9296-ab77961325e0.png)

[EDIT]
Upon further investigation restarting TS server hides/removes these errors from the problems tab. But intellisense/type-resolution is still broken. Also adding TS 3.9.7 to the workspace and using that does not resolve these issues. Any diagnostic or troubleshooting I can do would be appreciated.

VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T13:22:08.892Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.81GB (5.57GB free)|
|Process Argv|C:\_bunker\4klick\CM --crash-reporter-id 4f0cfeed-1899-4534-99dc-3679fb8c95af|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
ue4-snippets|CAP|2.0.1
tsl-problem-matcher|eam|0.3.0
url-encode|fle|1.1.0
vscode-pull-request-github|Git|0.19.0
docomment|k--|0.1.18
csharp|ms-|1.23.2
cpptools|ms-|0.29.0
hexeditor|ms-|1.3.0
debugger-for-chrome|msj|4.12.10

</details>

**Comment by roa-nyx** [comment]
You are, of course, correct. But I just don't understand why that all gets fixed with the @types/node dependency as well. I find that confusing.

This is definitely a case of user error though. Sorry again for the false alarm.

**Comment by DanielRosenwasser** [comment]
Unfortunately Node.js types are able to force the types for the full environment to be present.

**Comment by roa-nyx** [comment]
Ah. So that's how that works. Thank you @DanielRosenwasser.

Please feel free to close this task. As the OP I realize this is not a bug, not an issue with VS code at all, and the issue has been resolved and you've all supported me despite all of that.

Thanks!

**Comment by XenoBino** [comment]
I had `@types/node` installed and that didn't help. Adding or removing values to "lib" didn't solve it either. Restarting `tsc -p tsconfig.json --watch` did it for me.
