### ISSUE TITLE
TypeError: Cannot read property 'declarations' of undefined

### ISSUE THREAD

**Issue by lazytype** [microsoft/TypeScript#41823]
**TypeScript Version:**  4.1.2

**Search Terms:**

**Code**

```ts
import React from 'react';

type Override<T, U> = Omit<T, keyof U> & U;

type BoxProps<T extends keyof JSX.IntrinsicElements = keyof JSX.IntrinsicElements> = 
  Override<React.ComponentProps<T>, { as: T }>;

export function Box(props: BoxProps) {
  const { as: Component, ...rest } = props;
  // @ts-expect-error
  return <Component {...rest} />;
}
```

**Expected behavior:** tsc exits normally

**Actual behavior:** tsc crashes with stack trace
```
/node_modules/typescript/lib/tsc.js:87001
                throw e;
                ^

TypeError: Cannot read property 'declarations' of undefined
    at addImplementationSuccessElaboration (/node_modules/typescript/lib/tsc.js:57022:116)
    at resolveCall (/node_modules/typescript/lib/tsc.js:56947:33)
    at resolveJsxOpeningLikeElement (/node_modules/typescript/lib/tsc.js:57576:20)
    at resolveSignature (/node_modules/typescript/lib/tsc.js:57597:28)
    at getResolvedSignature (/node_modules/typescript/lib/tsc.js:57608:26)
    at checkJsxOpeningLikeElementOrOpeningFragment (/node_modules/typescript/lib/tsc.js:55477:27)
    at checkJsxSelfClosingElementDeferred (/node_modules/typescript/lib/tsc.js:55058:13)
    at checkDeferredNode (/node_modules/typescript/lib/tsc.js:64402:21)
    at Map.forEach (<anonymous>)
    at checkDeferredNodes (/node_modules/typescript/lib/tsc.js:64373:37)
error Command failed with exit code 1.
```

**Playground Link:** [Link](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4AocmATzCTgHkA3JKKYAEyQB4AVAGjgBVAHxwAvIxDAYfQQGsk1CJmFiAZMIpVa9AEIQAHgAUcYAM584SQzCQA7DubiLlqgFIBlABoA6AJL2MOz25sBoAKIANkggDjDOkq4qcF5+gcHAoeHRsfHmYpLkcIwsbJw8yOgwvgDCuJD28aYQFnwiggDecCjmAFxwvHAAviLaNpCwcJgArvYYwBD2cAaGABRgZv0rRi0WAJRwncVwaEvm8N29A-XgS-GCvk9EFyMScJut5hQlAPS-cAAAgkALQTJAYMFsaAnIgwGZQZbcW6NeJHJ6+F4wYZwX5jcjDIA)

**Comment by weswigham** [comment]
https://github.com/microsoft/TypeScript/issues/41616 ?

**Comment by lazytype** [comment]
> #41616 ?

Looks fixed in nightly (v4.2.0-dev.20201120) to me 👍

**Comment by hannahjin** [comment]
I am still seeing the same error when using `v4.2.0-dev.20201120` with `React.DetailedHTMLProps<React.HTMLAttributes<T>, T>`

```
import * as React from 'react';
...

export const TextDisplay1 = React.memo(function TextDisplay1<T extends HTMLElement>({
  as: Tag,
  children,
  color,
  display,
  textAlign = 'start',
  noWrap = false,
  tnum = false,
  ...props
}: TextProps<HTMLTextTags> & Omit<React.DetailedHTMLProps<React.HTMLAttributes<T>, T>, 'className' | 'style'>): JSX.Element {
  return (
    <Tag
      {...props}
      style={{ ... }}
      className={...}
    >
      {children}
    </Tag>
  );
});
```

One curious observation is that I don't see the error in vscode but only when running tsc.

tsconfig.json
```
  "compilerOptions": {
    "strict": true,
    "allowJs": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "skipLibCheck": true,
    "lib": ["dom", "esnext"],
    "jsx": "react",
    "sourceMap": true,
    "forceConsistentCasingInFileNames": true,
    "allowSyntheticDefaultImports": true,
    "module": "CommonJS",
    "target": "ES6",
 }
```

**Comment by lazytype** [comment]
I'll leave this open for @weswigham to verify the above issue and close again if need be

**Comment by weswigham** [comment]
Yeah, I can't repro this on the latest versions of TS given what @hannahjin has shared - you sure you have an updated command line version of tsc? The `vscode` nightly tsc plugin isn't going to upgrade your command line version - you manage that yourself.
