### ISSUE TITLE
Many errors on JSDoc use entire tag as errorNode

### ISSUE THREAD

**Issue by sandersn** [microsoft/TypeScript#41974]
This is made more obvious by #41877, which corrects the spans of tags to their full spans, making the error spans even more ungainly. Here's one example; see the errors.txt diffs in the linked PR for more.

**Expected behavior:**

```ts
    /** @type {Gioconda} */
        ~~~~~~~~~~~~~~~~ // before #41877
        ~~~~~~~~~~~~~~~~~ // after #41877 (both are wrong)
!!! error TS8030: The type of a function declaration must match the function's signature.
    function monaLisa(sb) {
        return typeof sb === 'string' ? 1 : 2;
    }
```

**Actual behavior:**

```ts
    /** @type {Gioconda} */
               ~~~~~~~~
!!! error TS8030: The type of a function declaration must match the function's signature.
    function monaLisa(sb) {
        return typeof sb === 'string' ? 1 : 2;
    }
```

**Comment by Kingwl** [comment]
BTW: What's 'PursuitFellowship' meaning....

**Comment by sandersn** [comment]
@Kingwl the TS team is running a workshop with [the Pursuit Fellowship](https://www.pursuit.org/fellowship) today, and we're going to work through the contribution process using this bug (among others).

**Comment by a-tarasyuk** [comment]
@sandersn Does this mean that issues labeled with "PursuitFellowship" should not be considered for external contributors?

**Comment by sandersn** [comment]
Yes, please, at least until tomorrow. But in general, they're simple issues that frequent contributors like you and @Kingwl should leave to new people.

**Comment by chenjigeng** [comment]
Has this been fixed?

**Comment by sandersn** [comment]
@DanielRosenwasser points out that the error message in the example is not very good, and should maybe have a related span:

> This error still is a little strange because it doesn't actually highlight the function declaration itself. You'd think it would switch to that with a "the signature is declared here.

@chenjigeng The first bad error span is fixed; the other two are not.

**Comment by andrewbranch** [comment]
The other baselines that still show errors are (at least):

- tests/baselines/reference/jsDeclarationsParameterTagReusesInputNodeInEmit1.errors.txt
- tests/baselines/reference/jsdocImportTypeNodeNamespace.errors.txt
- tests/baselines/reference/jsdocTypeTagCast.errors.txt 
- tests/baselines/reference/unusedTypeParameters_templateTag.errors.txt
- tests/baselines/reference/unusedTypeParameters_templateTag2.errors.txt 
- tests/baselines/reference/enumTagCircularReference.errors.txt
