### ISSUE TITLE
`declarationMap` causing incremental builds to crash on version 4+

### ISSUE THREAD

**Issue by moshest** [microsoft/TypeScript#44335]
# Bug Report

I'm getting a crash every time I change a `.ts` file. 

This happen where `.tsbuildinfo` exists and `declarationMap` is set on true. Looks like the compiler don't expect to see a `.d.ts.map` before `.d.ts` file and throwing an error.

### 🔎 Search Terms

Debug Failure. False expression: File extension for signature expected to be dts

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions 3.7.7 and 4.3.2

The crash will NOT happen if I disable `declarationMap`.

Deleting `.tsbuildinfo` will solve the problem until the next change (ie. build only the current version).

### 💻 Code

Prblematic `.tsbuildinfo` file: https://pastebin.com/rtCNGBmr

tsconfig settings:

```json
{
  "compilerOptions": {
    "target": "es2020",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "module": "es2020",
    "composite": true,
    "resolveJsonModule": true,
    "declaration": true,
    "strict": true,
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "moduleResolution": "node",
    "isolatedModules": true,
    "jsx": "react",
    "declarationMap": true,
    "noImplicitReturns": true,
    "pretty": true,
    "sourceMap": true,
    "inlineSources": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictBindCallApply": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "noImplicitThis": true,
    "noEmit": false,
   "baseUrl": "src",
    "rootDir": "src",
    "outDir": "lib",
    "paths": {
      "@/*": ["./*"]
    }
  },
  "include": ["src"],
  "exclude": ["node_modules"]
}
```

### 🙁 Actual behavior

Crashing with the following error:
```
/Users/moshe/git/anytrack/anytrack-services/node_modules/typescript/lib/typescript.js:2479
            throw e;
            ^

Error: Debug Failure. False expression: File extension for signature expected to be dts
Verbose Debug Information: Found: .map for /.../packages/config/lib/index.d.ts.map:: All output files: ["/.../packages/config/lib/index.d.ts.map","/.../packages/config/lib/index.d.ts"]
    at updateShapeSignature (/.../node_modules/typescript/lib/typescript.js:112516:30)
    at Object.getFilesAffectedBy (/.../node_modules/typescript/lib/typescript.js:112470:18)
    at getNextAffectedFile (/.../node_modules/typescript/lib/typescript.js:112943:51)
    at getSemanticDiagnosticsOfNextAffectedFile (/.../node_modules/typescript/lib/typescript.js:113567:32)
    at Object.getSemanticDiagnostics (/.../node_modules/typescript/lib/typescript.js:113612:20)
    at getSemanticDiagnostics (/.../node_modules/typescript/lib/typescript.js:116910:62)
    at executeSteps (/.../node_modules/typescript/lib/typescript.js:117051:25)
    at Object.done (/.../node_modules/typescript/lib/typescript.js:116856:13)
    at build (/.../node_modules/typescript/lib/typescript.js:117523:32)
    at Object.build (/.../node_modules/typescript/lib/typescript.js:117705:101)
```
### 🙂 Expected behavior

Build project without any crash.

**Comment by sheetalkamat** [comment]
This is already fixed by #43205

**Comment by moshest** [comment]
@sheetalkamat Thanks!

It's still crashing on 4.3.2, will it release on the next patch or minor version?

**Comment by gasnier** [comment]
I also have this problem in 4.2.4 and 4.3.2
I had no problem before today, I can't tell what was the trigger for this behavior.
I have disabled declarationMap and cleared the tsbuildinfo files for now.

**Comment by sheetalkamat** [comment]
Please provide complete repro as a simple repro doesnt repro on simple project with declarationMap enabled.

**Comment by gasnier** [comment]
I won't have time to prepare this in the next days / weeks.
On my side this is not critical since I don't really need the declaration maps.

**Comment by moshest** [comment]
I play with it more and I couldn't reproduce on a simple project as well. 

Maybe it's related to a more complex projects that reference other projects? @gasnier

**Comment by unstubbable** [comment]
I also tried to reproduce the issue, and couldn't at first. I used a simple monorepo with project references and `declarationMap` set to `true`. But when adding `ttypescript` the issue occurred. Specifically in https://github.com/microsoft/TypeScript/blob/663b19fe4a7c4d4ddaa61aedadd28da06acd27b6/src/compiler/builderState.ts#L337 the `outputFiles` array contains the `.d.ts.map` file as first item and the `.d.ts` file as second item. Therefore the assertion`fileExtensionIs(firstDts.name, Extension.Dts)` fails.
