### ISSUE TITLE
Comma Operator breaks Assertion Functions

### ISSUE THREAD

**Issue by pushkine** [microsoft/TypeScript#44487]
# Bug Report

### 🕗 Version & Regression Information

ts stable & nightly

### ⏯ Playground Link

[Playground Link](https://www.typescriptlang.org/play?ssl=7&ssc=2&pln=1&pc=1#code/GYVwdgxgLglg9mABAOQIYCd1wO4B4AqAfABQBuqANiAKYBciqYAngJT2oDOH16UHi5KtUQx++RAG8AvgCgZoSLASIo1DlGLA4cdswA0iAEYZdrSTMSWUGLHjAgAtoZ4ktcFgbSYcudehhgAOYkxugsANwWVm7hiAD0cYhu9PZOPJFWRhixCVnoppFSQA)
    
### 💻 Code

```ts
function Narrow<T>(value: any): asserts value is T {}

function test(foo: any, bar: any) {
    Narrow<number>(foo), Narrow<string>(bar);
    foo; // foo: number;
    bar; // bar: any;
}
```

### 🙁 Actual behavior

`foo` is asserted as `number`, `bar` is asserted as  `string`. 
The type of `foo` becomes `number`, but the type of `bar` is still `any`.

### 🙂 Expected behavior

Type of `bar` to be narrowed to `string`.

**Comment by MartinJohns** [comment]
Related issue: #41264

Tho I see no reason why you couldn't just use a semicolon instead.

**Comment by fatcerberus** [comment]
According to https://github.com/microsoft/TypeScript/pull/41312 this should be fixed already?

**Comment by jakebailey** [comment]
Just to note it since it's been a few months and I'm about to look a this; the bug is still present in 4.6.0-dev.20211130, so wasn't fixed by #41312.
