### ISSUE TITLE
Arguments to callback prop of generic React component are not inferred

### ISSUE THREAD

**Issue by Mesoptier** [microsoft/TypeScript#44596]
# Bug Report

### 🔎 Search Terms

react, polymorphic components, generic components, type inference on function arguments

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about type inference on function arguments

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4BYAKCpgE8wk4AFHMAZwB4AVOJADxhIAdgBM2iYjAB0AUQA2SEMJhd6SAHxwAvFThwA3nBRsAXHB4BfOADI4AeRDAYHZOmkBhXJCHKWEdgDqTgAWEACuMMiY3OoANATG+OoU1JQiSGhyKERwmGFCGMAQQnAAQhEwxdy8AsJiEm6yCkpCKmrqABRgrKbMPTEAlGYAUgDKABpNisopVAD0c3AAqmzAQgDmZRXFRuKuGHBoXsXKcB1rgqJIInBhbIxoxkhDVPOLdgDSZlzBjHQMcAgmDgAANyjBKkIQXBgOIQXkCjAiiVwZCOAAiABG2yE6M63X8vT87Ax2IhxTxQzgY0m8mmrWhazgMGCsJhQjYMBQBSQUioHFRxV0uy0WJx6OFC3sX3Mv2ZakBwJBxXccmAaAA1oy4R0aUYIVBgGTnoChKr1RqAPxmfbSACy4XuMgAbsoABLckQKKAcN1cO0AGUFQjpLRgmgAPrcrpg1tcQXzKHopQA5Ow8T7fOX-RhA0FIbWg7m0aHncBqtBOOS0AaJvQqisarT6DomrSaQxHDkQBRSOQQdatgakOAWCzzZKvShSlZrTbB3ZwIjrMJZKC5fKFHYdNgoJQwthsMLPExTqWZ2V-BV5sE4wvwzdInbB0ni-E9MzEzhi8m49RUmkpjDRkShZNk1k5bk0F5Khgw6fRhWMMx8DJSF8FiSV3hlH4rwBG8Gwte8ulYJBYBrU1zU1a0GgwKQHTuJAXXdT1vV9f0gxxUNlEjaN0ljHwRATTC4DTDNsOza8lQLA8iyEEszlAMAKyrGs6woxszCHbQO0OYo2B7Xl+0HZ4RwsDDKAsYcqCAA)

### 💻 Code

```tsx
import React from 'react';

type Props<T extends React.ElementType> =
  { as: T } & Omit<React.ComponentPropsWithoutRef<T>, 'as'>;

declare function Button<T extends React.ElementType>(props: Props<T>): JSX.Element;

// Using Button as React component (intended use case):

// OK: The type of `Button` is `function Button<"button">(props: Props<"button">): JSX.Element` in this instance.
<Button
  as="button"
  // OK: The type of `onClick` is `(JSX attribute) onClick?: React.MouseEventHandler<HTMLButtonElement> | undefined`.
  // NOT OK: The type of `e` is `any` (implicitly).
  onClick={(e) => { console.log(e); }}
/>;

// Using Button as regular function (same issue):

// OK: The type of `Button` is `function Button<"button">(props: Props<"button">): JSX.Element` in this instance.
Button({
  as: 'button',
  // OK: The type of `onClick` is `(property) onClick?: React.MouseEventHandler<HTMLButtonElement> | undefined`.
  // NOT OK: The type of `e` is `any` (implicitly).
  onClick: (e) => { console.log(e); },
});
```

### 🙁 Actual behavior

The argument `e` to the callback function provided to `onClick` implicitly has `any` type.

### 🙂 Expected behavior

I would expect the checker to know that the type of `e` can only be `React.MouseEvent<HTMLButtonElement, MouseEvent>`. 

The checker seems to know that the type of the `onClick` callback is `React.MouseEventHandler<HTMLButtonElement>`, which in turn resolves to `(event: React.MouseEvent<HTMLButtonElement, MouseEvent>) => void`. So I would expect the checker to be able to use that information to determine the type of `e` / `event`.

**Comment by Mesoptier** [comment]
I've looked into this some more. If I make the `onClick` prop required (i.e. remove the ` | undefined`), the inference starts working correctly. However, this is obviously not desirable, since the `onClick` prop is optional for a reason.

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4BYAKCpgE8wk4BZFAayWQEcBXYIgEwA8AFQA0cANIA+OAF5JcJAA8YSAHb8AznHa0ImOMLgB+OAHkQwGCPHS4AMkRIefJEIAKwNKxuSpMgC5DCmpKOgY4dxwwTRFFFXUtJ3QYADoAUQAbJBB1GGF6JBlZKjg4AG84FE0gowBfB2Y2DmdeAUELK0FkFNSAYVxINTyoiBiAdSsACwhuGGRMESlxfGr8ZYIINT7Mr1Z1kKp+JDRMlCI4TG41DGAtuAAhOZgtuOVVDW0ejAzs3LV8oUpAAKMDRGqRcFLACUQQAUgBlAAavxyeUOlAA9Ji4ABVTTANQAc0ez3u1WSGDgaEGWzycGBhI+x34cG4mkYaGqSFhVCo2PMElqU0Y4UY+jgAAMnjAXmpJXBgNpJVcbjA7mpSbLXgAiABGZLUOpBYLGENGMUE+sNxthcERKKyaIBCsJcBgUyVirUmhgKBuSFSVEEMrlpSqmlk1u1RvDArMQsMIvdhTgEslWx2e1dyuBDqqsqgwANqmhae2u28QW+aSYsw56QAbnkABL+-jZKCCFvCJgAGVDWyd-xgUklQcoZXjieEybFaYMkqQOaloPOKFyqigZaQ1eItfrSCbeW7vYHhuHeXEdfZR+bALHE7KmcrrFk5WBPLkMkqNJ9EGyVJMggIlP2hUg4DqOp+SkDEBXxQkSUHTUKSIIluDOKBLmuW57mBTQN0YJVNG4HkAj5LEcQTYVRVTdNkJXFUcPVe5kKtEs5WNUFwSCC1YmjTipDtB1URHV1NQ9L1CV9f00EDKhkOBcpw2qIJ8A4rZ8FEOMqJnOc6MXF9s0VXNTQYWBaDLIyq0pA9b2PAE2w0TtT37ZDLwfccdMFGiUwidNlxM1cwHXTckG3RQ916G8G3vawezci8-ivZhDwc0dJXDazWCCMDvwqaktk0ADA2A0CeQguptMoOpwKoIA)

```tsx
import React from 'react';

type MakeRequired<T, K> = K extends keyof T ? Omit<T, K> & Required<Pick<T, K>> : T;

type Props<T extends React.ElementType> =
  { as: T } & MakeRequired<Omit<React.ComponentPropsWithoutRef<T>, 'as'>, 'onClick'>;

declare function Button<T extends React.ElementType>(props: Props<T>): JSX.Element;

// Using Button as React component (intended use case):

// OK: The type of `Button` is `function Button<"button">(props: Props<"button">): JSX.Element` in this instance.
<Button
  as="button"
  // OK: The type of `onClick` is `(JSX attribute) onClick: React.MouseEventHandler<HTMLButtonElement>`.
  // OK: The type of `e` is `(parameter) e: React.MouseEvent<HTMLButtonElement, MouseEvent>`.
  onClick={(e) => { console.log(e); }}
/>;

// Using Button as regular function (same issue):

// OK: The type of `Button` is `function Button<"button">(props: Props<"button">): JSX.Element` in this instance.
Button({
  as: 'button',
  // OK: The type of `onClick` is `(property) onClick: React.MouseEventHandler<HTMLButtonElement>`.
  // OK: The type of `e` is `(parameter) e: React.MouseEvent<HTMLButtonElement, MouseEvent>`
  onClick: (e) => { console.log(e); },
});
```

**Comment by RyanCavanaugh** [comment]
We can take a look earlier if someone can remove the `react` dependency from the repro, since it's entirely possible there's something in the definition that causes this per expected behavior.

**Comment by Mesoptier** [comment]
After reading your comment I also searched through the issue tracker on DefinitelyTyped. There I found this issue for `@types/react` which looks similar to what I'm describing: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/50459. According to that, this might an issue with the React typings. However, I'll continue trying to reproduce the issue without the `react` dependency.

**Comment by Mesoptier** [comment]
I've altered my original code sample to no longer include the `react` dependency. Instead it now includes a few minimal types based on those found in `@types/react`, which is still enough to demonstrate the issue somewhat succinctly. Hopefully this will help in narrowing down on the issue.

[Playground link](https://www.typescriptlang.org/play?#code/PTAEFpNBlAXBDATrUAzeBXAHqASgU3gGMVYBPAB3wGcBYAKAYEsA7WfRdI-UASTcStqTIgFEANvgC2+NtVABvBqFDwAXIuUrQAC0T5UAfg3VYglgHMA3FpUB7FgGFxIgNbHQACnwaAEgBUAWQAZAEEWIh07RAlpWVgASlAAXgA+UAA3OyYAExt6FQBffJUAIwxYWAcNJQLtcioPU3NrW1AHZzcPbz8g4IAhCqqWWJk2JLTM7LytYoZChgYGnlH4xwdmjBJogB4ABXTkr08KRDsKag09ifSAKWgADQA6VfH8pcoVyTHYf0-9lKqFhkQ5aAA+oAA5PBIeCoeVKg5YXUIa9YOsWJttoh9ql3vRlqB1lIKA54nszhcdv5QPgsOwWDl5K58GQ7Kg+AIhCI0fJUd81hszFsqjj4MDUqC6jS6QymaA0RisaKdqxUBxQAc2oZNW0NDL6bJ5Sy2Rz+GZuWIBXI2iodebzMIrXE5ABtfwAXVtoBqc0Y9BAECgokZaEwOAIxFInzo-o+VE1lOo1NphsZ8jRfyoUpUClUl1ANMKoAAZKAAPJSJiwHbE0ksclJ6mpAA0UPg1EheMW9By+CI4iQPFQGAisCYDlAg0RLBTsqNGetv0+qROSauTf8qQSGnuzzR+MDAFVhJYp0NJx28IQSKAiHYSWS2F5WHL8DlQBhqDwiB38Due0DcsAGl9R0HhCXZUAAANp2GaDQCYeRoJHMcJxYc8Zx2AAiBFhmw1dTnOAsKWInC8IcAid1APcXiXBDWFAWAdCQxDMQQCJ8CeBgdjghwtA7ZJcIvFhsK0IDQMLcCmM+doOWgjoXCIVwGOQzw91USpBARf92icJT3A0TwelAAIQj4kYlxuKZciSCFRz7VBWHfaDuLqQMADlyxpECwIg2SoOg-BVJg8UyAQzwmBJJTq3EMgEjc+x9LcZIFG8ay83vTE7EkJ5xDsCx0qsUBCgWANu39Y9TwsTDhnzUB9AsDBB0QNBRxIdCvGoeAZEQ6hqAwf81EAsBfKk-yE0CiyQpQ9rx0nCzyJEgi12IjcyOEmcqN3R46JdWAGIw5jWKEDjuDcizPFqFQOw0SEKJYSEW3E0bJP8aTIPkxS3Bm1aqGQeK9M6ZTuhMsyBhEtFrKyWzQHsxkDGcnJXJe0AvJ8t6PoC+Tgr60LgQiqKKBi2A4oSrRvuUozdMmTKNhyrj8sK-9isKZ76EKBJ8iAA)

Interestingly, if I comment line 19 (`| ElementConstructor<P>`), the issue disappears. 

[Playground link with relevant line commented](https://www.typescriptlang.org/play?#code/PTAEFpNBlAXBDATrUAzeBXAHqASgU3gGMVYBPAB3wGcBYAKAYEsA7WfRdI-UASTcStqTIgFEANvgC2+NtVABvBqFDwAXIuUrQAC0T5UAfg3VYglgHMA3FpUB7FgGFxIgNbHQACnwaAEgBUAWQAZAEEWIh07RAlpWVgASlAAXgA+UAA3OyYAExt6FQBffJUAIwxYWAcNJQLtcioPU3NrW1AHZzcPbz8g4IAhCqqWWJk2JLTM7LytYoZChgYGnlH4xwdmjBJogB4ABXTkr08KRDsKag09ifSAKWgADQA6VfH8pcoVyTHYf0-9lKqFhkQ5aAA+oAA5PBIeCoeVKg5ISVQCBQBDXrB1ixNttEPtUu96MtQOspBQHPE9mcLjt-KB8Fh2CwcvJXPgyHZUHwBEIRJj5BjvmsNmYtlV8fBgalQXV6YzmazQJjsbiJTtWKgOKADm1DDq2hp5UzZEr2ZzufwzHyxMK5G0VPqreZhLa4nIANr+AC6DtANTmjHoaMg4GVLLQmBwBGIpE+dCDHyoOpp1DpDJNLPkmL+VFlKgUqkuoHphVAADJQAB5KRMWA7MkUlhU1N01IAGih8GokMJi3oOXwRHESB4qAwEVgTAcoEGiJY6YVpuzdt+n1SJ1TV1b-lSCQ092emKJaIAqsJLLOhjPu3hCCRQEQ7OTKWwvKxFfgcqAMNQeERu3wfd+zRKsAGkjR0HgSS5UAAAM52GODQCYeQ4PHSdpxYK95x2AAiBFhjwjdTnOYtqTI-DCIcYj91AQ8XlXZDWFAWAdFQlCcQQCJ8CeBgdkQhwtG7ZICOvFg8K0UCIJLKDWM+dpuTgjoXCIVxmLQzxD1USpBARID2icVT3A0TwelAAIQkEkZVxuKZciSCEJ0HVBWC-OC+LqaTIOghTYLg-ANPgyyBnEzEPK0FS3GSBRvDswsnxxOxJCecQ7AsOKrFAQoFmDPsgzPC8LBw4Yi1AfQLAwEdEDQCcSCwrxqHgGQUOoagMCAtQQLAcCfPk5N-OsoL0LqqcZ2sqjxOIzcyO3SixPnWiD0eRj3VgZjsLYjihG47hPOszxahUbsNEhaiWEhdspJ6mT-DkmClKitThpmqhkDIJInpM44fAsvprMxOysgc9EfxZAw3JyCKvJuvqHvgwLWuC-6wqYzz7CMtxTIMyYEo2ZLeLSjKgKyworvoQoEnyIA)

I can see how this might suggest that the issue lies within `@types/react`. However, the fact remains that TypeScript seems to be able to correctly resolve the type of the `onClick` callback (including its `event` argument), but not propagate that information to the type of the actual argument `e` in the provided callback.

**Comment by Mesoptier** [comment]
Looking at [this comment](https://github.com/microsoft/TypeScript/issues/44596#issuecomment-861551208) from earlier, I realised that it probably wasn't the "making the prop required" part of it all that made it work. I removed the `Required<>` utility type, and kept only the `Pick<>` and it still seems to work.

```diff
- type MakeRequired<T, K> = K extends keyof T ? Omit<T, K> & Required<Pick<T, K>> : T;
+ type FixCallback<T, K> = K extends keyof T ? Omit<T, K> & Pick<T, K> : T;
```

More interestingly, applying this fix to the `onClick` handler only will also make the `onBlur` event handler work in the function case, but NOT in the JSX case!

[Playground link](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4BYAKCpgE8wk4AxYADwGEUAbLgI3QDWAHgAqAGjgBpAHxwAvFLhJWMJADsAJgGc4ApLQiY4IuAH44AeRDAYoiTLgAyOAAVgaYeKmyAXMYrUlHQMrjhgWqJKKuraiMQwAHQAolxIIOowIvRIsnJUcHAA3nAoWn4mAL5OzGycPPweQlY2Qsjoiey4kGoZLmFaAOo2ABYQAK4wyJii0hL4pfizBBBq7FzuAosBVBpIaFwoRHCYY2oYwCtwAEITMCuRyqqaOm0YyanpapnZ0gAUYP0-H0IOEZgBKPwAKQAygANd5pDLbSgAehRcAAqlpgGoAObXW6XUpxdpwNBdFYZOC-HFPXYaOBjLSMNClJAQqhUNGWSTlYaMYKMQxwAAGNxgdzUIrgwB0IpOZxgFzUBIl9wARLxCWp1X8ASCyqEDUJNdrdRC4DD4SlEV9pTi4DBhrKZWotDAUGckAkqEJxZL8iUtHJTWqdYHuRZecZ+Y7snBhSKVmsNva5b8rSUJVBgFrVGCE6t1h4-K9EgBZcbMpIANwyAAlPRpUlAhPWROWADL+lY2z4waQin2UAqR6MiWOChNGEVINOi-6HFDpVRQAtIUvxBKVplIWsZNsd7vavsZCQ76t1r6D4cFZPFgRyQq-dnyWTFcluiCpBJcCC4l8wVIOAKgqCN0QAOQsEwoz5AV40TOcZTlT1aCHQMViuLgxigJ9ALfIoyRWLRv29P8APZYDQK5aRkW5LEcXxHsVWJIhcTGA4oGOU5zkuX4tGXRhZS0MZ2R8TlUXRWCY3gkJE2Y+d5R4pVLmYk080lXV-kBI1QVDTTpAtK0EX7e0VSdF0cXdT00G9KhmN+QpA1KPx8A0lZ8DEcCeTguM5Jne9U2Qhd9QYWBaALQKSxJN4Lz3K8YEbTQW0PLtmNPa90JHOAx18qdEMUxcoEE1d103dptyreKD3bNKTw+M84Di-dMtvQsU2i-C5HfIivx-cjAKorzsrHaloVwJBRgAd1MABCC0J1koUZyQl0RSKkqkDXJRyreJgIDQJkWtsWrjzDDKByyu81CwnC-C6nrPxI-r-0GkDhoqICqCAA)

```tsx
import React from 'react';

type FixCallback<T, K> = K extends keyof T ? Omit<T, K> & Pick<T, K> : T;

type Props<T extends React.ElementType> =
  { as: T } & FixCallback<Omit<React.ComponentPropsWithoutRef<T>, 'as'>, 'onClick'>;

declare function Button<T extends React.ElementType>(props: Props<T>): JSX.Element;

// Using Button as React component (intended use case):

// OK: The type of `Button` is `function Button<"button">(props: Props<"button">): JSX.Element` in this instance.
<Button
  as="button"
  // OK: The type of `onClick` is `(JSX attribute) onClick: React.MouseEventHandler<HTMLButtonElement>`.
  // OK: The type of `e` is `(parameter) e: React.MouseEvent<HTMLButtonElement, MouseEvent>`.
  onClick={(e) => { console.log(e); }}
  // NOT OK: The type of `e` is `any`.
  onBlur={(e) => { console.log(e); }}
/>;

// Using Button as regular function (same issue):

// OK: The type of `Button` is `function Button<"button">(props: Props<"button">): JSX.Element` in this instance.
Button({
  as: 'button',
  // OK: The type of `onClick` is `(property) onClick: React.MouseEventHandler<HTMLButtonElement>`.
  // OK: The type of `e` is `(parameter) e: React.MouseEvent<HTMLButtonElement, MouseEvent>`.
  onClick: (e) => { console.log(e); },
  // OK (Somehow?!): The type of `e` is `(parameter) e: React.FocusEvent<HTMLButtonElement>`.
  onBlur: (e) => { console.log(e); },
});
```

**Comment by probablyup** [comment]
@RyanCavanaugh I see that this is marked as backlog. A lot of people in the FE world use this prop inference pattern... would be good to at least target a milestone for fixing it.

**Comment by devanshj** [comment]
> We can take a look earlier if someone can remove the react dependency from the repro, since it's entirely possible there's something in the definition that causes this per expected behavior.

Here's the react free version @RyanCavanaugh asked for. [Playground](https://tsplay.dev/NBeZkw). (Uses react import just for the `JSX.IntrinsicElements` definition).

```ts
import React from "react";

declare const Identity:
  <C extends keyof JSX.IntrinsicElements>
    (props: { as?: C } & JSX.IntrinsicElements[C]) => 
      JSX.Element

<Identity
  as="input"
  onChange={value => {
    // value is any, expected string
  }}
  value="foo" />

Identity({
  as: "input",
  onChange: value => {
    // value is string, expected string
  },
  value: "foo"
})
```

**Comment by Mesoptier** [comment]
> We can take a look earlier if someone can remove the react dependency from the repro, since it's entirely possible there's something in the definition that causes this per expected behavior.

@RyanCavanaugh OK, I now have an _actual_ `react`-free reproduction case for this issue. One thing to note is that I've set TypeScript's JSX option to 'Preserve', to avoid errors from using JSX syntax without a React import.

[Playground link](https://www.typescriptlang.org/play?jsx=1#code/JYOwLgpgTgZghgYwgAgKIBsIFsLgM7IDeAUMsjAPYUBcRyCc66ARogNYD8tAFAG6MBXCLRACszaAEpkAXgB8yXhWAATZAF8A3KWSsotQvUYt2XZH0HDkeMFFABzafMXK1W4uuLEwATwAOKAAKUBR+eAA8AMLIEAAekCAqBGwQPhQwaJg4+AoydHB4ZtHqyABkmdi4YHgA2pEAutoqEAjocFAoMAIgCGDAFCDIACoQNlEx8bhJyClpGRiVOdx+IWG0waERkXKSIgJM2sThIzY6BTIARHoXOgxMrAhsMoQW6EJOCiRkZAD0PxMBXoQFS0XwBdKKSyyay2Bw6X7-RBgASMUH+CAQ-hvFB5OAgHzmYBYPzoYAIYBgdA+STw5B-ZAAOQA8kNkEyANI6dSeH5yQ4nMDcL7IAq0K7tC4AGluxgebB4WPesk+tPpcUBkBByDBGIyipxMLsIHsqsRvRR6DR4L1ULyNiNJu+dP+HK50vUkkOx1GYHCAHI9H65Gc8JdrjL7uxnq8lc5hQiAS1NVbdZDsdD7XCnfSkRaU5jbYas996a6yNziLzNEA)

```typescript jsx
interface Elements {
  foo: { callback?: (value: number) => void };
  bar: { callback?: (value: string) => void };
}

type Props<C extends keyof Elements> = { as?: C } & Elements[C];
declare function Test<C extends keyof Elements>(props: Props<C>): null;

<Test
  as="bar"
  callback={(value) => {
    // expected: typeof value = string
    // actual: typeof value = any (implicitly)
    // NOT OK
  }}
/>;

Test({
  as: "bar",
  callback: (value) => {
    // expected: typeof value = string
    // actual: typeof value = string
    // OK
  },
});

<Test<'bar'>
  as="bar"
  callback={(value) => {
    // expected: typeof value = string
    // actual: typeof value = string
    // OK
  }}
/>;
```

---

It still seems so weird to me that the type of the callback is correct, but the type of the callback parameter is not:

![image](https://user-images.githubusercontent.com/322632/160584506-bcdd5fdf-e75a-49ee-b261-ba1a7e6acf5d.png)
![image](https://user-images.githubusercontent.com/322632/160584697-7c55a94e-44f6-4e13-80b6-ef053f6d3fe1.png)

**Comment by RyanCavanaugh** [comment]
@Mesoptier thanks, that's a great repro

**Comment by MartinJohns** [comment]
https://github.com/microsoft/TypeScript/issues/44596#issuecomment-1081663610 works in 4.8.2, but the original code example by @Mesoptier still does not work.

**Comment by gynekolog** [comment]
The issue in the original code comes with the Omit in the Props definition.
I haven't solution for the issue but [I can share playground link with the original code extended by Props without Omit](https://www.typescriptlang.org/play?ts=4.8.2#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4BYAKCpgE8wk4AFHMAZwB4AVOJADxhIAdgBM2iYjAB0AUQA2SEMJhd6SAHxwAvHADecFGwBccHgF84AMjgB5EMBgdk6aQGFckIcpYR2AdQcACwgAVxhkTG51ABoAIgM2WPUKSjoGZlY2AJhgsIBBNjsHQRFuXgFhMQkXWQUlIRU1TR19QxNzK2qMKXdwCC8Gn38g0PCkSK5kqioRJDQ5FCI4TBChDGB+uAAhMJh+sv5BUXFnbvlFZVUGdQAKMEyTIc5JgEoTACkAZQANWouGlKzeaLRgrNYwDZCba7frZXIwApFGAlA4VY5daTneqNa53B4ZXxZEb5Qr2ZFIUqvD4-P7YlJUAD0DLgAFU2MAhABzaHIzaGDFwNAefrKOA3DlHWYiOAhNiMNCGJBvaaUJm2ADS7UCjDSjAgmDgAAMdryhIa4MBxIawetNia9kIOLEAEYwoRJPGEx6ZJ2u01JN5wL6-LHKc0cuA5S0WoRsGAoNZIKRUDj2-pUOAJLQut2xDNwNU2TWmbWRtRwfVG-quOTANAAa3DVpuwYMyKgwD9SorQhrdfrAH4TKdpABZUJymQAN2UAAkEyIFFAOLOuKOADJpoShhqaAA+MtE4w5FMNycombVADkbDwi1qdeXK4akE2jQnaObxeBa2gHHJaBec9M2rX96y0XQbm7LRNH0IVYwgBQpDkCBOSgl5SDgMwzEZKZqFVZk2Q5bktwSOAiE5EIFigZZVltKEbjYFAlAtNg2BCJUjBVQtiy4UtdQrA1jTdN9rToiE7TdX1c1ue4vQJdhpP9dRA2DWkwxjSNAmjDk4wTNAkyoLcbl0fM2gIP0HXwaJ8x4h8y3SZ9QP7UTPQYWBAJ7PsGyHDEpHHWUkGnOcFyXFc103N0dxgfdD1mTATxEM9bOZG8714-inyE19WPfIRPzFUAwF-f9AOArywJMdDtFgwV+jYRCkxQtClUwswbMoMwMJVRlmThUY4FiQx4lwYoKRTLd+pJJESjMths0s-o8wvCr+wg6qYL0OqEKQ5r0LanDVTwoy3SmhFSTGkQTLmkx8EWoRrPzZyGyq6DavghrdtQ-asI6rqUiAA).

**Comment by cristatus** [comment]
I fixed my issue like this:

```tsx
import React from 'react'

interface AsComponent<P, E extends React.ElementType<P>> {
  (props: React.ComponentProps<E>): JSX.Element | null;
  <As extends React.ElementType<P> = E>(props: { as?: As } & React.ComponentProps<As>): JSX.Element | null
}

declare const Button: AsComponent<{}, "button">

export const Test = () => {
  return (
    <div>
      <Button onClick={e => { }}>Button</Button>
      <Button onClick={e => { }} as="a">Link</Button>
    </div>
  )
}
```
See the [playground link](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wChTgA7GJKTdJOAQQGcBhXSSpagHgAUANHACicJAA8alACYtExGADoRAGyQgeMACoBPMEgEA+I3ADepOHAAUYHGBYAuBemUdwEbtX72WvEUYAlM4AUgDKABoq6prUcAA+cJQArqqqANyWcLys4lI8ci4Y0RpaegbGcAC8oka2vs5mcCgsAPzOuQC+cABkRW6cnlo+EA45LEGhkSWx8IkpaaSd5DJIaKooRHBonizwAELJMDCeHeyDXjC8Zp3CAEQARkcnlHdG5JKQsNu78NpIe2qNkC1VMFisRBgySglBsWSsvBkwAAbu8rOjsodjp44J42KpgGgANZVMyMKpguCdTpGLEvXgAejpnjRGMxzxxeIJxNJ5Mp1OaLCqdxQbwAMlQiYzmZRWQiGUjUVlAksgA).

So the issue seems to be associated with type inference when some of the type parameters are omitted?

**Comment by corbanbrook** [comment]
I have been playing around with building a polymorphic box component which takes native html props as well as atomic class names from vanilla-extract sprinkles.

```jsx
  <Box display="flex" borderWidth="thick" />
```

Which can also use as:

```jsx
  <Box as="input" type="email" /> 
  <Box as={Link} to="/home" /> // react-router-dom link
  ```

I came up against the problem of event handlers not typing the event properly and like others have noted here it is related to using types like `Omit`,`Pick`, `ComponentPropsWithRef` on your type. With some massaging I was able to get it to work.

You may have noticed that `ComponentPropsWithoutRef` seems to work fine, but `ComponentPropsWithRef` breaks when used on the top level of your type. So the below example uses and intersection of `{ref?: Ref<ComponentPropsWithRef<T>['ref']>  | null}` to get around the issues mentioned above.  

```jsx
type BoxProps<T extends ElementType = 'div'> =
    ComponentPropsWithoutRef<T> & {
        as?: T
        ref?: Ref<ComponentPropsWithRef<T>['ref']> | null
    }
```

This example is largely based on the original types from the react-polymorphic-box  lib.

[playground link](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAJQKYEMDGMA0cDec1SoxICiANkiEgHZZwBm0A7ilACbL3bmU0wAqATzBJsAYQjgI1PgAUoEMAGcA6sBgALTuMmQZteYtXqNEAK4xtiJF2voYPKrWzJ7AOQhskcAL4MFIHAA5IT2QQDcAFCRAPQxcACCMJLAaPhKSvhkKBlImZHAtEhQ9OjeSZKZOJFwtXBswEpg2YIA-ABcwYVkhUhBcAA+wQBGZBBoANb9Q0HdvQC0o+NTg8H0FAAe08EA5lDAbEE1dUwHmh3BKBYQ20H0ZmRkR3VwGkjAOxowF0FXybf3R7POrDaBeKAIFANMxKH5KEC3ECHVZBMg7W5oYBQNAUYG1UHsYpqNjnTpBTSFW4UyZ4uBgKENag7OEIlFI25o2kgVg7QosxHImac461OK1JAwNAAOilkR80TFYhQ1GoEHgMO8Eik+hghmUak0nDg0jgyTAcAoADckGQ4MMLHAmN40NIlDAoGYMHAUKbhN4mBpUho4IUcWYvJlNN5CPRTYHMixBJEYH64AAhCAbPVKAA8-DgSA2xGobEyjj4QhEcAAvMEGpaggA+GsiuBavRyBT6kzmSw2PPNgBkuFbLxyF34o7qMYunBz7eknaMBq0-f4jYA2iEbEEALrNobUB62xW6RcGLvGQ02OAatgh6hKA7eRoMXqtvzDiogJTRFNV2QIDIQQQGgMBAzQbMc1kbB80LYtSzgctaErJBm1rWQ4GHDMs0vAc-1TQDgNAqBwNSBcdWg7AABECyLGhEOQgRU1rIJ6ybGs4DzOiELLCgnGYqta2oxsAAowEvToiJAsCIKgmC4HXABKGtG1bVwMCY1Yj0eAiAKAmTSIguc4Poks+N4FCWLrYAG3Q9NMyg9ctxjPdoi8HFWGdV14BxJQNk6USZSlTyMjcFAqCUTo3X2JkN13FTq2bGLCh2SIPOyQh8B871kh-To8AkxRihgYA8gK14ckCiYkEEaL3VSxLm1BIDUGoXwOuHUTxMk3A4A3ABpB84BqwQIFjb8lF3TpJsG3cfCauAUqZJTohdR94BwqSDJIsi0AovgcxwHxsDY2yONrRgoBYdhOFE45uPghiLIE1CxKK5ROhwpzG2wGNOjnAAJfgAFkABkmMbRbqheda3T6nJOLOhtsFCpRwqobBgsIN1sw62sPt-WGcpQPLswBpAXXYHNlp2bAzGoCZVSYah7OO1s4fgahSdspByesKm2BphqmXpxnmdZzj2dbK64FEzmRtq4acd1S8VJhl4Q1jUTScqKUPpKsqlClDQclE0bvUyUbxsSPKlCU9Wp1qXWQGzDdRt3TiVbdi3Eet2N-yQG3vcvXcpz8G0lG8DXNbgbnSutH3as92sQ6Md2lb92qbcD4O8lVoww9j+UXnlDmSby8jslyTJaxdpRRJjupgpd7MP1W1tCBgMwoHaggiFIfi+B1pRsCb2o0YxpBOj8jYdcr-bq6j0eshydGIqQJTMCnYL4957Nt9jmN2+OeUO7FEgNgi5pvO1PhMjvYbiHhtAcjyO0bQgJhIgVsHCgmTiPUjAVWSPVWKOxwj4EDGQNghBqCzlQBgDwXhfDQ07hKHu7VRI5h9BoGM1YABEABiAhxpqBiB6JMasOBRKLThq1KUYwdhAOUFKZISkfBqVjrUHAhMQrQNgTQEudQcwxBQFDOUelvBpgsMkageNaxN0tKwYAypvhkgkqAVgghbiqigNyJ4rYnwAC8kD8jZIKYIwoXjZGGDaMBqVJGxHiDImAcjsp31oI6EwDBmCsA4DYH+OVXFyO2sRWS5EzyURCdIA+IxZHSAur466-i7qtkemZRiQ8rIiHer1aSu05J4RifIy8sFfpwH+nAApES0AmShqpEcxMNoI1rvEtxiTsDKP2GopGeiDFBGwCY7wtYCFIgIdgWxNosYyhVvjOkl5ogvC7pguW6ScKW2oTkPwk8N7UO6aorxABqJawBTF+HwTgGMfgcDY3zpwp2uAplkGEbUUROEuF1FWgtBU8R+D5zbG-X8Ct-lujabQxp90Xg5k+aKeIAABGASh5iFhEBgFFUAFBQDgPMOAAADPBNg8UhkyKqeAPplE9HvB9ZJXRqBgAsLSHMGyciEMKAymApDCX0EIaQmIsK4DrMzJsgh7KLCkMDoQ4gRY+VqSFRsEVKBSHSAoakCY1CkCWkaZqvw-K4CnkxZTGAwFfQiEyJqmglUSwUCgL+VsYpEXItRUajFWKcX4r4MUAatVAaFBgMSkAMJ4B2O9HASlBww0oDIGYJA8qRVis5QWIoUBvWCF9bQQhGgzAaFlUskRLKlBsvpeKpNxAU0+r9YQqOrA0A5v1XK6FJSLQoDsWQQhgMbRjFIQctRhDNHcigIIUhlyYyNOufyvNcK4COpRRsNFMBXXQHdQSmMGxiWvjJaG8N1Kuy0rxSgPFcbWUEKVa8VdhCYimCoLm+1CKkWzvnYu7FuKV1ErgIG+GIafS0yPYWk9XLLkAFZdUNvzcK49p7uUXqvUgG9LwHX3udei4obqX3JHXZkEAjRUr+EkPiv+jND2NvA4WnABGJicMBpIJA7zMyganTOpDC6UNLpfdyjDcc1RbqjRGmlss8XkaI2BhVrKyP-z8FBghl7qMEMbFRqgtGNj0a4gW6h5G-DJGgzJuT1HFPKYQ06udLqWPPvxQ0JoLQ10ks4+SyNVKloKo+kJt5GzzPNBQIIDYhCliTDg3UMUnAibCcqTYaho6kohfoCB39hDT0jpvBF659aYuiuLYm+LsZEs2Gi8RkTpH1OmggFp69kWwsJebElvVYpR2vgZkzL+1BJ0qYSe1CDAHQtSbeI8CApDnnts7T1shqqqE0M1YtHVyXb3TsQ0Z5DmLWP4vQ9ZrDGQcP0ACHAQT6yWubLE4zPwfWCEdu635lzO3RMFc051gbvWW02n6yd5L0KJ1KSAA)

**Comment by sscaff1** [comment]
@gynekolog  I'm not omitting any props, but I do want to set a default for the ElementType and apparently that causes the issue again.

Here is your snippet with as an optional prop [Link](https://www.typescriptlang.org/play?ts=4.8.2#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4BYAKCpgE8wk4AFHMAZwB4AVOJADxhIAdgBM2iYjAB0AUQA2SEMJhd6SAHxwAvHADecFGwBccHgF84AMjgB5EMBgdk6aQGFckIcpYR2AdQcACwgAVxhkTG51ABoAIgM2WPUKSjoGZlY2AJhgsIBBNjsHQRFuXgFhMQkXWQUlIRU1bQIAIzCYCCF8TR19QwB+E3Mraowpd3BO70zs3PCkSK5kqioRJDQ5FCI4TBChDGBOuAAhds6y-kFRcWcx+UVlVQZ1AAowTJMfdiiAShMAKQAygANWoPBopNYbLaMXb7GCHIQnM5CWahGAFIowEoXCrXUbSe71RrPN4fDK+LJBdGY+zYpClJZ-OBA0FE5QpKgAei5cAAqmxgEIAObI7FHQwEuBoDxTBpwF5Cq5rERwEJsRhoQxIP4rSg82wAaSGgUYaUYEEwcAABqdxUJrXBgOJrXCDkc7R0hBxYm17UkyZTPpkfX6vUlmaywcTHUK4DlnU6hGwYCh9kgpFQOJ7OlQ4AktL6UbE83ADTZjaZTfGmpabZ1XHJgGgANaxl0vVkGbFQYB+nVwBtN1uDAlSACyoQ1MgAbsoABJpkQKKAcedcccAGRzQnZDU0AB81aIFkKGdbM5R8waAHI2HgVk1m2tW61Ids2tO0R2K8DDhxyLQPyXvmQ7Ni2Wi6C8A5aJo+gysmEAKFIcgQMK0E-KQcBmGY3LLNQ+q8gKQqijuCRwEQwohJsUA7Hs7pIi8bAoEoTpsGwIQ6kYerlpWXDVuag6vjuH6uvRCIeiiobFq87xBhS3xFv66iRiC0bKLGSIJuIQopmmaAZlQO4vLopaGCY+Bhp0+DRKWvFPjW6R1taYGtqJgYMLAQGDkIjbgaOtzSJO6pILOC5Liua4btuKJ7jAh7HmsmBniIF52byd4PnxAkvja75sZ+QjfgqoBgP+MCAcBpauS2JgYdocHSp0bBIRmqHoTqWFmLZlBmJhercryaJhHAsSGPEuDFAyWY7sNGKFHSJTVb5w4QVBMGNQhLXIe1GFdbh+r4UZKJzbSU0iCZy1+a2dUbXoTWITtaF7dhPV9SkQA)

Again it knows the type of the onClick, but it says the event is any. What's strange is that this is the same thing:

https://codesandbox.io/s/intelligent-marco-qdfwy4?file=/src/App.tsx

And yet codesandbox doesn't complain. When I try to do the same thing in a CRA project, I get the implicit any error as well.

**Comment by cristatus** [comment]
The issue is because of `ElementType` without any given parameter as it's type parameter defaults to `any`. See my last comment how I fixed it.

**Comment by sscaff1** [comment]
I simplified your example and it still appears to work [Link](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAJQKYEMDGMA0cDecCiANkiEgHYwAqAnmEtgMITgRnkwAKUEYAzgOrAYACwgBXGMgBmcAL5wp3EHADkUVBhUAoHTFpI4AQV5MWbCgB58cJAA8Y5ACa8CxUhRp0AfHAC8cLTg4C2MbeycXIhJ2TwN-fC8ACjBuPgAuXDgUXgB+DND5ADI4U0hzTlSBIVEJaRDeLwBKPx8AKQBlAA0AOij3GABuHUckNEIUdTg0Vl54ACEJGFZ8k2Yy9gsAIgAjRdZNrx07SFgpmfhKJFm-OETm3x8cQLh1GDEoMlvnoItHYAA3Q5BYHBBYwJafVgMQjANAAa18ODijzksi8YIhFgA9BjWECQaC9pCyNDYQikS1MrJ5NlfJsUAcADLAMhw7G4sj4n5Yv6A56NLSyIA)

What's strange is that if I paste my example, it also seems to work... [I'm not sure what's going on.](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAJQKYEMDGMA0cDecDCE4EAdkiTAApQRgDOA6sDABYQCuMyAZtgKIAbJCHIwAKgE8wSOAF843GiDgAiKKgwqA3ACgdwCkijd0MgJIAhTjFLVadADxi4SAB4xyAEzpxBw0ZLSAHy4OnBwaESQZBQA-ABccM4APqoARtak2jqyejBSMgCyEoTEMVQ09E4u7l4+fiIUgUghALxwlpkkdlViIQBkYQRRpKI9jMxsnDxOQbo63OwkGMCkcMWl0aLVbh4k3r5CjeIFcO0qGTA2JCpBABQ4Q5FlooliKADmZ+ldKphDADogWBKnQcokNiNyuNZgBKULhdQwdhQEhwJyfXBAgEg+zyAD0cxyejckFgcE8SBM7AE8EWyxgqzRAEEwGA7vDHoikMjUXA7kNwg5PMAAG4RAQoOh0AByKBErRUrLAt0F4XRLAAjEEABJIAQCCDDSkAZRQ+zSEFcDnxWqCaqFLAATEETTAUOSkCLGSQvjY4HQkDI6EQZCBPsA0HAWCg2eQAIQ25329Xq4VilOptOQl4UOCkfACSMAa1aODuSHhrRCkRIIaEAMNHwrsNkQSsV1INpzWwomdTNpFov7aaHI4HPdGeeevZgipQKnzJELJbLLbONdI9aQjYgzcrbYdWYAMgZi0ehfjJ+Vx+j8WO1YOM0NYbpckA)

**Comment by cristatus** [comment]
> I simplified your example and it still appears to work [Link](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAJQKYEMDGMA0cDecCiANkiEgHYwAqAnmEtgMITgRnkwAKUEYAzgOrAYACwgBXGMgBmcAL5wp3EHADkUVBhUAoHTFpI4AQV5MWbCgB58cJAA8Y5ACa8CxUhRp0AfHAC8cLTg4C2MbeycXIhJ2TwN-fC8ACjBuPgAuXDgUXgB+DND5ADI4U0hzTlSBIVEJaRDeLwBKPx8AKQBlAA0AOij3GABuHUckNEIUdTg0Vl54ACEJGFZ8k2Yy9gsAIgAjRdZNrx07SFgpmfhKJFm-OETm3x8cQLh1GDEoMlvnoItHYAA3Q5BYHBBYwJafVgMQjANAAa18ODijzksi8YIhFgA9BjWECQaC9pCyNDYQikS1MrJ5NlfJsUAcADLAMhw7G4sj4n5Yv6A56NLSyIA)
> 
> What's strange is that if I paste my example, it also seems to work... [I'm not sure what's going on.](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAJQKYEMDGMA0cDecDCE4EAdkiTAApQRgDOA6sDABYQCuMyAZtgKIAbJCHIwAKgE8wSOAF843GiDgAiKKgwqA3ACgdwCkijd0MgJIAhTjFLVadADxi4SAB4xyAEzpxBw0ZLSAHy4OnBwaESQZBQA-ABccM4APqoARtak2jqyejBSMgCyEoTEMVQ09E4u7l4+fiIUgUghALxwlpkkdlViIQBkYQRRpKI9jMxsnDxOQbo63OwkGMCkcMWl0aLVbh4k3r5CjeIFcO0qGTA2JCpBABQ4Q5FlooliKADmZ+ldKphDADogWBKnQcokNiNyuNZgBKULhdQwdhQEhwJyfXBAgEg+zyAD0cxyejckFgcE8SBM7AE8EWyxgqzRAEEwGA7vDHoikMjUXA7kNwg5PMAAG4RAQoOh0AByKBErRUrLAt0F4XRLAAjEEABJIAQCCDDSkAZRQ+zSEFcDnxWqCaqFLAATEETTAUOSkCLGSQvjY4HQkDI6EQZCBPsA0HAWCg2eQAIQ25329Xq4VilOptOQl4UOCkfACSMAa1aODuSHhrRCkRIIaEAMNHwrsNkQSsV1INpzWwomdTNpFov7aaHI4HPdGeeevZgipQKnzJELJbLLbONdI9aQjYgzcrbYdWYAMgZi0ehfjJ+Vx+j8WO1YOM0NYbpckA)

I see. May be it's fixed in some recent version.

**Comment by cristatus** [comment]
The type of `as` param in your original code should be inferred to make it work. You are passing the type directly.

**Comment by ayloncarrijo** [comment]
Seems like the problem occur just when using `Omit` or `ComponentProps`.

The reason why `ComponentPropsWithoutRef` works and `ComponentProps` doesn't is because `ComponentPropsWithoutRef` uses `PropsWithoutRef`, which uses a conditional type to omit the "ref" attribute. This gives us a workaround to fix the problem.

For now, using a conditional type on the omitted type seems to be enough to solve this:

[Playground](https://www.typescriptlang.org/play?ts=4.9.5#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgIilQ3wG4AocgeirgFoHGnnm4B1YGACwgFd4A8iE5wAFAIDSASnos5LSjACeYJHAAKOMAGcO3PjCGcAPAEFtcJAA8YSAHYATC8nQwAdAFEANkhD2YACoqSAB8cAC8cADe5HBwKNoA-ABccOYUAL5wAGSIxO4AwriQdv6aEDp6PPzImGbaIRTkDkhoXihEcJi8dhjAEHZwAUjaMFUGRjD1ljb2Tnmunj5+doHBIaKxcGBa2qnllZzVhsJT5iHkUql2vF5eTcbDo+P8k1sJ4fgARvwwA-hbAYFLzANAAa3CUVEADcUF5eEgZOEwjE4nEaDNVBgkA5UspVBBMHBYfC1JEXBg3ABZPjaJAeaH+YwACQCVIAMgAhX4Dby+fwAGjgNN4dIZ-guaLgGNcvDheOChOJcIREQWlJFYsZqxZbK5PLsfJWMCFmvp2pgkrRGMkWwyGWojUoGPkrsY7COcEmYgAcgIAl7pLI3fJFMENLsqpNptZbI5nPklvzVkFVGFIqj4klUulyFlctGKYVigMypGjgZavUQkL8Ch8HAAD4EL4N5v4ND4J3NVrtTrdXowfqDJ5jI7R8wzOPzItJ42p0KbOI7Cp7COrqOnauXa63e6UR4jMfcN5xD7fA0AuJAkHgyEwlWIiIorbo2jWLG2XFwfFIJUk1VyUTM1xR1VkOW5GA-kNZZBWFWlzQlV9pVoWV5R-RUiQAsl4jsJQxFAMBb04LwlCkZCMT9ANbTie1HSaF0Q3kL1TnYaAwQ6PhHDESQZCY0NyF-OAADFgCsR50yGKc5gsFA8LgRIpOuJBGSgJohIOXR2M4noHBjWZ43VdwjX8BdJMzBIUjSbRMhyESxOMQtEyKcBS1WTSXhgKtzlresmxbNsCE7EJGhQ+yrDgLgkCISgWjaDo1AHPoBiGI82G0nBdP06cE0WEyU3WJdtl2fZIwyri9POHc4BuO4HlHdKoA4zLHHebRPh+KD-kBOxgVBCEoWwpEXylDEP1aL8FQJLDHzVWcQItXUIINfKTXg0VENWK033iDA5S8Ka-xm0k5uAhDQKmcD9S6mDkzWhakNG2gaLgOiqCdIA)

```ts
import React from "react";

// -------------------- Without Omit (OK) --------------------

type PropsWithoutOmit<As extends React.ElementType> = {
  as?: As;
} & React.ComponentPropsWithoutRef<As>;

declare function TestWithoutOmit<As extends React.ElementType>(
  props: PropsWithoutOmit<As>
): null;

<TestWithoutOmit
  as="button"
  onClick={(value) => {
    // expected: typeof value = React.MouseEvent<HTMLButtonElement, MouseEvent>
    // actual: typeof value = React.MouseEvent<HTMLButtonElement, MouseEvent>
    // OK
  }}
/>;

// -------------------- With Omit (NOT OK) --------------------

type PropsWithOmit<As extends React.ElementType> = {
  as?: As;
} & Omit<React.ComponentPropsWithoutRef<As>, "a" | "b" | "c">;

declare function TestWithOmit<As extends React.ElementType>(
  props: PropsWithOmit<As>
): null;

<TestWithOmit
  as="button"
  onClick={(value) => {
    // expected: typeof value = React.MouseEvent<HTMLButtonElement, MouseEvent>
    // actual: typeof value = any (implicitly)
    // NOT OK
  }}
/>;

// -------------------- Omit Workaround (OK) --------------------

type Fix<T> = T extends any ? T : never;

type PropsWorkaround<As extends React.ElementType> = {
  as?: As;
} & Fix<Omit<React.ComponentPropsWithoutRef<As>, "a" | "b" | "c">>; // Fix here

declare function TestWorkaround<As extends React.ElementType>(
  props: PropsWorkaround<As>
): null;

<TestWorkaround
  as="button"
  onClick={(value) => {
    // expected: typeof value = React.MouseEvent<HTMLButtonElement, MouseEvent>
    // actual: typeof value = React.MouseEvent<HTMLButtonElement, MouseEvent>
    // OK
  }}
/>;
```

**Comment by Frownhoratio** [comment]
Spot this https://jacob-react-table-v8.github.io/ainsley/ answer here
