### ISSUE TITLE
Incorrect transpilation of generic type parameter

### ISSUE THREAD

**Issue by marikaner** [microsoft/TypeScript#44727]
# Bug Report

I have a type with an unused generic type parameter.\*
This type annotates an **optional parameter property** in the constructor of a class.
Starting with Version 4.2.X of TypeScript, this class is incorrectly transpiled, so that TS code using the transpiled sources (.d.ts) does not transpile anymore.
The error was:
```
error TS2304: Cannot find name 'T'
```

No wonder it cannot be found, it was not in the original code (please see the minimal example below).

During my investigation I found that this issue occurs, when these prerequisites are met:
1. The given type has an unused generic parameter.
1. The given type represents a union type.
1. You have a class with a constructor argument using the given type.
1. The constructor argument is a parameter property.
1. The constructor argument is optional.

*\* (Tried something. Didn't work. Postponed it, but left the parameter for later use.)*
### 🔎 Search Terms

generics, transpilation, missing parameter

### 🕗 Version & Regression Information

- This changed between versions 4.1.X and 4.2.X

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?target=5#code/C4TwDgpgBAQgTgewNYQHYBVwQDzoHxQC8UA5AIYlQA+pARiQNwCwAUKwMYA2ZAzj1AFkQAYW58oAb1ZQZUdglQ9gcAK7tgCOAAo4EMgBMFnEFDJwA5gH4AXLEQoMWbGVQg8ASkkBfVj5ZA)

### 💻 Code

Before transpilation:
```ts
type BrokenType<T> = 'a' | 'b';

class MyClass {
    constructor(readonly arg?: BrokenType<any>) {}
}
```

After transpilation
```ts
declare type BrokenType<T> = 'a' | 'b';
declare class MyClass {
    readonly arg?: BrokenType<T> | undefined;
    constructor(arg?: BrokenType<T> | undefined); // <----- T should be any
}
```

### 🙁 Actual behavior

The code is transpiled to contain the generic parameter name, instead of the actual type that was passed as argument.

### 🙂 Expected behavior

I would expect the result to contain the original type as specified in the original code. The generic parameter is not known when consuming the type. This worked before version 4.2.X.

**Comment by weswigham** [comment]
Fixed by #42211 - a dupe of #42079 (though, admittedly, a simpler repro)

**Comment by jakebailey** [comment]
The original problem here is "fixed" because we can copy the annotation, but the inferred version is still broken: https://www.typescriptlang.org/play?ts=5.5.0-dev.20240415#code/C4TwDgpgBAQgTgewNYQHYBVwQDzoHxQC8UA5AIYlQA+pARiQNwCwAUKwMYA2ZAzj1AFkQAYW58oAb1ZQZUdglQ9gcAK7tgCOAAo4EMgBMFnEFDJwA5gH4AXLEQoMWbGVQg8AGihhEYIlADaqCqcnKb8Lia8dshomJDOrngAuv4ADEkAlJIAvqzZQA
