### ISSUE TITLE
pnpm import module autocomplete is so long

### ISSUE THREAD

**Issue by pincman** [microsoft/TypeScript#45141]
*TS Template added by @mjbvz*

**TypeScript Version**: 4.4.0-dev.20210721

**Search Terms**
- completion
- suggestion / auto import

---

Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.58.2
- OS Version: macOS big sur

Steps to Reproduce:

1. pnpx create-vite
2. pnpm i
3. pnpm add antd

when i pass `ctrl+space`, import intellisense is so long

![image](https://user-images.githubusercontent.com/74093067/126461440-050451ff-8a5c-4cfd-95fe-bbd0b5864681.png)
but yarn is work fine
![image](https://user-images.githubusercontent.com/74093067/126461679-c5c8625f-3d93-4a8e-8cbd-3bf5852e53b5.png)

**Comment by andrewbranch** [comment]
@pincman can you share your package.json dependencies?

**Comment by pincman** [comment]
@andrewbranch 
package.json
```json
{
  "version": "0.0.0",
  "scripts": {
    "dev": "vite",
    "build": "tsc && vite build",
    "serve": "vite preview"
  },
  "dependencies": {
    "antd": "^4.16.8",
    "immer": "^9.0.5",
    "lodash": "^4.17.21",
    "react": "^17.0.2",
    "react-dom": "^17.0.2"
  },
  "devDependencies": {
    "@types/react": "^17.0.14",
    "@types/react-dom": "^17.0.9",
    "@typescript-eslint/eslint-plugin": "^4.28.4",
    "@typescript-eslint/parser": "^4.28.4",
    "@vitejs/plugin-react-refresh": "^1.3.5",
    "autoprefixer": "^10.3.1",
    "deepmerge": "^4.2.2",
    "eslint": "^7.31.0",
    "eslint-config-airbnb-typescript": "^12.3.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-import": "^2.23.4",
    "eslint-plugin-jest": "^24.3.6",
    "eslint-plugin-jsx-a11y": "^6.4.1",
    "eslint-plugin-prettier": "^3.4.0",
    "eslint-plugin-react": "^7.24.0",
    "eslint-plugin-react-hooks": "^4.2.0",
    "eslint-plugin-unused-imports": "^1.1.2",
    "jest": "^27.0.6",
    "less": "^4.1.1",
    "postcss": "^8.3.5",
    "prettier": "^2.3.2",
    "tailwindcss": "^2.2.4",
    "typescript": "^4.3.5",
    "vite": "^2.4.3",
    "vite-plugin-style-import": "^1.0.1"
  }
}
```
thx

**Comment by andrewbranch** [comment]
@pincman I can’t reproduce this. Are you sure your steps to reproduce are complete?

> Steps to Reproduce:
>
> pnpx create-vite
> pnpm i
> pnpm add antd

This produces a lot smaller of a package.json and tsconfig.json than you shared. I tried following your steps exactly, and I tried copying your package.json and tsconfig.json , but couldn’t ever find a repro. Can you make sure your steps to reproduce are accurate, precise, and still exhibit the issue?

**Comment by pincman** [comment]
@andrewbranch 
1.  pnpx create-vite
2. press `y`
3. select `react`
4. select `react-ts`
5. cd vite-project
6. `npm install -g pnpm`
7. `pnpm i`
8. `pnpm add antd`
9. `code .`
10. open `src/App.tsx` in vscode
11. press `<Button` after `<div className="App">`
this will get like follow
![image](https://user-images.githubusercontent.com/74093067/128001778-83ad6e1b-1b45-4d1a-9e12-64b371fffa7b.png)
but correct is like
![image](https://user-images.githubusercontent.com/74093067/126461679-c5c8625f-3d93-4a8e-8cbd-3bf5852e53b5.png)

**Comment by andrewbranch** [comment]
Oh, you’re just talking about the path that shows up in the list, not the path that gets inserted when you accept the completion 🤦 

That’s already fixed in TS 4.4 and VS Code Insiders.

**Comment by OptimBro** [comment]
I am having same issue here. I was just googling and came here. @andrewbranch thanks let me check with VSCode insider.

**Comment by dialformonkey** [comment]
> Oh, you’re just talking about the path that shows up in the list, not the path that gets inserted when you accept the completion 🤦
> 
> That’s already fixed in TS 4.4 and VS Code Insiders.

Hi Andrew. It still does not work for me on VSCode insiders as well. please advice

**Comment by heemoe** [comment]
reload vscode window just work for me.😋
