### ISSUE TITLE
Renaming file triggers error in tsconfig.json

### ISSUE THREAD

**Issue by zgoda** [microsoft/TypeScript#46432]
*TS Template added by @mjbvz*

**TypeScript Version**: 4.5.0-dev.20211019

**Search Terms**
- jsconfig / tsconfig
- config
- configFileDiag

See https://github.com/microsoft/TypeScript/issues/46432#issuecomment-940813629 for the simplest repo

---

Issue Type: <b>Bug</b>

The project is in JS but has configured TS support with `tsconfig.json`. After renaming source file in explorer pane, following error appears twice in problems pane pointing to `tsconfig.json`:

```
File '/home/jarek/work/wymarsz/wk-web/node_modules/source-map/source-map' not found.
  The file is in the program because:
    Root file specified for compilation
```

The issue appears also with all extensions disabled.

The error goes away after window reload.

Reproductible: always.

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:43:02.136Z)
OS version: Linux x64 5.4.0-81-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3400G with Radeon Vega Graphics (8 x 2002)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|29.34GB (23.56GB free)|
|Process Argv|--unity-launch --crash-reporter-id 75655822-4d79-453c-9a0d-23266699ca32|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.23
gitlens|eam|11.6.0
EditorConfig|Edi|0.16.4
prettier-vscode|esb|8.1.0
dotenv|mik|1.0.1
sass-indented|syl|1.8.18

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwt:30329788
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30360495
bridge0723:30353136
pythonf5test824:30361777
vsdyn478:30356813
pythonvspyt187cf:30362783
pydsgst2:30361792
vscus224:30358039
vssid140:30362080

```

</details>

![Zrzut ekranu z 2021-09-07 11-53-45](https://user-images.githubusercontent.com/141999/132326089-425112a2-e386-40ef-b4f8-d4fdac58116c.png)

**Comment by nolawnchairs** [comment]
> I see people asking for that on Reddit and SO and the only answer is "reload window to fix temporarily".
> 
> The package (and file) definitely exists:
> 
> ```
> $ ls -al /home/jazg/work/wymarsz/wk-web/node_modules/source-map/source-map.js 
> -rw-rw-r-- 1 jazg jazg 405 sie 30 00:45 /home/jazg/work/wymarsz/wk-web/node_modules/source-map/source-map.js
> ```

Actually, all you need to do is reload the TS server, that's an F1 action as well.

**Comment by AzharUddinSheikh** [comment]
I was getting an error in `tsconfig.json` file (React Typescript) when I have renamed a `file` I just close my `editor` and restart the `server` error gone

**Comment by Luxcium** [comment]
My workaround (since I do not use  _workbench.action.quickOpenNavigateNextInRecentFilesPicker_ was to go into the Keybindings ctrl+k ctrl+s and change the _Developer: Reload Window_ to use ctrl + R

**Comment by Luxcium** [comment]
As I mentioned in #43838 :

For the moment I have changed my keybindings (using VS Code) and I think I will be using them often so I will probably change them again... 

![Screenshot_000001_20221201_092230](https://user-images.githubusercontent.com/42672814/205078271-8ea47cb1-2be1-421d-9750-f35860fa0d44.png)


It remaps some default keybindings, You probably need something similar depending on your workflow...

**Comment by DanielRosenwasser** [comment]
It sounds a whole lot like [TypeScript 4.8's file-watching fixes](https://devblogs.microsoft.com/typescript/announcing-typescript-4-8/#file-watching-fixes) and [TypeScript 4.9's usage of file system events](https://devblogs.microsoft.com/typescript/announcing-typescript-4-9/#file-watching-changes) should alleviate this issue. These fixes typically targeted Unix-like systems (including Linux and macOS) so I'm curious to hear if anyone is experiencing this with the latest version of TS.

**Comment by jleclanche** [comment]
@DanielRosenwasser yes, I've been able to reproduce this in WSL and TS 4.9. I don't remember if I experienced it on Linux itself.

**Comment by Ashin-55** [comment]
i got the same error while renaming any file ,
![Screenshot from 2023-01-24 20-16-42](https://user-images.githubusercontent.com/72868663/214326058-f6e495ae-3593-4cc0-a76e-30760ff8ec15.png)
then I reopened the code again, and that time the error is not showing...

**Comment by sandersn** [comment]
The repro I get now is exactly #43838, so I think the original bug has been fixed -- the bizarro "thing in node_modules is not found" been replaced by the similar, slightly better, but obviously-wrong "The old name of the thing you renamed is not found."

**Comment by jonschlinkert** [comment]
I still have this error, literally every time I rename any file.

**Comment by gameprogrammingsteven** [comment]
I just got this error as well. It seems to repro when I rename things above my src dir for React. It does not fix when I re-rename it to undo. F1 Refresh works.

**Comment by ChristopherHaws** [comment]
This issue should not be closed. I have been dealing with this issue for over a year now, it's an awful developer experience. Is it really that hard to watch the file system? I feel like every other language is able to do this... For the longest time I thought it was just a local environment, but even on fresh installs of Windows or Linux I instantly run into this issue. I have tried different configurations of `typescript.tsserver.watchOptions`, `files.watcherInclude`, and `files.watcherExclude` in VSCode to no avail.

NOTE: I am using `pnpm` and not `npm`

**Comment by sheetalkamat** [comment]
If this is still an issue, you should file a new issue with clear steps to repro, tsserver log so that can be investigated.

**Comment by gameprogrammingsteven** [comment]
If you need clearer instructions than "rename file", maybe you're not meant for this job.

**Comment by RyanCavanaugh** [comment]
@gameprogrammingsteven please refer to the [code of conduct](https://microsoft.github.io/codeofconduct/) and consider yourself warned re "insults"
