### ISSUE TITLE
Spread arguments should appropriately spread into optional parameters

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#4759]
Adapted from #4755.

Currently the following is fine:

``` TypeScript
function f(...things: any[]) {
    let [a, ...bs] = things;

    // do things with 'a' and 'bs'
}

function g(xs: any[]) {
    f(...xs);
}
```

However, it might be the case that you want to be clear about how `things` will be used when your function gets called, so it should be fine to use an optional parameter for `a`:

``` TypeScript
function f(a?: any, ...bs: any[]) {
    // do things with 'a' and 'bs'
}

function g(xs: any[]) {
    f(...xs);
//  ~~~~~~~~
}
```

Currently, with the invocation of `f` above you'll get the error message `Supplied parameters do not match any signature of call target.` even though `a` is optional.

**Comment by bootstraponline** [comment]
:+1:

**Comment by mhegazy** [comment]
should be subsumed by a fix to https://github.com/Microsoft/TypeScript/issues/4130

**Comment by mhegazy** [comment]
on a closer look, this is already fixed.

**Comment by yordis** [comment]
@mhegazy @DanielRosenwasser using `"typescript": "^2.7.0-dev.20171123"` I am still having this issue everywhere I use spread operator I have to actually do `functioName.call(null, value)`

I am confused because most of the tickets said close but this still happening

**Comment by bootstraponline** [comment]
Yeah, I don''t think this works.


```typescript
let str = "abc";
let arr = [...str];
```

Maybe it requires some configuration.

- https://stackoverflow.com/a/33233956
