### ISSUE TITLE
narrowing object by property doesn't work if key isn't a `const`

### ISSUE THREAD

**Issue by DetachHead** [microsoft/TypeScript#51368]
# Bug Report

### 🔎 Search Terms

narrow property const

### 🕗 Version & Regression Information

4.9.0-dev.20221025

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.9.0-dev.20221025#code/JYOwLgpgTgZghgYwgAgCJzHZBvAUMg5OAfgC5kQBXAWwCNpcBfXXAEwgQBs4oUEB7EAGcwyVhjjl0mFpwiiA1hACeyALzIA5HE1EhyAcLAtgMZAApxmAHRYAhGo2UQ7GKAisAlDnyEly3wIAeiCAPWJAg0ERInUxCQBtfwBdSJDCZHDIwxjaOKs4BO1NVIz0wizGIA)

### 💻 Code

```ts
interface Data {
    a?: number
}

declare const data: Data

let key = 'a' as const

if (data.a !== undefined) {
    key // "a"
    const a = data[key] // number | undefined
    const b = data['a'] // number
}
```

### 🙁 Actual behavior
`data[key]` is `number | undefined`

### 🙂 Expected behavior
`data[key]` is narrowed to `number`

**Comment by KotlinIsland** [comment]
I managed to minify this issue a little bit, take a look below:
```ts
declare const data: {
    a?: number
}

if (data.a === undefined) throw "up"

const a = data['a' as 'a']
//    ^?
const b = data['a']
//    ^?
```

**Comment by fatcerberus** [comment]
Duplicate of https://github.com/microsoft/TypeScript/issues/10530.  Only certain patterns of property access induce narrowing, specifically only the forms `obj.foo` and `obj['foo']` (i.e. the key must be a naked literal).  `obj[key]` won't be narrowed, even if `key` is literal-typed.

**Comment by DetachHead** [comment]
the example in that issue seems to have been fixed ages ago https://github.com/microsoft/TypeScript/issues/10530#issuecomment-1298005608

**Comment by MartinJohns** [comment]
Plenty of issues with your example are closed as duplicate of that issue, and it's still open.

**Comment by fatcerberus** [comment]
Yeah, `foo["bar"]` used to not be narrowable.  Now it is, but the larger issue of `foo[keyVar]` not narrowing (which is a much bigger can of worms, implementation-wise) is still present.
