### ISSUE TITLE
Issue with TS4.9 -   'AbortSignal' was also declared here.

### ISSUE THREAD

**Issue by jogibear9988** [microsoft/TypeScript#51567]
# Bug Report

After upgradeing to Typescript 4.9 I get now this error.

      [20:27:02] Starting compilation in watch mode...
      
      node_modules/@types/node/globals.d.ts:72:13 - error TS2403: Subsequent variable declarations must have the same type.  Variable 'AbortSignal' must be of 
      type '{ new (): AbortSignal; prototype: AbortSignal; abort(reason?: any): AbortSignal; timeout(milliseconds: number): AbortSignal; }', but here has type 
      '{ new (): AbortSignal; prototype: AbortSignal; timeout(milliseconds: number): AbortSignal; }'.
      
      72 declare var AbortSignal: {
                     ~~~~~~~~~~~
      
        node_modules/typescript/lib/lib.dom.d.ts:2071:13
          2071 declare var AbortSignal: {
                           ~~~~~~~~~~~
          'AbortSignal' was also declared here.
      
      [20:27:09] Found 1 error. Watching for file changes.

**Comment by jogibear9988** [comment]
This are the packages in my package.json:

    "dependencies": {
      "@node-projects/base-custom-webcomponent": "^0.10.3",
      "construct-style-sheets-polyfill": "^3.1.0"
    },
    "devDependencies": {
      "@node-projects/lean-he-esm": "^3.3.0",
      "@node-projects/node-html-parser-esm": "^2.4.1",
      "@papyrs/stylo": "^0.0.41",
      "@types/codemirror": "^5.60.5",
      "@types/jquery": "^3.5.14",
      "@types/jquery.fancytree": "0.0.7",
      "ace-builds": "^1.13.1",
      "codemirror": "^6.0.1",
      "esprima-next": "^5.8.4",
      "html2canvas": "*",
      "jest": "^29.3.1",
      "jquery": "^3.6.1",
      "jquery.fancytree": "^2.38.2",
      "monaco-editor": "^0.34.1",
      "ts-jest": "^29.0.3",
      "typescript": "^4.9.3",
      "typescript-lit-html-plugin": "^0.9.0"
    },

**Comment by MartinJohns** [comment]
https://devblogs.microsoft.com/typescript/announcing-typescript-4-9/#correctness-changes

Why do you reference node AND dom types?

**Comment by benmccann** [comment]
I ran into this in my project with `AbortController` and fixed it by upgrading all my dependencies to the latest versions (https://github.com/sveltejs/kit/pull/7657).

**Comment by melink14** [comment]
> [devblogs.microsoft.com/typescript/announcing-typescript-4-9/#correctness-changes](https://devblogs.microsoft.com/typescript/announcing-typescript-4-9/#correctness-changes)
> 
> > We don’t expect major breaks as a result of DOM and lib.d.ts updates, but there may be some small ones.
> 
> Why do you reference node AND dom types?

Wouldn't it be quite natural to reference both if you had a web project with node build scripts? 

It looks like the goal is to fix it in the node types https://github.com/DefinitelyTyped/DefinitelyTyped/issues/60868 but not sure how long that will take...

**Comment by jakebailey** [comment]
I'm pretty sure that this is just a case of needing to update types. We fixed this same issue in Monaco a week or so ago by updating deps.

**Comment by melink14** [comment]
As Jake said, you may have a transitive dependency with out of date node types. In that case try to delete your lock file and then run `npm i` again. (relock as Jake put it)

**Comment by jogibear9988** [comment]
I did this. I deleted the lock file.

**Comment by jogibear9988** [comment]
fixed it by adding @types/node to my dev dependencies

      npm i -d @types/node

**Comment by melink14** [comment]
That's definitely strange and unexpected but without seeing your setup it's hard to say what went wrong. If you're okay keeping an unused dev dependency, that's probably a solid solution.

**Comment by jogibear9988** [comment]
You see my setup. Above I posted every Dependecy I have.
The source I used is here: https://github.com/node-projects/web-component-designer

**Comment by melink14** [comment]
Took a quick look and it was a problem with transitive dependencies, I had just not gotten the steps to properly refresh your lockfile correctly. You also need to delete node_modules folder. Here's the steps I took in your repo:

1. `npx npm-upgrade` and say yes to everything.
2. 'npm i1
3. `npm run tsc` and confirm error.
4. `rm package-lock.json`
5. `rm -Rf node_modules/`
6. `npm i`
7. `npm run tsc` -> no error!

**Comment by jogibear9988** [comment]
Thanks
I thought a "npm i" was enough

**Comment by fatcerberus** [comment]
It used to be that *not* having lockfiles made dependency management hard.  Now **deleting** the lockfile is a valid troubleshooting method to fix dependency issues.  We've come full circle, ladies and gentlemen! 😄

**Comment by jogibear9988** [comment]
yes, and now you also need to delete node_modules folder... this i found modt discusting

**Comment by GitGrv** [comment]
QUICK FIX*
--------update all your dependencies ----

1.  npm i -g npm-check-updates
2. ncu -u
3. npm install

**Comment by fregante** [comment]
This may happen when another dependency installs an older `@types/node` version. Run this to find out which one it is:

```
npm ls @types/node
```

In my case I had `@types/node@17.0.40` installed. So via `@types/tape`, so I uninstalled and then re-installed `@types/tape`.

You don't need to install `@types/node` directly. **Doing a clean install without package-lock and node_modules might fix it.** And/or `npx npm-check-updates -u`

**Comment by Jeremiah-Ropo** [comment]
fixed

**Comment by peetjvv** [comment]
> fixed

@Jeremiah-Ropo , has this fix been released yet? I'm still getting the error in v4.9.4.

**Comment by jakebailey** [comment]
There is no change to TypeScript that will fix this; the fix is to update your installed types to new enough versions that support 4.9.

**Comment by IRod22** [comment]
@RyanCavanaugh the error still persists, *and* I have no other dependencies besides TypeScript.

```
> tsc

../node_modules/@types/node/globals.d.ts:72:13 - error TS2403: Subsequent variable declarations must have the same type.  Variable 'AbortSignal' must be of type '{ new (): AbortSignal; prototype: AbortSignal; abort(reason?: any): AbortSignal; timeout(milliseconds: number): AbortSignal; }', but here has type '{ new (): AbortSignal; prototype: AbortSignal; }'.

72 declare var AbortSignal: {
               ~~~~~~~~~~~

  node_modules/typescript/lib/lib.dom.d.ts:2071:13
    2071 declare var AbortSignal: {
                     ~~~~~~~~~~~
    'AbortSignal' was also declared here.


Found 1 error in ../node_modules/@types/node/globals.d.ts:72

>
```
```jsonc
{
  // ...
  "devDependencies": {
    "typescript": "4.9.4"
  }
}

```

This is after I deleted my `node_modules` and `package-lock.json`.

**Comment by nVitius** [comment]
I started getting this issue today when adding "DOM" to my `compilerOptions.lib`.

**Comment by dbrgn** [comment]
If you're having issues even though both the node types and TypeScript are up to date, try removing your `node_modules` directory.

I had the situation where `@types/node` would still load the TS 4.8 compatibility types (from the `ts4.8` directory) even though I was already on TS 4.9 and had called `npm install`. Removing the `node_modules` directory and re-running `npm install` resolved the issue.

**Comment by ilyaVenetrab** [comment]
> 



> fixed it by adding @types/node to my dev dependencies
> 
> ```
>   npm i -d @types/node
> ```
Thanks, this really helped me.

**Comment by breck7** [comment]
Thank you @melink14! I started hitting this this morning and your steps worked for me.

**Comment by VitorAugusto** [comment]
Fixed it by upgrading my "@types/node".

from
`"@types/node": "^17.0.13"`
to
`"@types/node": "^18.11.18"`

all on "devDependencies".

**Comment by jakebailey** [comment]
v17 was an unstable release and its types are no longer on DT, so it makes sense that it didn't get the fix as it hasn't been updated in 8 months; if you still have Node 17 types in your projects you'll definitely want to go to v18.

**Comment by BroJenuel** [comment]
Thanks, I was able to fix mine:
```bash
yarn add @types/node -D
```
or 
```bash
npm install @types/node -D
```

**Comment by TierK** [comment]
npm upgrade

Works 100%!

**Comment by ShaikMohammadAbdullah** [comment]
> These are the packages in my package.json:
> 
> ```
> "dependencies": {
>   "@node-projects/base-custom-webcomponent": "^0.10.3",
>   "construct-style-sheets-polyfill": "^3.1.0"
> },
> "devDependencies": {
>   "@node-projects/lean-he-esm": "^3.3.0",
>   "@node-projects/node-html-parser-esm": "^2.4.1",
>   "@papyrs/stylo": "^0.0.41",
>   "@types/codemirror": "^5.60.5",
>   "@types/jquery": "^3.5.14",
>   "@types/jquery.fancytree": "0.0.7",
>   "ace-builds": "^1.13.1",
>   "codemirror": "^6.0.1",
>   "esprima-next": "^5.8.4",
>   "html2canvas": "*",
>   "jest": "^29.3.1",
>   "jquery": "^3.6.1",
>   "jquery.fancytree": "^2.38.2",
>   "monaco-editor": "^0.34.1",
>   "ts-jest": "^29.0.3",
>   "typescript": "^4.9.3",
>   "typescript-lit-html-plugin": "^0.9.0"
> },
> ```

**Comment by kenny1983** [comment]
> fixed it by adding @types/node to my dev dependencies
> 
> ```
>   npm i -d @types/node
> ```

This should be `npm i **-D** @types/node` (case is important!), but other than that, this works. Thanks!

**Comment by Sintayew4** [comment]
#51567
