### ISSUE TITLE
Wrong import suggestion in subpath pattern

### ISSUE THREAD

**Issue by konsalex** [microsoft/TypeScript#52870]

**Comment by mjbvz** [comment]
Can you please try upgrading your workspace to use the next version of typescript by installing [this extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next) and then restarting VS Code. Does this fix the issue?

**Comment by RyanCavanaugh** [comment]
A reduced repro would let us look at this earlier

**Comment by mbrevda** [comment]
Look like this was fixed in https://github.com/microsoft/TypeScript/pull/55015

**Comment by konsalex** [comment]
@mbrevda tried with TS 5.4, and still have the same issue in VS Code.

Example screenshot:

![CleanShot 2024-02-14 at 15 26 40@2x](https://github.com/microsoft/TypeScript/assets/12672541/7a69183d-2fac-47b6-9942-5799fcb28239)

Here you can find the package config:
https://www.jsdelivr.com/package/npm/@neo4j-ndl/react?tab=files

Not sure what is different from WebStorm's approach, but there is works as expected:
![CleanShot 2024-02-14 at 15 28 49@2x](https://github.com/microsoft/TypeScript/assets/12672541/71a7dafb-4752-4754-8d0a-8e18779b7f50)

**Comment by mbrevda** [comment]
Realizing now that our use cases differ: I'm doing subpath imports.
