### ISSUE TITLE
Inaccurate Type Definition for String.prototype.matchAll

### ISSUE THREAD

**Issue by kkirby** [microsoft/TypeScript#57024]
### ⚙ Compilation target

ES2020

### ⚙ Library

es2020.string

### Missing / Incorrect Definition

The issue is with the `String` interface, specifically regarding the `matchAll` method.

- **Current Incorrect Definition:**
  - In the TypeScript standard library file `lib.es2020.string.d.ts`, the `String` interface is currently defined as follows:
    ```typescript
    interface String {
        matchAll(regexp: RegExp): IterableIterator<RegExpMatchArray>;
    }
    ```
  - The return type `RegExpMatchArray` is only valid for `String.prototype.match`.
  - `String.prototype.matchAll` is guaranteed to return an iterator with the same value as `RegExp.prototype.exec`. The regular expression provided to `matchAll` must contain the `/g` modifier, otherwise an error is thrown.

- **Problem with Current Definition:**
  - This definition incorrectly says that the `index` and `input` properties may not be present in the `RegExpMatchArray`. However, when using `String.prototype.matchAll`, it returns an iterator of objects, each consistently including the `index` and `input` properties. These properties are not optional in the returned objects.

- **Suggested Correct Definition:**
  - The `matchAll` method should be updated to return `IterableIterator<RegExpExecArray>`

### Sample Code

```TypeScript
const str = "Hello, {{name}}!";
for(const match of str.matchAll(/{{(.*?)}}/g)){
  if(match.index > 0){} // TypeScript incorrectly says that `index` may be undefined
}
```

### Documentation Link

https://tc39.es/ecma262/multipage/text-processing.html#sec-string.prototype.matchall

**Comment by fatcerberus** [comment]
This was already fixed? https://github.com/microsoft/TypeScript/pull/55565

**Comment by BoringBoredom** [comment]
Not fixed on my end

![image](https://github.com/microsoft/TypeScript/assets/16615327/366bec8f-3812-4ebe-bbff-a262ddcd853c)
![image](https://github.com/microsoft/TypeScript/assets/16615327/b6d52178-a762-4d86-a004-980344fb5a30)
