### ISSUE TITLE
Differing user-defined type guard and built-in type guard behaviour when narrowing 'any'

### ISSUE THREAD

**Issue by pimterry** [Microsoft/TypeScript#6015]
In the below code, using a typeof type guard and an equivalent (I thought) user-defined guard, only one error is produced.

```typescript
var y: any;

// Built-in type guard
if (typeof y === "string") {
	y.hello = true; // Correct error - 'hello' does not exist on type string
}

// Equivalent user-defined type guard
function f(x: any): x is string {
	return typeof x === "string";
}

if (f(y)) {
	y.hello = true; // No error with user-defined guard
}
```

[Playground demo](http://www.typescriptlang.org/Playground#src=var%20y%3A%20any%3B%0A%0A%2F%2F%20Built-in%20type%20guard%0Aif%20(typeof%20y%20%3D%3D%3D%20%22string%22)%20%7B%0A%09y.hello%20%3D%20true%3B%20%2F%2F%20Correct%20error%0A%7D%0A%0A%2F%2F%20Equivalent%20user-defined%20type%20guard%0Afunction%20f(x%3A%20any)%3A%20x%20is%20string%20%7B%0A%09return%20typeof%20x%20%3D%3D%3D%20%22string%22%3B%0A%7D%0A%0Aif%20(f(y))%20%7B%0A%09y.hello%20%3D%20true%3B%20%2F%2F%20No%20error%20with%20user-defined%20guard%0A%7D). Looks like user-defined type guards won't narrow from `any`, in any circumstances, as far as I can tell.

**Comment by pimterry** [comment]
Any thoughts on this?

Looks clearly incorrect to me, but I can't find a definitive spec on user-defined type guards, which makes it difficult to verify. I'd be very surprised that they're actually intended to differ from built-in type guards in this regard though.

**Comment by DanielRosenwasser** [comment]
The thing is that user-defined type guards are "weaker" than `typeof` guards given that an implementation might use `instanceof` in some way. `instanceof` type guards have to be weaker because narrowing a value's type from `any` to `Object` limits what you can do with it. Clearly this gives you a not-so-great experience when you try to work with primitives.

@ahejlsberg and I have discussed this offline and one idea we have is that for any primitive type covered by a `typeof` type guard (i.e. `string`, `number`, `boolean`, and `symbol`), we should consider performing the same narrowing as a `typeof` type guard because that's usually how you were going to implement something like `isString`.

**Comment by DanielRosenwasser** [comment]
If anyone is considering sending a PR for this, give a heads up here so we don't duplicate work. :smiley:

**Comment by thebanjomatic** [comment]
I've been playing around with the controlFlowTypes branch and it appears as if the same narrowing behavior should probably apply there as well:  

For example:
```typescript
let a: any;
a = "10";
a; // a: any ... expected a: string
a.toFixed(2); // no compile error!
```

I have been using noImplicitAny in my own code base, but I can imagine some smarter behavior here could only help to find bugs in code which does wind up using any (whether implicitly or explicitly).

**Comment by basarat** [comment]
Came up on stackoverflow : http://stackoverflow.com/a/37153565/390330 :rose:

**Comment by jstaro** [comment]
Writing a type guard for something that TS thinks is `any` is basically what I've always tried to use this feature for, and it fails 100%, making the language feature DOA for me. I just end up casting instead, which makes me feel unclean :(

**Comment by RickCarlino** [comment]
@jstaro This does not seem to be a problem with TSC > 2.2 and latest VS Code.

```typescript

interface User {
  name: string;
}

function isUser(input: any): input is User {
  return (input && input.name);
}

let x = JSON.parse('"any"');

if (isUser(x)) {
  x;
} else {
  x;
}
```

**Comment by ShuiRuTian** [comment]
@DanielRosenwasser this should have been fixed?

**Comment by onlynone** [comment]
This appears to be fixed for user defined type guards, [but strict equality `===` appears to still not narrow `any` types](https://www.typescriptlang.org/play?#code/G4QwTgBAngXBIDsoG4BQqD0GICECuAlgDYAuAtAQhCVAA4CmEA5nuACaoEBmEAFDQwD2PKBAC8EiACIAziTCUmUgJQQA3qghboAOgAW9IkUHjqYPPWQQsEAMKCwYegGMSEeo4cQyEAOQGjQV8INkF6GQgEQTd6AA8COQhBKgFGOQUEJlQAX3QbAFEAR0JQInoENzwZDzI2ei5KejZqOkYWdlQuPARXAmSILl5YuEQoZThYiASIdMV1TW0nEjwwFNbhCEmJMWlZzKk0XM4eXkGx1Q1tXQDjU3kLKxsAFT1p6aiAd3gIZwcnV3cnkgHwIJD0ECIIBI4TcTwAyhBgB4ZH0EHAAApgQQMMA0Pw3IIhMIRKIxeKJfqpPx7Ji+HQ5dDcXiibbSAkqeZXKD6Qy3Hb3SzWbAAORMHixwNB4NmAPoxRARFBonaYA42SAA):

```typescript
var y: any;

// Built-in type guard
if (typeof y === "string") {
    y.hello = true; // Correct error - 'hello' does not exist on type string
}

// Equivalent user-defined type guard
function f(x: any): x is string {
    return typeof x === "string";
}

if (f(y)) {
    y.hello = true; // This is now a correct error with latest TS version: Property 'hello' does not exist on type 'string'.
}

if(y === "hello") {
    y.hello = true; // No error with strict equality guard
}
```

Is that intentional?

**Comment by d07RiV** [comment]
It appears to be "fixed", but I don't think that's the correct behavior? I should be able to access arbitrary fields on `any` type.

```
const x: any

if (_.isObject(x)) {
  x.foo // error - why?
}
```

**Comment by gregor-mueller** [comment]
> This appears to be fixed for user defined type guards, [but strict equality `===` appears to still not narrow `any` types](https://www.typescriptlang.org/play?#code/G4QwTgBAngXBIDsoG4BQqD0GICECuAlgDYAuAtAQhCVAA4CmEA5nuACaoEBmEAFDQwD2PKBAC8EiACIAziTCUmUgJQQA3qghboAOgAW9IkUHjqYPPWQQsEAMKCwYegGMSEeo4cQyEAOQGjQV8INkF6GQgEQTd6AA8COQhBKgFGOQUEJlQAX3QbAFEAR0JQInoENzwZDzI2ei5KejZqOkYWdlQuPARXAmSILl5YuEQoZThYiASIdMV1TW0nEjwwFNbhCEmJMWlZzKk0XM4eXkGx1Q1tXQDjU3kLKxsAFT1p6aiAd3gIZwcnV3cnkgHwIJD0ECIIBI4TcTwAyhBgB4ZH0EHAAApgQQMMA0Pw3IIhMIRKIxeKJfqpPx7Ji+HQ5dDcXiibbSAkqeZXKD6Qy3Hb3SzWbAAORMHixwNB4NmAPoxRARFBonaYA42SAA):
> 

I ran into the same thing, and read through some issues here (e.g. https://github.com/Microsoft/TypeScript/issues/1938#issuecomment-72994925).


> Is that intentional?

```ts
function doSomeThing(input: 'foo' | 'bar') { }

function onChange(value: any) {
    if (value === 'foo') {
        doSomeThing(value)
//                  ^? any
    }
    if (value === 'bar') {
        doSomeThing(value)
//                  ^? any
    }
}
```
[_Playground link_](https://www.typescriptlang.org/play/?ts=5.9.3#code/GYVwdgxgLglg9mABAEzgZTgWwKYBUAWMYA5gBREAOIUAXIgOTBxz2IA+DARgIYBO9ASkQBvRAF8AUBNCRYCRAgDC+biWykAbtwA2IbHVUBPIcImJziGMESadexAF4nDJixNmLn1BhwEiZLV1sAQkAelDPSKiLAD0Afg9zSU8rG0D7JwcuPkERRMjvLDxCElsgkPDoqtiEz0lJIA)

It feels like instead of `any` it really should be `'foo'` or `'bar'` respectively. The check is also done in runtime, so I don't see why primitives should not be narrowed from any in a value comparison like this.

This might be another issue so if you want, I can create another issue for that  - is it a feature request or bug report though?
Just tried not to create too much noise for you.

Thanks for always being so open to suggestions. Keep up the good work! 👍
