### ISSUE TITLE
External modules that don't export anything emit empty declarations.

### ISSUE THREAD

**Issue by robwormald** [Microsoft/TypeScript#6022]
Background - in RxJS we have a number of "operators" that extend our base Observable type.

```typescript
//src/Observable.ts
class Observable {
  map: <R>(project: (x: T, ix?: number) => R, thisArg?: any) => Observable<R>;
}
```

```typescript
// src/operators/map.ts
export function map<T, R>(project: (x: T, ix?: number) => R, thisArg?: any): Observable<R> {
  if (typeof project !== 'function') {
    throw new TypeError('argument is not a function. Are you looking for `mapTo()`?');
  }
  return this.lift(new MapOperator(project, thisArg));
}
//snip
```

This separation allows a user to import the `map` operator function and use it without bringing in the other 95 or so - without "side-effects":
```typescript
import {map} from 'rxjs/operators/map'
map.call(someObservable, (v) => v + 1 );
```
Without functionBind, this is slightly unergonomic, so we defined a set of "patch" modules that import the `Observable` type and the the `map` operator, and patch the prototype there:

```typescript
//rxjs/add/operators/map.ts
import {Observable} from '../../Observable';
import {map} from '../../operator/map';
Observable.prototype.map = map;
```

With the idea being a user should be able to simply `import 'rxjs/add/operators/map'` and have the prototype patched in the background.

Issue:

The emitted `rxjs/add/operators/map.d.ts` file is emitted completely empty, and so when a user goes to `import 'rxjs/add/operators/map.ts'`, the Typescript compiler errors with
 ```
error TS2656: 
Exported external package typings file 'node_modules/rxjs/add/operator/map.d.ts' is not a module. 
Please contact the package author to update the package definition.
```
Discussed with @mhegazy 

CC @blesh @jeffbcross

RxJS Issue: https://github.com/ReactiveX/RxJS/issues/1010
Sample file: https://github.com/ReactiveX/RxJS/blob/master/src/add/operator/map.ts

**Comment by vladima** [comment]
fixed in #6213

**Comment by masaeedu** [comment]
@vladima I'm still seeing this issue. When doing:

```
// a.ts
export class A { }
```

```
// b.ts
import {A} from './a';
// do some prototype patching or other side effect stuff here
```

With the `declaration` option set to `true`, the declaration file for `b.ts` is still generated empty, which makes it impossible to import it for consumers of the library. I'm not sure there's anything that needs to be changed in what is generated, but possibly the error for importing an empty declaration file for its side effects should be removed.

**Comment by vladima** [comment]
you need to declare module augmentation for `./a` in `b.ts` in order to explicitly tell compiler that this is module is patching its imports (or global scope). In this case compiler will keep treat this file as internal module.
```ts
// a.ts
export class A {}
```
```ts
// b/ts
import {A} from "./a";
(<any>A.prototype).foo = function() {}
declare module "./a" {}
```
Output after running `node built/local/tsc.js b.ts -m commonjs -d`:
```ts
// b.d.ts
declare module "./a" {
}
export {};
```

**Comment by masaeedu** [comment]
@vladima Some modules don't have any type signatures to merge. They simply mutate existing members. A good example is [this file](https://github.com/ReactiveX/RxJS/blob/90bf3f18f94cd63b5cdbfe83b7b7b5c5f021d641/src/add/observable/defer.ts), which assigns a function to a static class member defined elsewhere:

```
import {Observable} from '../../Observable';
import {DeferObservable} from '../../observable/DeferObservable';

Observable.defer = DeferObservable.create;

export var _void: void;
```

The .d.ts file generated for this is empty, which means consumers of the compiled JS + definitions will get an error when trying to import this, although within the TypeScript codebase it is treated as an external module and can be imported without problems.

**Comment by masaeedu** [comment]
Would you recommend adding an empty module declaration for every such file?

```
import {Observable} from '../../Observable';
import {DeferObservable} from '../../observable/DeferObservable';

Observable.defer = DeferObservable.create;

declare module '../../Observable' { } // Dummy module augmentation to ensure the definition file is not empty
```

**Comment by vladima** [comment]
I'm curious if we can just add `export {}` when emitting declaration file for an external module that does not export anything by itself (just to preserve the fact that original file is external module so it should be ok to import it). pinging @mhegazy @ahejlsberg for their opinion.

**Comment by masaeedu** [comment]
Another alternative would be to not emit anything instead of emitting an empty file, since this also eliminates the error (although this might come with its own set of problems that I'm not foreseeing).

**Comment by mhegazy** [comment]
@masaeedu i do not see how you are getting any errors here. here is the setup that i have:

```ts
// deferedAugmentation.ts
import {Observable} from '../../Observable';
import {DeferObservable} from '../../observable/DeferObservable';

Observable.defer = DeferObservable.create;
```

generates:

```ts
// deferedAugmentation.d.ts
// Empty
```

now we use it in anohter module

```ts
// anotherModule.ts

import "./deferedAugmentation"; // No Error
```

Can you give us more information on where you are seeing the error/

**Comment by masaeedu** [comment]
@mhegazy Here's what I'm seeing:

![image of error in editor](http://i.imgur.com/6dvp1G8.png)

The error (which is identical to the error at the top of this issue) is:

> ts/main.ts(1,8): error TS2656: Exported external package typings file 'E:/depot/untracked/test/node_modules/rxjs/add/observable/fromArray.d.ts' is not a module. Please contact the package author to update the package definition.

The corresponding `fromArray.d.ts` file is empty.

Maybe this occurs only when importing a typings file from a node module? I'm not sure what the actual cause is, so I'm still trying to figure out a way to set up a simplified testcase for you.

**Comment by mhegazy** [comment]
aah.. that is a different one, thanks for the info. i think we should relax this check, the error here is not meaningful.

**Comment by vladima** [comment]
#6846 should cover this

**Comment by mhegazy** [comment]
@masaeedu can you give `typescript@next` a try later tonight, and let us know if this scenario is working end-to-end or you are still running into issue.

**Comment by masaeedu** [comment]
@mhegazy Will do

**Comment by masaeedu** [comment]
@mhegazy Looks like it works

**Comment by blesh** [comment]
I know this isn't a helpful comment: But I'm super pleased with the work being done here. Thanks everyone.
