### ISSUE TITLE
Chained module resolution during npm install

### ISSUE THREAD

**Issue by erykwarren** [Microsoft/TypeScript#6424]
(related to #2338)

## Problem
Install a TS module _A_, itself depending on another TS module _B_. `npm` flattens the dependency structure under `node_modules` and therefore the resolution algorithm implemented by #2338 is broken when module _A_ is built.

## How to repro
1. clone https://github.com/erykwarren/ts-6424-repro
2. npm install

The project includes dependency on module ts-lib2, which itself depends on ts-lib1.  If you clone ts-lib2 by itself, and run npm install on it, it works. It's only when there's a chained dependency (with npm flattening the modules) that the problem occurs.

## Assumptions

Each project is built as an npm `postinstall` step. I couldn't find out if there is a recommended way to accomplish this differently.

**Comment by vladima** [comment]
it looks like this issue is fixed in out latest bits, can you give a try to our nightly build (`typescript@next`) to see if you still can see this problem.

**Comment by erykwarren** [comment]
It works very nicely. Thanks @vladima.

**Comment by erykwarren** [comment]
@vladima Is there anyway to port this fix in 1.7? If we have to wait for 1.8, what's the workaround?

**Comment by vladima** [comment]
this issue was fixed in two PRs: #5275 and #5461. I've ported them into release-1.7 in #6441, pinging @mhegazy for his decision if it is safe to take these changes.

**Comment by erykwarren** [comment]
@vladima Thanks for pushing this. However, I tried building a custom TS with the patch in 6441, and it didn't solve the issue....

**Comment by erykwarren** [comment]
@vladima Forget what I wrote, my test was wrong. It works! Thanks a lot.
