### ISSUE TITLE
Show error when compiling external modules with -out or -outFile option

### ISSUE THREAD

**Issue by Roaders** [Microsoft/TypeScript#6514]
See this issue:

http://stackoverflow.com/questions/34816304/why-does-adding-this-require-import-stop-node-js-outputing-to-the-console/34826050#34826050

This took me ages to get to the bottom of. no error messages to indicate I was doing something stupid just no output at all in the js file.
Suggest that an error message is displayed when we are compiling external modules with an invalid option like --out or --outFile

**Comment by DanielRosenwasser** [comment]
Hey, sorry about the frustration. Instead of giving an error, we decided to do the "right" thing. #5090 should fix this.

Can you give the nightlies a try and let us know how it works out?

**Comment by basarat** [comment]
The user is using `commonjs` based on the stackoverflow tsconfig. Hence it will still not work (https://github.com/Microsoft/TypeScript/pull/5090#issuecomment-163746277) and maybe should give an error :rose:

**Comment by Roaders** [comment]
That works fine in the nightlie. I get a message:

"Only 'amd' and 'system' modules are supported alongside --out"

Many thanks
