### ISSUE TITLE
TypeError when reading tsconfig.json

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#6620]
- start tsc in watch mode
- change the tsconfig.json to be invalid JSON

You get:

```
C:\Users\dirkb\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:31084
            var jsonOptions = json["compilerOptions"];
                                  ^
TypeError: Cannot read property 'compilerOptions' of undefined
    at getCompilerOptions (C:\Users\dirkb\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:31084:35)
    at Object.parseJsonConfigFileContent (C:\Users\dirkb\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:31074:22)
    at parseConfigFile (C:\Users\dirkb\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:31351:40)
    at performCompilation (C:\Users\dirkb\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:31362:45)
    at recompile [as _onTimeout] (C:\Users\dirkb\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:31454:13)
    at Timer.listOnTimeout (timers.js:92:15)
```

**Comment by ahejlsberg** [comment]
Which version of tsc are you using? Doesn't repro with compiler currently in master.

**Comment by mhegazy** [comment]
This repros in 1.7, it has since been fixed by https://github.com/Microsoft/TypeScript/pull/5589.

**Comment by DaveVoyles** [comment]
I've run into the same issue with 1.7.5 today as well.

**Comment by JPVenson** [comment]
I Agree Bug is still happen in 1.7.5

![capture](https://cloud.githubusercontent.com/assets/6794763/14207806/a28b34f6-f81c-11e5-8d21-9276610ab0b6.PNG)

**Comment by nspaeth** [comment]
In case anyone is still having this problem, in @JPVenson's case it is likely caused by the trailing comma after "noLib" in "compilerOptions".
