### ISSUE TITLE
MSBuild: Compile task output GeneratedJavascript does not match tsconfig.json or project settings

### ISSUE THREAD

**Issue by mykohsu** [Microsoft/TypeScript#6934]
In the typescript targets:

```
    <VsTsc
      ToolPath="$(TscToolPath)"
      ToolExe="$(TscToolExe)"
      TSConfigFile="%(ConfigFiles.Identity)"
      YieldDuringToolExecution="$(TscYieldDuringToolExecution)"
      ProjectDir="$(ProjectDir)"
      ToolsVersion="$(TypeScriptToolsVersion)"
      TypeScriptCompileBlocked="$(TypeScriptCompileBlocked)"
      ComputeOutputOnly="false">

      <Output TaskParameter="GeneratedJavascript" ItemName="emittedFiles" />
    </VsTsc>
```

The output parameter GeneratedJavascript includes a js file for every ts file in the project even if:
1. The file is not set to TypeScriptCompile.
2. The file is excluded or not matched in tsconfig.json.

Side affect is publish fails trying to copy files that do not exist.

**Comment by mhegazy** [comment]
This is something we are aware of and working on fixing. The change is not trivial and touches different parts of the build system. So hopefully we have this ready soon.

**Comment by mykohsu** [comment]
I have a workaround that uses msbuild to exclude missing files. Will post
it tomorrow.

**Comment by mhegazy** [comment]
The issue that the way the tasks work today is by "guessing" what the output will look like based on input. this is not feasible when using tsconfig.json. any more. we have a plan to make this work, but as noted above it is a rather big change and will touch different parts of the system. so we will be doing this for the next release.

**Comment by mykohsu** [comment]
The following excludes files that do not exist on file system.

```
<?xml version="1.0" encoding="utf-8"?>
<!--
This file is used by the publish/package process of your Web project. You can customize the behavior of this process
by editing this MSBuild file. In order to learn more about this please visit http://go.microsoft.com/fwlink/?LinkID=208121. 
-->
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Target Name="CustomExcludeFiles" 
          DependsOnTargets="$(ExcludeFilesFromPackageDependsOn)"
          BeforeTargets="ExcludeFilesFromPackage">

    <Message Text="Custom exclude..." Importance="high"></Message>
    <WriteLinesToFile Condition="$(EnablePackageProcessLoggingAndAssert)"
                      Encoding="utf-8"
                      File="$(PackageLogDir)\CustomExcludeFilesBefore.txt"
                      Lines="@(FilesForPackagingFromProject->'
                      From:%(Identity) 
                      DestinationRelativePath:%(DestinationRelativePath) 
                      Exclude:%(Exclude) 
                      FromTarget:%(FromTarget) 
                      Category:%(Category)
                      ProjectFileType:%(ProjectFileType)')" Overwrite="True" />

    <ItemGroup>
      <FilesForPackagingFromProject Remove="@(FilesForPackagingFromProject)" Condition="!Exists('%(FullPath)')" />
    </ItemGroup>
    <WriteLinesToFile Condition="$(EnablePackageProcessLoggingAndAssert)"
                      Encoding="utf-8"
                      File="$(PackageLogDir)\CustomExcludeFilesAfter.txt"
                      Lines="@(FilesForPackagingFromProject->'
                      From:%(Identity) 
                      DestinationRelativePath:%(DestinationRelativePath) 
                      Exclude:%(Exclude) 
                      FromTarget:%(FromTarget) \
                      Category:%(Category)
                      ProjectFileType:%(ProjectFileType)')" Overwrite="True" />
  </Target>
</Project>
```

**Comment by tbertenshaw** [comment]
Is the code above a workaround or the final fix? and is there guidance for adding this to a .csproj file? or .pubxml (publish profile?) or what ever file layout that continuous deployment (from git repo) uses when applied to an azure webslot?

**Comment by mhegazy** [comment]
This is not a workaround. we are working on a solution for the issue. we believe we should have one shortly. once we have that, we will publish it to [nuget](https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Nightly%20Builds.md#using-nuget-with-msbuild), and will report back to this thread.

**Comment by paulvanbrenk** [comment]
This is fixed in the [Nightly Nuget Package](https://www.myget.org/feed/typescript-preview/package/nuget/Microsoft.TypeScript.MSBuild) after build 1.9.0-beta-20160411-1.

**Comment by AndersSahlin** [comment]
Using `1.9.0-beta-20160412-1`, the issue reported in #7806 still exists.

I have pushed an update with the above version to the demo repo.

**Comment by Drol** [comment]
Nope, latest nightly still doesn't fix #6896.

**Comment by paulvanbrenk** [comment]
We had an issue with signing binaries, so I couldn't get this change in. I just kicked of another build, so the version which does have this fix should be up in about an hour.

**Comment by Drol** [comment]
I don't know if I'm missing something but I still get the following error. The project have app.ts file (and other ts-files) in the project but there are no app.js generated because "outFile" is set in tsconfig.json. Or am I trying to do something that is not supported?

`C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\Web\Microsoft.Web.Publishing.targets(2998,5): Error : Copying file app\app.js to obj\Production\Package\PackageTmp\app\app.js failed. Could not find file 'app\app.js'.`

**Comment by AndersSahlin** [comment]
Having issues with outDir as well:

`Error : Copying file output\js\file1.js to obj\Debug\Package\PackageTmp\output\js\file1.js failed. Could not find file 'output\js\file1.js'.`

https://github.com/AndersSahlin/TypescriptIssueRepo3 (Try publishing the web project)

I'm wondering about `<TypeScriptToolsVersion>1.8</TypeScriptToolsVersion>` - should that still be in the csproj, and if so should it be upped to `1.9` now?

**Comment by paulvanbrenk** [comment]
@AndersSahlin Yes, for this to work you have to either change the `TypeScriptToolsVersion` to 1.0, or remove it completely. I do have a fix so that won't be necessary in the future.

@Drol Can you share your project, or confirm if removing the `TypeScriptToolsVersion` works for you?

**Comment by AndersSahlin** [comment]
@paulvanbrenk I tried removing the tag and the publish succeeded but without copying any generated js-files. It's quite late here now but I will give it another go tomorrow.

**Comment by paulvanbrenk** [comment]
Ok, it looks like the behavior for MSBuild is different when referencing the tasks through a NuGet package vs. from the standard location in Program Files... I did not expect that, and don't have an immediate fix.

**Comment by Drol** [comment]
@paulvanbrenk Yes that works, thanks :-)

Howerver, the js-file generated from the outFile configuration have to be included in the project to be included in the publish. I don't know if that's by design or not. But its fine in our case.

**Comment by paulvanbrenk** [comment]
So I figured out what was going wrong... and I have a fix. Current ETA for testing would be Tuesday.

@Drol you shouldn't have to include the files in the project, my fix should resolve that.

**Comment by paulvanbrenk** [comment]
And checked in, should be on MyGet tonight.

**Comment by tbertenshaw** [comment]
will a vsix release be available for this soon or is it to be part of the v2 release?

**Comment by mhegazy** [comment]
TypeScript is not distributed as a visix package. the fix should be available in the nightly nuget package, see https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Nightly%20Builds.md#using-nuget-with-msbuild for more details.

An installer with the fix will be available with the next TS 2.0 release.

**Comment by AndersSahlin** [comment]
@paulvanbrenk I have been away for some time but when verifying the fix today I still can not get the generated JS-files to copy when publishing a project. Disabling the `outDir` flag does not help.

Pushed an update to my test repo: https://github.com/AndersSahlin/TypescriptIssueRepo3

**Comment by danrien** [comment]
Was using the nightlies to resolve this issue, just updated to the beta, and this issue has re-appeared

**Comment by paulvanbrenk** [comment]
@AndersSahlin Sorry for the slow response. I'm going to re-open your original bug, since it is a different scenario from this bug.
