### ISSUE TITLE
jsdoc error function as parameter for callback 

### ISSUE THREAD

**Issue by Thaina** [Microsoft/TypeScript#6993]
I have object with function like this
```
db.query({ /* queryParameter */ },function(err,data) {  });
```

So I write jsdoc for pass this object in my function. And it got error

![screen shot 2559-02-10 at 2 30 14 pm](https://cloud.githubusercontent.com/assets/1042507/12941269/59f92d56-d003-11e5-8728-9e6b8635b4c0.png)

Also jsdoc is not support both `@typedef` and `@callback` so I got stuck here

**Comment by RyanCavanaugh** [comment]
PR pending

**Comment by RyanCavanaugh** [comment]
Fixed in TypeScript@next. Thanks!

**Comment by Thaina** [comment]
@RyanCavanaugh I was install TypeScript@next and got 1.9.0-dev.20160308

Still not fixed

**Comment by RyanCavanaugh** [comment]
Can you post the exact code to repro? Thanks!

**Comment by Thaina** [comment]
@RyanCavanaugh

```
/** @param {function({string,string}):void} onFinish
 *	@param {function({string}):void} onError */
function GetData(onFinish,onError) {
	
}
```

Actually it is #7254 that you was closed because you think it duplicate with this. It is difference

**Comment by Thaina** [comment]
Also this is nearly similar. 2 functions in same class with multiple function with parameter also make the same problem

var asyncLib	= {
	/**
	 * @template T
	 * @param {T[]} array
	 * @param {function(T,number,function():void):void} action
	 * @param {function():void} onFinish
	 */
	ForEach: function(array, action, onFinish) {
		/** @type number */
		var i = arguments[3];
		if (!(i > 0))
			i = 0;

		if (i >= array.length)
			return onFinish();

		action(array[i], i, function () {
			setImmediate(asyncLib.ForEach, array, action, onFinish, i + 1);
		});
	},

	/**
	 * @template T,U
	 * @param {T[]} array
	 * @param {function(T,number,function():U):U} func
	 * @param {function(U):void} onFinish
	 */
	Map: function (array, func, onFinish) {
		/** @type {[]} */
		var result = arguments[3];
		if (!result && !(result.length > 0))
			result = [];

		if (result.length >= array.length)
			return onFinish(result);

		func(array[result.length], result.length, function (res) {
			result.push(res);
			setImmediate(asyncLib.Map, array, func, onFinish, result);
		});
	}
};

![image](https://cloud.githubusercontent.com/assets/1042507/13625874/d3defb0e-e5ee-11e5-9fdb-f54b87a1f256.png)

**Comment by RyanCavanaugh** [comment]
Thanks!

**Comment by RyanCavanaugh** [comment]
@Thaina what's the intended meaning of `{function({string,string}):void}` ? To me this looks like a function taking one argument whose type is an object with two properties which are both named `string`, which should be an error

**Comment by Thaina** [comment]
@RyanCavanaugh I was actually use

```
/** @param {function(string,string):void} onFinish
 *  @param {function(string):void} onError */
function GetData(onFinish,onError) {
}
```

That thing you see is I try to hack by random syntax to see if it fix. And it not related, it was still cause the same error

**Comment by RyanCavanaugh** [comment]
OK, makes sense. Looks like the real problem is that the fix for this went into release-1.8 branch and not master, I'll port it over.
