### ISSUE TITLE
Allow Default Values for String Literal Types

### ISSUE THREAD

**Issue by blink1073** [microsoft/TypeScript#7223]
**TypeScript Version:** 

1.8.2.

**Code**

``` ts
// A self-contained demonstration of the problem follows...
class Foo {
    bar: "fizz" | "buzz";
}

class Bar extends Foo {
    bar = "fizz";
}
```

**Expected behavior:**
`Bar.bar` is initialized to `"fizz"`;

**Actual behavior:** 
`Type 'string' is not assignable to type '"buzz"'`

**Comment by blink1073** [comment]
This works:

```typescript
interface Foo {
	bar: "fizz" | "buzz"
}

class Bar implements Foo {
	bar: "fizz" = "fizz";
}
```

as does this:

```typescript
interface Foo {
	bar: "fizz" | "buzz"
}

class Bar implements Foo {
	bar: "fizz" | "buzz" = "fizz";
}
```

I'd like to see the former inferred from the original, or at least allow assigning a default value.

**Comment by sccolbert** [comment]
Another example:

```typescript
class Foo {
	bar: "fizz" | "buzz";
}

class Bar1 extends Foo {
	constructor() {
		super();
		this.bar = "fizz";  // okay
	}
}

class Bar2 extends Foo {
	bar = "fizz";  // fail
}
```

**Comment by DanielRosenwasser** [comment]
I think #6118 should fix this. CC @sandersn

**Comment by blink1073** [comment]
I ran the original code through the 2.0.2 compiler, and the error remains.

**Comment by blink1073** [comment]
The message has changed to:

```typescript
test.ts(6,7): error TS2415: Class 'Bar' incorrectly extends base class 'Foo'.
  Types of property 'bar' are incompatible.
    Type 'string' is not assignable to type '"fizz" | "buzz"'.
```

**Comment by sandersn** [comment]
Yep, neither #6118 or #10610 are merged yet. We are trying to determine how bad the breaking change is right now.

**Comment by blink1073** [comment]
Ah, fair enough.

**Comment by RyanCavanaugh** [comment]
Duplicate #10570
