### ISSUE TITLE
Request: add TypeScript support for UWP projects in Visual Studio

### ISSUE THREAD

**Issue by lilred** [Microsoft/TypeScript#8950]
It's not at all obvious right now how to:
1. Write a UWP app in TypeScript;
2. Debug that app.

A prepared template would be lovely for this.

---

Workaround for the debugging issues in VS 2015.2 and 2015.3 (s/o @minestarks):

> I assume you're running in an English locale here, otherwise I don't think the workaround is applicable.
> 
> Close VS.
> In an administrator command prompt:
> 
> ```
> cd %ProgramFiles(x86)%\msbuild\microsoft\visualstudio\v14.0\typescript
> mkdir en
> copy *.xaml en
> copy TypeScript.Tasks.dll en\TypeScript.Tasks.resources.dll
> ```
> 
> Now open your UWP project again, the TS files should be visible and building when you build your project.

**Comment by mhegazy** [comment]
UWP projects are not currently supported for TS. we are working on enabling them, including type definitions, templates, and debugging.

**Comment by lilred** [comment]
>UWP projects are not currently supported for TS. 

Could you clarify that somewhere in the documentation?

>we are working on enabling them, including type definitions, templates, and debugging.

Exciting news!

**Comment by grork** [comment]
Do we have a time frame? I'm less bothered by full template support, but people have existing projects that were broken by Update 2/1.8.

**Comment by SaschaNaz** [comment]
TS works anyway on UWP when every compiled js file is added to project, while we have to build twice to run. Debug should just work, at least my projects do.

**Comment by lahloumehdi** [comment]
The bad thing is that TypeScript it worked perfectly with uwp/visual studio 2015 Update 1 and Typescript 1.7.6.

There was something broken after the update 2 of VS or the update of typescript (1.8>)


I have a very big UWP project that use TypeScript and I'm not able to upgrade VS or TypeScript because of to this issue ...

**Comment by SaschaNaz** [comment]
@lahloumehdi Does your problem also happen on VS2015 Update 3?

**Comment by lahloumehdi** [comment]
@SaschaNaz Unfortunately no.

**Comment by lilred** [comment]
@lahloumehdi so the issue is fixed in VS2015 Update 3? Great news!

By the way, [last time I checked](http://stackoverflow.com/questions/37604906/how-can-i-break-inside-a-typescript-uwp-app-in-visual-studio) this was broken in VS15 Preview 2. Any idea if it was fixed at some point?

**Comment by lahloumehdi** [comment]
@lilred sorry I misspoke. The problem persists in the update 3 of VS cc @saschanaz

**Comment by minestarks** [comment]
@lahloumehdi While we work on proper support for this scenario in Visual Studio 15, here is a workaround for VS 2015 Update 2 and 3 that I hope will restore the Update 1 behavior for you. The behavior you're seeing is potentially due to a TypeScript installation bug.

I assume you're running in an English locale here, otherwise I don't think the workaround is applicable.

Close VS.
In an administrator commant prompt:

`cd %ProgramFiles(x86)%\msbuild\microsoft\visualstudio\v14.0\typescript`
`mkdir en`
`copy *.xaml en`
`copy TypeScript.Tasks.dll en\TypeScript.Tasks.resources.dll`

Now open your UWP project again, the TS files should be visible and building when you build your project.

Let me know how this works for you. I apologize for the trouble!

**Comment by lilred** [comment]
IT WORKS! Thank you @minestarks!

**Comment by grork** [comment]
I can also confirm it works great on Update 2! Thank you @minestarks!

**Comment by minestarks** [comment]
@lilred Glad to hear! For VS 15, try running the same steps but replacing v14.0 with v15.0 in the folder path. Just tried it out with VS 15 Preview 3 and it worked for me, barring this other issue I noticed:

If you install VS 15 Preview 3 side by side with VS 2015 Update 3, the MSBuild task definitions may get corrupted (for both VS installations). If you start to see build errors referencing Microsoft.TypeScript.targets, back up and delete your %ProgramFiles(x86)%\msbuild\microsoft\visualstudio\ **v14.0**\typescript and **v15.0**\typescript folders, then from the Programs and Features UI in Windows, select Visual Studio 15 and repair it. 

After you do this, you will need to re-run the [original steps](https://github.com/Microsoft/TypeScript/issues/8950#issuecomment-231170405) again to create the "en" directory and fix your UWP/TS project.

Sorry for all the manual steps. We're working on making this a lot less painful in the next update.

**Comment by lahloumehdi** [comment]
@minestarks Thank you, thank you, thank you  !!

**Comment by lilred** [comment]
By the way, what ambient type definition file do you suggest for UWP? Should I use `lib.winrt.d.ts`?

**Comment by StrahilKazlachev** [comment]
@lilred I think there was also `winrt-uwp.d.ts`.

**Comment by minestarks** [comment]
Yes, DefinitelyTyped is currently the best source for UWP type definitions. For VS15 we are working on generating these definitions automatically for your project, which should provide better support for changing APIs and third party libraries.

**Comment by lahloumehdi** [comment]
Oh ! That is an awsome feature ! VS15 (will) rocks

**Comment by lilred** [comment]
FYI: the most recent update `vs14-kb3165756` appears to undo the workaround. I had to do it again.

**Comment by lahloumehdi** [comment]
Uunfortunately the last update of VS2015 breaks undo the workaround :( @minestarks

**Comment by SaschaNaz** [comment]
Installing VS15 side by side with VS2015U3 does not display .ts files and does not let me deploy UWP apps. [The tip](https://github.com/Microsoft/TypeScript/issues/8950#issuecomment-231239827) didn't work as repairing didn't restore v15.0/typescript folder. Copy-pasting from v14.0/typescript made .ts files visible but I still cannot deploy UWP apps.

**Comment by SaschaNaz** [comment]
I've found that VS15 Preview 5 gives us WinRT type definitions with its file name `winrtrefs.d.ts` :D

**Comment by minestarks** [comment]
@SaschaNaz yup - in Preview 5, types from the Windows API and any other WinRT references should automatically be included in your TS build and Intellisense context. Go ahead and try it out and please file issues :)

**Comment by IngoChou** [comment]
Hello,
My project is developed in TYPESCRIPT.
How can I distinguish an application is website or is UWP App in runtime?
Because I want to use different UI between website and UWP.
Thanks.

**Comment by SaschaNaz** [comment]
@IngoChou Try `let isUWP = typeof Windows !== "undefined"`.

**Comment by IngoChou** [comment]
@SaschaNaz 
Thank you very much. It works well.
